### ISSUE TITLE
Kickoff

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#1]
Ok, we have a clean history, version goes from `0.0.1` for now, we can figure that out later. It's based on the copy from @johot's fork and I've removed some obvious stuff like Provider/inject and some tests that were working with these two, It's still heavily broken, but good enough for the kickoff.

I certainly need help as I am not using `mobx-react` in its full glory, eg. prop types, devtools, SSR, transactions... so a lot of stuff does not make a full sense to me just yet.

@mweststrate Would you be against writing it directly in TypeScript? I assume it's ok considering that `mobx` itself is full blown TypeScript project. Would be certainly much easier to maintain typings.

**Let's keep this issue to track who is going to do what do avoid duplicate work.**

I am going to focus purely on the observer/Observer pair, rewrite to TypeScript and hopefully make some tests.

**Comment by FredyC** [comment]
I've cleaned up src folder to strip down to basics. I've most likely removed too much, eg. devtools support, but I assume it will work differently anyway. Next step ... tests

**Comment by FredyC** [comment]
I've removed/disabled most of the tests for now and made the first one working for `observer`. Travis is enabled and link in the README updated to reflect that tests are passing. Perhaps it's time to switch to PRs instead of hogging master by me? :)

I've switched to `react-testing-library` instead of `enzyme` as it feels just better. Would love to hear some opinions on this. I am influenced by Kent's course a big time :)

There is also simplified README to explain more about this project.

**Comment by FredyC** [comment]
I've run into one test that's using computed property on a class component and got a bit stumped how that should actually work with a function components? Does it even make sense to have computed properties in there? @mweststrate ?

```js
const Component = props => {
    const computed = React.useMemo(() => {
        return mobx.computed(() => props.odata.x)
    }, [])

    return (
        <span onClick={props.doStuff}>
            {computed}
        </span>
    )
}
```

This does not work, React complains that `computed` is object and does not know how to render that. Am I doing it wrong somehow? The original test with class component looks like that...

https://github.com/mobxjs/mobx-react/blob/2e2cf2241baaa3a47e8a125645dade57a2186927/test/observer.test.js#L448

**Comment by FredyC** [comment]
Some further thoughts after night sleep. We have the `useObservable` which can be used like this and it works well.

```js
const TestComponent = observer(() => {
    const obs = useObservable({
        x: 1,
        y: 2,
        get z() {
            return this.x + this.y
        }
    })
    return <div onClick={() => (obs.x += 1)}>{obs.z}</div>
})
```

However, what if I want only a single computed value without wrapping it into an object? I tried to create `useComputed`, but for some reason, it's not working. I am most likely missing something, but `observe` never triggers.

```ts
function useComputed<T>(initialValue: () => T): T {
    const value = computed(initialValue)
    const [state, setState] = useState(value.get())
    useEffect(() => {
        return value.observe(change => {
            setState(change.newValue)
        })
    }, [])
    return state
}
```

**Comment by FredyC** [comment]
Well, thanks for cooperation everyone 🤣 The first version is done and published. Closing this issue and we can discuss bugs and further improvements there.

**Comment by johot** [comment]
Woah 😄 Good Job @FredyC !

**Comment by mweststrate** [comment]
Good stuff indeed! Well done @FredyC  :)
