### ISSUE TITLE
How to access mobx store inside useEffect hook

### ISSUE THREAD

**Issue by talha131** [mobxjs/mobx-react-lite#114]
I have gone through the ReadMe and other issues but cannot figure out following use case.

```js
const Example = ({ teamStore }) => {
  React.useEffect(() => {
    if (location.pathname === teamStore.path) {
      document.title = 'You are here';
    }
  });

  return (
    <div>
      <Observer>{() => <h1>teamStore.title</h1>}</Observer>
    </div>
  );
};
```

What I am trying to do is to access the mobx store `teamStore` inside `useEffect` hook. Every time the hook is run, I want to make comparison of `location.pathname` with entries in the `teamStore`.

Inside React component, I can use `<Observer>` or `observer()`. But how do I observe changes in the the store inside a function?

## Background

My Ui has a sidebar and a main view. When you select menu item in the sidebar then main view and route changes.

What I want is when user enter direct URL in the address bar, then main view and menu selection should change. In this case, main view changes fine, thanks to react-router.

Problem is sidebar menu selection. For this I `useEffect` hook. Certain menu items are generated dynamically using mobx store. `useEffect` needs to compare the `location.path` with values in mobx store and then select the corresponding menu item in the sidebar.

But as stated, I cannot figure out how to access mobx store inside useEffect hook.

What can I do here? Is it even possible? If not than what can be a workaround?

**Comment by FredyC** [comment]
That's easy :) 

```js
  React.useEffect(() => mobx.autorun(() => {
    if (location.pathname === teamStore.path) {
      document.title = 'You are here';
    }
  }));
```

**Comment by talha131** [comment]
Thanks a lot @FredyC.

I was so close. You know I was off by a function. I had tried

```js
const test = autorun(() => {
    console.log(teamStore.teamCount);
});

React.useEffect(test);
```

And of course it didn't work. From your answer, I realized correct way is

```js
React.useEffect(() => test);
```

Thanks again for your help. I had wasted almost an hour on it. Much appreciated!

**Comment by alsotang** [comment]
I think the problem is mobx doesn't know you access the `teamStore.path` property in the `Example`. So mobx doesn't record that the `Example` is reactive to `teamStore.path`.
For a consistent code style, what if you wrap the content of the `Example` component in a `useObverser` hook?

**Comment by FredyC** [comment]
@alsotang Yea, for side effects like that it has to be done with autorun/reaction directly. The observer does not see inside other functions. It's the same with a render prop, it won't see any observable inside of it.

```jsx
const Comp = ({ store }) => {
  return useObserver(() => (
    <>
       <div>{store.value} is correctly observed</div>
       <RenderProp>{() => (
          <div>never gonna react to change of {store.otherValue}</div>
       )}</RenderProp>
    </>
  ))
}
```

**Comment by talha131** [comment]
@FredyC can you explain why 

```js
React.useEffect(test); // does NOT work
// but
React.useEffect(() => test); // works
```

from [my sample code above](https://github.com/mobxjs/mobx-react-lite/tree/HEAD@%7B2019-03-29T22:25:46Z%7D).

The reason for my confusion is as follows.

From [useEffect()](https://reactjs.org/docs/hooks-reference.html#useeffect) docs, 

> [`useEffect()`] Accepts a function that contains imperative, possibly effectful code.

And from [`autorun` docs](https://mobx.js.org/refguide/autorun.html)

> The return value from autorun is a disposer function

`React.useEffect(test)` has `test` function argument which in turn returns a disposer function.

`React.useEffect(() => test)` has an anonymous function argument which in turn returns `test` function.

What difference does this anonymous function make that `useEffect` and mobx starts working with it?

**Comment by FredyC** [comment]
I don't know where is your `test` defined, but there is an obvious difference in that example. In the first case, the `test` is called by `useEffect` and runs the code within. In the second case, the body of `useEffect` is defined by the anonymous function and it implicitly returns the `test` which would be called in a cleanup phase. These are JavaScript basics really, nothing to do with MobX or React.

**Comment by talha131** [comment]
Thank you @FredyC. 

> These are JavaScript basics really, nothing to do with MobX or React.

My apologies. I perhaps didn't state my question correctly.

Anyone else coming to this issue and have similar confusion then please see this StackOverflow question and the accepted answer to it.

https://stackoverflow.com/q/55451484/177116

**Comment by FredyC** [comment]
For the sake of closure here, I've included recipe about side effects on the new docs site.

https://mobx-react.netlify.com/recipes-effects
