### ISSUE TITLE
Performance: Observer vs observer

### ISSUE THREAD

**Issue by urugator** [mobxjs/mobx-react-lite#116]
Following up on https://github.com/mobxjs/mobx-react-lite/issues/94#issuecomment-478618062 

I checked the `Observer` impl in `mobx-react-lite` and the impl is slightly different than the one in current `mobx-react`.
Therefore the statement: 

> due to the way it's implemented, it unnecessarily runs prop comparison (unless the callback isn't inlined, which is rarely the case).

doesn't apply to `mobx-react-lite`. For comparison:  

```javascript
// current mobx-react-lite
function ObserverComponent({ children, render }: IObserverProps) {
  const component = children || render
  if (typeof component !== "function") {
    return null
  }
  return useObserver(component)
}

// =>
// modified version to match the current mobx-react
// the difference is that this one applies `memo`
const ObserverComponent = observer(({ children, render }: IObserverProps) => {
  const component = children || render
  if (typeof component !== "function") {
      return null
  }
  return component();
})
```

Sidenote regarding the code above: I suggest to rename the `component` variable to `callback`, it doesn't represent a *component*.

> It always re-renders together with parent, because it always receives new children (the closure)

Here is a sandbox to demonstrate the difference between `observer` and `Observer`:
https://codesandbox.io/s/xlr4z37z6o

> Wouldn't be enough to just wrap it into React.memo same as the observer

No. As noted above this is already done in case of current `mobx-react`.
The problem is that any component which depends on children/callback is non-optimizable unless you memoize the children/callback in parent, which is rarely the case, because the API is designed for inline use:

```javascript
// Inline is non-optimizable
function Parent() {   
  return <Observer>{() => 'child'}</Observer>  
}

// Wrapped in memo
// optimizable in parent by memoizing callback 
function Parent() {
  const render = useCallback(() => 'child', []);
  
  return <Observer>{render}</Observer>  
}
```

**Comment by FredyC** [comment]
Thanks for the detailed report. I am wondering if it's really such a big deal in the end. Yes, it does re-render, but it that only means it runs `useObserver` again which itself doesn't do much on a component update.

And if you actually care about a performance of the component included within the `Observer` callback, you can optimize that with `React.memo` just fine.

I don't know. Until the Hook came to the light, we were using render prop components like that without much of the concern. Feels like it would require some benchmarks to see if there is an actual problem. And as you are saying there isn't really much what we can do and it's about consumers to memoize callback.

It's definitely worth mentioning in a new docs site I am planning (#115).

**Comment by urugator** [comment]
> useObserver again which itself doesn't do much on a component update.

Correct me if I am wrong, but it runs the rendering logic, returns new element, forcing react to reconcile etc. 
What more it should do (to consider it a subject of optimization)? 

> And if you actually care about a performance of the component included within the Observer callback, you can optimize that with React.memo just fine.

If you can apply `memo`, then you can use `observer` directly. The point of `Observer` is that you don't need a component.

> render prop components like that without much of the concern.

As I have already mentioned in v6 discussion thread (in relation to implicit `memo` for `observer`), react is usually fast enough by itself.

Imho the only problem is to advertise/consider the `Observer` as a one-to-one replacement for `observer`.

**Comment by FredyC** [comment]
> Correct me if I am wrong, but it runs the rendering logic, returns new element, forcing react to reconcile etc.

I am not well versed with terminology, but if by reconcile you mean throw away stuff to replace it with new stuff, it doesn't do that. AFAIK it won't reconcile as long as you return same component type with same props. Doesn't matter if it's a different element.

I've modified your example slightly just to show that component rendered within `Observer` is not thrown away, it's just updated. That alone shouldn't be expensive as it won't be touching DOM at all.

https://codesandbox.io/s/jzj5j8mqpv

> If you can apply `memo`, then you can use `observer` directly. The point of `Observer` is that you don't need a component.

That depends, I can imagine doing something like this which allows you to keep observable at one layer and let other "dumb" component pretend it works based on props changes only, not knowing anything about MobX. I am mostly saying it's one of the options if someone is seeking optimization there.

```jsx
function Parent() {   
  return <Observer>{() => <Child value={store.value} />}</Observer>  
}
```

> Imho the only problem is to advertise/consider the `Observer` as a one-to-one replacement for `observer`.

You are right, readme is misleading. It was written way before the `useObserver` became a thing and nobody has updated it since then. If you have some better wording, PR is welcome for sure :)

**Comment by urugator** [comment]
**IMPORTANT**
I've noticed that `observer` from `mobx-react v6` relies on `Observer` from `mobx-react-lite`. 
You have to change the `Observer` so that it uses `memo`, otherwise `observer` won't work as intended: https://github.com/mobxjs/mobx-react/blob/v6/src/observer.js#L143
(I will try to reproduce in sandbox to be sure...)

> by reconcile you mean throw away stuff to replace it with new stuff

By reconcile I mean a process of determining which part of real DOM has to be replaced.
Once the component updates, react has to compare the returned element with the previous one.
The only possible optimization is to prevent this comparison (diffing) by preventing the component update.
Which in our case means preventing an invocation of `useObserver`.

> you return same component type with same props.

You're not returning components with props, but native elements and component elements.
In case of component elements, react only compares the component type and key to find out whether a new component instance has to be created or existing one has to be reused (the goal is to preserve component state inbetween renders).
It doesn't compare props, because it doesn't know how prop changes translate to DOM changes.   

> I am mostly saying it's one of the options if someone is seeking optimization there.

Ok but the Parent still needs to be mobx aware, so why would you prefer it over:   
```javascript
const Parent = observer(() => {
  return <Child value={store.value} />;  
})
```
Imho it really kills the point of `Observer`.

> If you have some better wording

Probably I wouldn't suggest `<Observer>` for anything but [a workaround for render callbacks of 3rd party components](https://github.com/mobxjs/mobx-react/issues/484#issuecomment-391685354).
`<Observer>` was kind of attractive, because it was the only way to use observables without the need to patch the component, which is no longer true ... so anything else seems superior atm?

**Comment by JabX** [comment]
I've had success with multiple <Observer> blocks in the render of a complex (class) component, to have my render split into several sub computations that only rerender part of the render tree. You can get the same result with several fully-fledged observer components, but it's simpler to write and it doesn't force you to decouple things that doesn't make sense of their own and think about what props you need to pass down to these components... But yeah, it's not exactly a best practice or anything and if you do that you have to make sure that the whole render never retriggers. Also, you need observable props if you want to use props inside the Observer callbacks, so all this only works with classes… which are still better suited for complex components and this is the only case you'd want to use it, so I guess it's fine.

Observer works great for render callbacks too, but I agree that both of these use cases are the only ones where you'd want to use it. It can remain as a lowe level API like useObserver (but at least it has some actual use cases), especially since it's used by observer internally.

I don't think the overall situation will/would have to change with hooks about all of this : just use observer everywhere and Observer in the rare cases you can't, just like we've been doing for a while.

**Comment by FredyC** [comment]
> I've noticed that `observer` from `mobx-react v6` relies on `Observer` from `mobx-react-lite`.
> You have to change the `Observer` so that it uses `memo`, otherwise `observer` won't work as intended:

I am not sure it's such a huge issue since it's for class components only (RIP).

> The only possible optimization is to prevent this comparison (diffing) by preventing the component update.
> Which in our case means preventing an invocation of `useObserver`.

Ok, so we are on the same page, but you are using correct terms :) I think we can agree it's pretty much just a micro-optimization to prevent extra diffing (which React does all the time). I kinda doubt anyone would ever notice it or consider a bottleneck. Without an actual benchmark, it's purely theoretical what's more performant.

> `<Observer>` was kind of attractive, because it was the only way to use observables without the need to patch the component, which is no longer true ... so anything else seems superior atm?

Agree with this. Also considering it's effectively a one-liner (minus render prop check), it could be another candidate for removal along with utility hooks and instead offer it as a recipe on the new site with explanation of all cons and pros.

**Comment by urugator** [comment]
@JabX
 
>  to have my render split into several sub computations that only rerender part of the render tree.

Yea, I think thats reasonable (as an optimization). 

> make sure that the whole render never retriggers

Well not necessarily never ... just "significantly" less often than the individual `Observer`s

> Also, you need observable props if you want to use props inside the Observer callbacks

Why? The prop change will always lead to parent update and therefore the invalidation of `<Observer>`s as demonstrated above.
 

@FredyC

> I am not sure it's such a huge issue

There is no technical or practical reason to introduce inconsitency here.

> it's pretty much just a micro-optimization

It's exactly the same optimization as it is in `observer`.
I don't say it should be one way or another, but there should be some consensus and consistency about whether it's worth it or not.


Found out why I can't reproduce the problem ... haven't realized that sCU is still patched in classes :)

**Comment by FredyC** [comment]
> It's exactly the same optimization as it is in `observer`.

Is it? As you said, it would only work if you (as a consumer) keep callback memoized. With `observer` it works without such a ceremony. I would not say those solutions are comparable. In fact, in most cases, it's an additional cost to check for unchanged props.

Of course, the `mobx-react` is a different story and it should implement its own `Observer` for internal use which can drop prop types checking altogether to be even slightly faster.

**Comment by JabX** [comment]
> > Also, you need observable props if you want to use props inside the Observer callbacks
> Why? The prop change will always lead to parent update and therefore the invalidation of `<Observer>`s as demonstrated above.

My mistake, I was incorrectly referring to an issue I had a few weeks ago on a legacy project in MobX 3 where its observable props implementation didn't work properly in a specific case (it worked in 4 so I ended up updating the project). I thought initially that the problem was surfaced because of Observer but in the end it was earlier on.

**Comment by urugator** [comment]
@FredyC Your original statement was:

*"Yes, it does re-render, but that only means it runs useObserver again which itself doesn't do much on a component update."* 

I am just saying that this isn't a valid argument, because in both cases the subject of optimization is a rendering logic of an arbitrary complexity. The amount of prevented extra work is the same in both cases. They both do "this much" on component update.

> With observer it works without such a ceremony.

It works quite the same. If you pass any inlined callback or element to the `observer` it will be invalidated every time parent's rendered (and runs unecessary prop check).
We can make some opinionated assumptions/estimations about how often non-memoized (or static) callbacks/elements are passed to `observer/<Observer>`, but that's a different argument than *"it doesn't do much on component update"*.

**Comment by FredyC** [comment]
> If you pass any inlined callback or element to the `observer` it will be invalidated every time parent's rendered (and runs unecessary prop check).

Um you cannot pass an element to `observer`. Callback is surely possible, but that's pretty much considered a functional component. I wouldn't call it a _callback_ really.

I don't follow why would you use `observer` inline really. What would be a purpose of that? Components are usually statically defined. It's kinda discouraged by React itself to declare components inline as it will always cause remount and not just reconciliation. I was caught of guard with this when trying to be too clever with `React.lazy` ... https://github.com/facebook/react/issues/14299

So yea I would argue it's very different problem ;)

**Comment by urugator** [comment]
You are misunderstanding:
```javascript
const Child = observer((props) => {
  return el('div', { onClick: props.onClick },
    props.renderHeader(),
    props.children,
    props.rendeFooter(),
  )    
})

function Parent() {
  return el(Child, {
    renderHeader: () => 'Header', // breaks memo
    onClick: () => console.log('Clicked'), // breaks memo
    renderFooter: () => 'Footer', // breaks memo
  },
    el('div', null, 'Body'), // breaks memo
  )
}

// A "fix"
function Parent() {
  const renderHeader = useCallback(() => 'Header', []);
  const renderFooter = useCallback(() => 'Footer', []);
  const onClick = useCallback(() => console.log('Clicked'), []);
  const body = useMemo(() => el('div', null, 'Body'), []);
  
  return el(Child, {
    renderHeader,
    onClick,
    renderFooter,
  },
    body,
  )
}
```

**Comment by FredyC** [comment]
Ok, that makes sense, but it's not much related. In the `Observer` you are passing a callback with a different intention - to declare observed content. With `observer` you passing some callbacks if your component needs it, but it's not like very component does that. It's completely up to you to `useCallback` if you are about optimization. You cannot do the same with `Observer`.

Let's cut this discussion, I guess we are understanding each other now :) If you think the `React.memo` should be around the `Observer`, feel free to PR it. Problem is it won't really help so it feels like extra check for nothing.

**Comment by SrBrahma** [comment]
Hey, so, what are the best ways to improve performance? I was just wrapping useObserver() in my FC returns, but I suspect that it was making my navigation lags on transition.

**Comment by FredyC** [comment]
@SrBrahma Please, don't comment on old and closed issues as only a few people will see that here.

You can use GH Discussions now if you want to dive deep into a performance talks. However, keep in mind that without any sort of benchmarks it's purely theoretical and every step you take to improve perf can as well make it worse.

Also, it was said in many other places. MobX is not built with performance as a major concern. It's made to offer a great developer experience which of course comes with tradeoffs. In summary, if you are building something that needs really every bit of performance, then MobX is not a right tool for you. With regular apps it hardly matters and performance bottlenecks are usually somewhere else.

**Comment by urugator** [comment]
@FredyC

> MobX is not built with performance as a major concern

Well the only thing mobx does is making sure that only the relevant components are invalidated on state mutation, instead of the whole component tree (react's default behavior).
So that's better be the case, otherwise you can throw mobx away and replace it with single `dispatch/action` function that simply invalidates the root component ... that would be a lot better DX.
Mobx is an alternative optimization technique to immutability+memoization.

@SrBrahma

Use `observer` whenever possible.
Depend on observable stores rather than props.
Pass stores with context, don't mutate the context value itself (don't swap stores).
Avoid callbacks.
Avoid `props.children`.

Ideally all your components would look like:
```javascript
observer(() => { // no props
  const storeA = useContext(StoreAContext); // storeA is the same for the whole app lifetime
  const storeB = useContext(StoreBContext);	

  return (<div className="{storeA.foo ? 'class1' : 'class2'}">
	<Child />
   </div>)
})
```
The problem is such component is almost non-reusable, but unless you're creating an UI library it's usually a less of an issue.
The only time when you really have to pass some props is when you need to display a dynamic number of records, then you have to pass some ID that identifies the record.
However don't take these too seriously, the main idea is that you slap `observable` and `observer` everywhere without much thinking and it miraculously works in more or less optimal way.
