### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AwesomeObserver** [mobxjs/mobx-react-lite#125]
observer or useObserver, what is preferred for massive list component?

**Comment by FredyC** [comment]
It's totally up to you. If you like HOC more, go with that. Otherwise, `useObserver` which (obviously) doesn't put `React.memo` around the component.

**Comment by FredyC** [comment]
@AwesomeObserver Have a look at new docs site with some comparison of each of these approaches: https://mobx-react.js.org/observe-how

**Comment by AwesomeObserver** [comment]
> @AwesomeObserver Have a look at new docs site with some comparison of each of these approaches: https://mobx-react.js.org/observe-how

Wow, thanks!
