### ISSUE TITLE
mobx-react to mobx-react-lite upgrade notes

### ISSUE THREAD

**Issue by ajbarber** [mobxjs/mobx-react-lite#126]
Would someone please tell me if <StoreContext.Provider/> as referred to in the readme will be backwards compatible with existing mobx-react apps? Specifically, will I be able to swap out my mobx <Provider> wrapper on the root of my tree and replace it with <StoreContext.Provider />, and have all my existing class and (non hook) function components still work?

Put another way I am interested in incrementally upgrading an existing mobx-react app, which uses the mobx Provider mechanism. So I need to both provide the root and it's child stores to 'legacy' components, but also provide same stores to new hook components. 

Thanks.

**Comment by FredyC** [comment]
If you care about compatibility, please do try `mobx-react@6.0.0-rc.4`

**Comment by FredyC** [comment]
@ajbarber Have a look at new migration guide if still struggling: https://mobx-react.js.org/recipes-migration

**Comment by ajbarber** [comment]
Much appreciated, have decided to wait until you merge up with mobx-react 6.00. 
    On Tuesday, 28 May 2019, 3:08:52 pm GMT+8, Daniel K. <notifications@github.com> wrote:  
 
 
@ajbarber Have a look at new migration guide if still struggling: https://mobx-react.js.org/recipes-migration

**Comment by FredyC** [comment]
@ajbarber Well, it is already merged with lite and released as `6.0.0-rc.4`, although a bit outdated as it doesn't re-export new hooks. Hopefully, @mweststrate can get to it soon.

May I ask what are you expecting from such release? The only migration you will have to do will be to replace import from `mobx-react-lite` to `mobx-react`, so it's operation for like a minute :)

**Comment by ajbarber** [comment]
I am expecting what is in mobx-react-lite, nothing more, but I read on the mobx issues mobx-react 6 · Issue #640 · mobxjs/mobx-react that the final api is still not certain. This made me want to wait :)


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
mobx-react 6 · Issue #640 · mobxjs/mobx-react

Things to be addressed: switch to modern context (but keep same Provider / inject api) (#448) plan strategy for ...
 |

 |

 |




    On Tuesday, 28 May 2019, 4:25:10 pm GMT+8, Daniel K. <notifications@github.com> wrote:  
 
 
@ajbarber Well, it is already merged with lite and released as 6.0.0-rc.4, although a bit outdated as it doesn't re-export new hooks. Hopefully, @mweststrate can get to it soon.

May I ask what are you expecting from such release? The only migration you will have to do will be to replace import from mobx-react-lite to mobx-react, so it's operation for like a minute :)
