### ISSUE TITLE
Context in my react-app does not update after updating mobx store. 

### ISSUE THREAD

**Issue by OlIvAl** [mobxjs/mobx-react-lite#128]
I am strugling a bit with mobx-react-lite and react hooks.

I developed a little app https://codesandbox.io/s/1vrqj840q

I tried to make it as instructed (https://github.com/mobxjs/mobx-react-lite#what-about-smartdumb-components) 

But changing the 'loading' field value does not entail a change in the context and component update.

Unfortunately, there is not full example with context in the tutorial.

I can not understand, why!

Thanks for answers

**Comment by FredyC** [comment]
I am sorry for that misleading example with selectors. I've never actually tested it. I will remove it.

I've fixed the app for you: https://codesandbox.io/s/vy9p0k8265

Note: I highly recommend using [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree) to build your stores. The way you have chosen might turn out to be rather annoying for you in overall.

PS: It's kinda funny you have so many unnecessary types all around, but then IRootStore is just `any` :D

**Comment by OlIvAl** [comment]
@FredyC Thanks a lot!
So you don't recommend to use  react-selector-hooks.
Ok.
It will be great to fix readme file.

**Comment by FredyC** [comment]
It's not that I don't recommend it, but it needs some elaborating on how it should work actually.

For now, I've removed the whole section. It might appear in some form on the new docs site: #115
