### ISSUE TITLE
Suggestion: Add auto binding for methods in useObservable

### ISSUE THREAD

**Issue by Dudeonyx** [mobxjs/mobx-react-lite#133]
I recently decided to try mobx and frankly it has been a breathe of fresh air compared to redux.

One common gotcha though is `this` bindings, it's not an issue when creating classes in react thanks to CRA supporting `class properties` babel transform out of the box.

But when using `useObservable` with an object with methods there is no way to bind `this` automatically, so destructuring it would cause all your methods to fail.

so my suggestion is to add a flag that can enable autobindings something like

```ts
function useObservable<T extends SupportedValues>(initialValue: T, autoBind: boolean = false ):T {
        var observableRef = react.useRef(null);
        if (!observableRef.current) {
           if (autoBind) {
                // loop through `initialValue`
               Object.keys(initialValue).forEach(key =>{
                   const val = initialValue[key];
                   if (typeof val === 'function') {
                       // bind all methods
                       initialValue[key] = val.bind(initialValue);
                   }
               })
           }
            observableRef.current = mobx.observable(initialValue);
        }
        return observableRef.current;
    }
```

Since the flag is disabled by default there is no immediate change to existing behavior.

What do you guys think?

**Comment by FredyC** [comment]
Uhh, I don't follow, functional components don't have this :) If you are using one of those awkward projects that allow using hooks in classes then I am sorry, but we are not going to support that. Feel free to use `observer` or `<Observer />` instead.

**Comment by joenoon** [comment]
@Dudeonyx If I follow I think what your getting at can be solved by using the second argument of observable.  Something like:

```
          import {observable, action} from 'mobx'

          const [obs] = useState(() =>
                observable(
                    {
                        x: 1,
                        y: 2,
                        inc() {
                            this.x += 1
                        }
                    },
                    {
                        inc: action.bound
                    }
                )
            )
```

Getters (computeds) don't need this.

**Comment by FredyC** [comment]
Ah ... Or you can just do this and forget about this :)

```
          const [obs] = useState(() =>
                observable(
                    {
                        x: 1,
                        y: 2,
                        inc() {
                            obs.x += 1 // using closure variable directly
                        }
                    },
                )
            )
```

**Comment by Dudeonyx** [comment]
> Ah ... Or you can just do this and forget about this :)
> 
> ```
>           const [obs] = useState(() =>
>                 observable(
>                     {
>                         x: 1,
>                         y: 2,
>                         inc() {
>                             obs.x += 1 // using closure variable directly
>                         }
>                     },
>                 )
>             )
> ```

@FredyC Yeah, this is the workaround I'm currently using, but it's annoying when I want to immediately destructure the return ala

```js
const [{ x, y, inc }] = useState(() =>
                observable(
                    {
                        x: 1,
                        y: 2,
                        inc() {
                            obs.x += 1 // using closure variable directly
                        }
                    },
                )
            )
```

**Comment by FredyC** [comment]
Be warned, destructuring observables is generally bad idea :)

**Comment by joenoon** [comment]
Agreed, I can't see that ending well :)  Good luck

**Comment by Dudeonyx** [comment]
Yeah, besides turns out that my suggestion wouldn't work anyway because the bound `this` would be the non-observable object.

**Comment by mweststrate** [comment]
In the upcoming version, `useObservable` might very well actually automatically bind methods: https://github.com/mobxjs/mobx-react-lite/pull/130/files#diff-b343012e846f6092e6d077b011b393f4R12

**Comment by FredyC** [comment]
@mweststrate That's nice and all, but fails in TypeScript because `this` is just `any`. So I would rather opt for that closure variable that works.

**Comment by mweststrate** [comment]
No, `this` should be correct ootb if you use function member syntax `x() {
return this.bla }`.

**Comment by FredyC** [comment]
> No, `this` should be correct ootb if you use function member syntax `x() { return this.bla }`.

Made a new issue, it does not belong in here for sure. https://github.com/mobxjs/mobx/issues/1954

But it's definitely something that should be addressed before recommending the `useLocalStore`, imo.

**Comment by FredyC** [comment]
@Dudeonyx Just for your information, version 1.3.0 includes `useLocalStore` which has its actions auto bound to store instance, so `this` should be working just fine.
