### ISSUE TITLE
Unable to directly see hooks in React devtools for components wrapped in `observer` HOC

### ISSUE THREAD

**Issue by Dudeonyx** [mobxjs/mobx-react-lite#134]
Due to the way the `observer` HOC works, i.e wrapped components are called directly as functions and not with `React.createElement`.
![image](https://user-images.githubusercontent.com/23441172/56742888-7a274180-676d-11e9-9645-24e22a4ec5c0.png)

The hooks in the wrapped component do not show up in the React dev tools, at least not directly, they can be found nested deeply here

![image](https://user-images.githubusercontent.com/23441172/56742626-05540780-676d-11e9-9e92-81d598904f78.png)

under `Observer` > `.track` > `trackDerivedFunction$$1:` > ` :` > `:` > `ComponentName` it's difficult to find and you can't interact with the values at all.

Unfortunately switching `Observer` to call `useObserver` with `React.createElement` didn't work so well for me, so I don't know if this is fixable or just something we'll have to live with;

**Comment by FredyC** [comment]
That's an interesting observation. Would you be willing to try out if using `createElement` fixes the problem?

**Comment by Dudeonyx** [comment]
@FredyC when using createElement, updates are not triggered for changed observables

**Comment by FredyC** [comment]
Ah, I see, makes sense. Well, that's a bummer.

@mweststrate some ideas?

**Comment by Dudeonyx** [comment]
I was able to gut the internals of `mobx-react` and copy pasting the `makeComponentReactive` util then replacing the `useObserver` call in the `observer` Hoc with an adapted version (basically removed anything that had `this` in it and bound the `baseComponent` to props).

For some reason it works?

**I have no idea why it works.** This isn't me being humble, I literally have no idea why it works, not a single clue.

Hooks show up in the dev tools, and no nesting.

God knows what awful things are happening in the background tho.

**Comment by Dudeonyx** [comment]
Ok after calming down and remembering that I'm not an idiot. I was able to narrow the cause and create a version of `useObserver` that can be used by the `observer` Hoc

```ts
export function useObserver$<P>(
  fn: React.FC<P>,
  props: P,
  ref: React.Ref<any>,
  baseComponentName: string,
  options: IUseObserverOptions = EMPTY_OBJECT,
): any {
  const boundFn = useMemo(() => fn.bind(null, props, ref), [fn, props, ref]);
  if (isUsingStaticRendering()) {
    return boundFn();
  }
  const wantedForceUpdateHook = options.useForceUpdate || useForceUpdate;
  const forceUpdate = wantedForceUpdateHook();
  const reaction = useRef<Reaction | null>(null);
  const committed = useRef(false);

  if (!reaction.current) {
    // First render for this component. Not yet committed.
    reaction.current = new Reaction(`observer(${baseComponentName})`, () => {
      // Observable has changed. Only force an update if we've definitely
      // been committed.
      if (committed.current) {
        forceUpdate();
      }
    });
  }

  useDebugValue(reaction, printDebugValue);

  useEffect(() => {
    committed.current = true;
    return () => {
      reaction.current && reaction.current!.dispose();
    };
  }, []);

  let exception = undefined;
  let rendering = undefined;
  reaction.current!.track(() => {
    try {
      rendering = _allowStateChanges(false, boundFn as any);
    } catch (e) {
      exception = e;
    }
  });
  if (exception) {
    reaction.current.dispose()
    throw exception;
  }
```

Essentially the important part is that the baseComponent is somehow rendered by ` _allowStateChanges(false, boundFn as any)` and the observables are properly tracked.

**Comment by Dudeonyx** [comment]
![image](https://user-images.githubusercontent.com/23441172/56767792-909cbf80-67a4-11e9-9d97-38fd252bdd1d.png)

Hooks show up in dev tools

**Comment by Dudeonyx** [comment]
`observer` wraps this alternate hook like so
![image](https://user-images.githubusercontent.com/23441172/56767953-e5403a80-67a4-11e9-9af7-4646a4e2de77.png)

Should I make a PR so you(@FredyC ) and @mweststrate can point out all the things I did wrong.

**Comment by Dudeonyx** [comment]
my bad, like I suspected what i did didn't actually work. What showed up in the devtools was a forceUpdate hook I added to wrappedComponent

**Comment by FredyC** [comment]
Well, so I have spent some time to figure out a better way, but unfortunately, React Devtools is a kinda black box and doesn't allow to improve that in any way. There is an obvious problem that rendering happens inside the reaction track which is essential to make a whole thing work. I don't think React will ever provide any means to solve this because it's a fairly specific case.
