### ISSUE TITLE
Deprecated useObservable is used in the first example in README.md

### ISSUE THREAD

**Issue by shamrin** [mobxjs/mobx-react-lite#136]
It's confusing that useObservable is in the very first example in README.md. And then it's mentioned that useObservable is deprecated. Could you please fix the examples so they don't use deprecated API?

**Comment by FredyC** [comment]
I would accept PR :) I am not available till the end of the week.

**Comment by shamrin** [comment]
Thank you @FredyC! Unfortunately, I'm very new to mobx-react-lite. What do I use instead of `useObservable`?

**Comment by FredyC** [comment]
If you like, please check out the discussion leading to a deprecating: #94

**Comment by mweststrate** [comment]
See #140

**Comment by Ciantic** [comment]
I'm here to say that I'm trying to figure out how to replace my useObservable calls. But the documentation is truly confusing. I think merging that change of docs would be most helpful for everybody.

**Comment by ricardobeat** [comment]
Concur with @Ciantic above. I'm looking for a new solution for managing state in a fully hooks-based project; after reading through #94, #130, #140, other issues, mobxjs/mobx-react#640 I still have little clue on the current state of things.

- All four initial examples in the README contain `useObservable()`
- The last item in the README shows how to use `React.Context` but doesn't tell us what `createStore()` is
- In mobxjs/mobx-react#640 you'll find this comment:

> V6 does not really bring any new essential features on the table. It's pretty much a starting point where class and functional (with hooks) components are supported in a single package. It uses mobx-react-lite underneath

but no mention of hooks at all in the main package docs (it points back here instead)
- The [last example in this post](https://dev.to/ryands17/using-mobx-with-react-hooks-52h5) is a bit more clear but uses a mix of `mobx` and `mobx-react-lite` which I'm now unsure is the right approach

Could somebody who's been following development explain, or maybe point to an updated canonical example? Should we just hold off on MobX + hooks for the meantime?

**Comment by FredyC** [comment]
I understand it's not ideal, but we are simply lacking time to finish up #140. Just read through that for now, please. 

https://github.com/mobxjs/mobx-react-lite/blob/readme-improvements/README.md

> All four initial examples in the README contain useObservable()

The `useObservable` is clearly marked as deprecated there.

> The last item in the README shows how to use React.Context but doesn't tell us what createStore() is

That's out of scope and up to you how you construct your store, eg. class+decorators or mobx-state-tree

> * The [last example in this post](https://dev.to/ryands17/using-mobx-with-react-hooks-52h5) is a bit more clear but uses a mix of `mobx` and `mobx-react-lite` which I'm now unsure is the right approach

That's fairly normal to use `mobx` and `mobx-react-lite` alongside, especially when you need eg. `reaction` or `autorun`.

**Comment by ThomasRoest** [comment]
I'm trying to figure out the same things. @ricardobeat I'm experimenting with some patterns here: 
Right now it's a combination of the class based store approach and using context to access it
https://codesandbox.io/s/pmnoqzoyzj

**Comment by FredyC** [comment]
Have a look at a new docs site, it will be official soon.

https://mobx-react.js.org

**Comment by FredyC** [comment]
#156 merged, closing this
