### ISSUE TITLE
Going from mobx-react -> mobx-react-lite

### ISSUE THREAD

**Issue by johnnyreilly** [mobxjs/mobx-react-lite#138]
Heya!

A while ago I took mobx-react-lite for a spin.  The problem I bumped was how I should migrate the following pattern to mobx-react-lite:

```
interface IInjectedProps {
    login: () => void;
    isAuthenticated: boolean;
}

type IProps = RouteComponentProps & Partial<IInjectedProps>;

export const HomePageRaw: React.FC<IProps> = props => {
        const { login, isAuthenticated  } = props;

        return (
            <div>html be here</div>
        );
    }

export const HomePage = inject(
    (dependencies: Dependencies): IInjectedProps => ({
        login: dependencies.authStore.login,
        isAuthenticated: dependencies.authStore.isAuthenticated
    })
)(observer(HomePageRaw));
```

I tried about 5 or so permutations based on the docs but things generally either didn't work or didn't work as expected (perpetual re-renders etc)

Given that this is a fairly common pattern, I wonder if it would be possible to request that an example be added to the docs illustrating how you would go from this to a mobx-react-lite friendly alternative.

From what I understand `inject` is dead in a ditch, instead reach for `useContext` - that's cool.  But how should the rest of the component be structured?  I'd be happy to send a docs PR if I understood how things could / should be structured. 

If someone could advise I'd be super grateful.

Thanks for all the work you're doing BTW.  It's 💯 😄

**Comment by FredyC** [comment]
Um, can you perhaps show at least one pattern you have tried and failed with it? I cannot imagine where what's the catch really :)

**Comment by joenoon** [comment]
FWIW, this example from the tests (with a couple changes to make sure eslint is happy) probably covers 98+% of the use cases.  I've yet to switch over to the new useLocalStore/useAsObservableSource hotness, but trust the tests.  Essentially, every component with observable data should look something like this:

```tsx
import { observer, useAsObservableSource, useLocalStore } from "mobx-react-lite"

interface CounterProps {
  multiplier: number;
}

export const Counter = observer(function Counter(props: CounterProps) {
    const observableProps = useAsObservableSource(props)
    const store = useLocalStore(() => ({
        count: 10,
        get multiplied() {
            return observableProps.multiplier * this.count
        },
        inc() {
            this.count += 1
        }
    }))

    return (
        <div>
            Multiplied count: <span>{store.multiplied}</span>
            <button id="inc" onClick={store.inc}>
                Increment
            </button>
        </div>
    )
})
```

So it's really very simple, and even in that example there are a lot of things you don't need all the time: useAsObservableSource, computed getter, action.  The biggest challenge is probably unlearning all of the old typescript hackery/noise and realizing its no longer necessary.

**Comment by johnnyreilly** [comment]
Thanks @joenoon - I'll try to make use of that. 

> The biggest challenge is probably unlearning all of the old typescript hackery/noise and realizing its no longer necessary.

This is great news! Less code is better code!

**Comment by FredyC** [comment]
> More generally I raised this issue as I feel the documentation is missing the kind of guidance that shows you an end to end of how mobx-react-lite can be used.

Totally agree, that's why I started #115, but I am failing to find some time to at least start working on it.

**Comment by mweststrate** [comment]
Added an introduction overview in #140

**Comment by FredyC** [comment]
@johnnyreilly New recipe just landed in docs that might interest you. Further questions direct into source repo there, please.

https://mobx-react.netlify.com/recipes-inject

**Comment by FredyC** [comment]
Since people were still asking about migration, I've prepared a specific document focused on such topic.

https://mobx-react.netlify.com/recipes-migration

Feedback welcome as it's kinda harder for me to think in those old patterns.

**Comment by mweststrate** [comment]
Sorry for my absence lately :). I'll hope to soon return to
mobx-react-(lite) stuff now that the first mst-gql version is out :)

**Comment by johnnyreilly** [comment]
> Feedback welcome as it's kinda harder for me to think in those old patterns.

Awesome - I'm away camping right now. But I'll try to take a look on my return

**Comment by FredyC** [comment]
@johnnyreilly Did you have a chance to look at the migration guide?

Closing this for now, but feedback is still appreciated.
