### ISSUE TITLE
can't use mobx-react & mobx-react-lite together on codepen/jsfiddle/etc

### ISSUE THREAD

**Issue by kfedorov91** [mobxjs/mobx-react-lite#148]
the docs say
> you can use this package alongside the mobx-react just fine.

however I tried to do just that inside of a codepen and couldn't.

both https://unpkg.com/mobx-react & https://unpkg.com/mobx-react-lite return functions that try to register the module in the global namespace as `window.mobxReact` so whichever script gets run later overwrites the former.

I wanna use both libs in the same codepen because I'd like to implement a React component using both and then compare those implementations side-by-side.

Please consider making mobx-react-lite register itself in the global namespace as `window.mobxReactLite` instead. Thank you.

**Comment by FredyC** [comment]
Yes, you are right. I am wondering, does CodePen has some advantage over the [CodeSandbox](https://codesandbox.io) which allows you to use modules from NPM directly so you don't need to worry about UMD?

I will change the namespace either way.

**Comment by kfedorov91** [comment]
> I am wondering, does CodePen has some advantage over the CodeSandbox which allows you to use modules from NPM directly so you don't need to worry about UMD?

I personally find CodeSandbox to be very slow, memory-hungry, and hard to work with. Whenever I'd like to quickly try out a new lib or framework I always start with CodePen or JSFiddle, and if I need something that those tools don't provide out-of-the-box then I move to local dev on my machine and use VSCode + Webpack dev server. CodeSandbox is a last resort for me, and I'd only use it if I need an easily shareable link to a multi-file project.

**Comment by FredyC** [comment]
Fix released in 1.3.2, thanks @kfedorov91
