### ISSUE TITLE
mobx-react-lite ignores fast updates

### ISSUE THREAD

**Issue by jantimon** [mobxjs/mobx-react-lite#152]
**This bug is already fixed with 1.3.1** This issue is only for reference.  

Updating an observable inside a computed function (which shouldn't be done in most cases anyway) it does not trigger a reaction.

Code https://codesandbox.io/s/pmw3kqxkx0
```js
class DemoStore {
  get name() {
    if (this.usedComputedValue) {
      return "🙋‍♀️";
    } else {
      setTimeout(() => {
        this.usedComputedValue = true;
      });
    }
    return "🤷‍♀️";
  }
}
decorate(DemoStore, {
  usedComputedValue: observable,
  name: computed
});
```

Using the computed `name` property should result in `🙋‍♀️` after the timeout is done.  
Unfortunately that did not work before `1.3.1`

**Comment by FredyC** [comment]
I am sure it worked with 1.2.0 though :) There was a short period where 1.3.0 was released with a bug. Thanks for making an effort, but I don't think it's necessary to keep it open.

**Comment by jantimon** [comment]
Thanks for your additional input 👍
