### ISSUE TITLE
Allow passing custom arePropsEqual to observer

### ISSUE THREAD

**Issue by olee** [mobxjs/mobx-react-lite#154]
It would be nice to allow passing a custom arePropsEqual function to observer for it's internal call to `React.memo` here:
https://github.com/mobxjs/mobx-react-lite/blob/6ea7bf1ec5c8738743a795b6178f18e756811627/src/observer.ts#L50-L52

I just found out, that I can actually wrap the returned memo component **again** with `React.memo`, but this introduces a new wrapper level again and feels kinda akward:
```typescript
const ListViewItem = React.memo(observer(function ListViewItem(props: any) {
    return (
        // ...
    );
}), arePropsEqualWithStyle);
```

So instead of the above you could then just do
```typescript
const ListViewItem = observer(function ListViewItem(props: any) {
    return (
        // ...
    );
}, { arePropsEqual: arePropsEqualWithStyle });
```

**Comment by FredyC** [comment]
I suppose it makes sense, although I had never need to specify that for React.memo. The general idea of observable components is that you are not re-rendering them based on props, but more likely with changes to observables. It might be worth to rethink the approach and perhaps split that component into a smaller one if you really need both of those worlds.

**Comment by FredyC** [comment]
@olee I assume you have figured out the way without addition of that option? I will close this for now since nobody else seems to be interested in such a feature. Let me know if you want to work on the PR in case it's still relevant.
