### ISSUE TITLE
Request for more documentation about migration with React new context API

### ISSUE THREAD

**Issue by AoDev** [mobxjs/mobx-react-lite#155]
With mobx-react-lite, there is no more provider / inject. 
For those who haven't migrated to the new context API, I'd like to have a better example on how to migrate the typical app "boot" that have similar code like this:

```js
// app bootstrap
import * as mobx from 'mobx'
import App from './App'
import RootStore from './stores/RootStore'
import {Provider} from 'mobx-react'
import {AppContainer} from 'react-hot-loader'

const rootStore = new RootStore()

// AppContainer is a necessary wrapper component for HMR
const render = (Component) => {
  reactDom.render(
    <AppContainer>
      <Provider rootStore={rootStore}>
        <Component />
      </Provider>
    </AppContainer>,
    document.getElementById('root')
  )
}

render(App)

// Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./App', () => {
    render(App)
  })
}
```

Then consuming the store somewhere:

```js
import {observer, inject} from 'mobx-react'
import PropTypes from 'prop-types'
import React from 'react'

export function App (props) {
  const {rootStore} = props
  return (
      <div>
        My App
      </div>
  )
}

export default inject('rootStore')(observer(App))
```

The new context API is still unknown to me, I think it would help to have a more detailed change from such code.

**Comment by AoDev** [comment]
Hi Sorry, I pressed enter by mistake and github just published this without any way to rollback. I'll complete it.

**Comment by FredyC** [comment]
Please follow #115

**Comment by AoDev** [comment]
@FredyC I had a concrete question, please look at the updated description. As I mentioned, is that I pressed enter by mistake and this created an empty issue.

**Comment by FredyC** [comment]
@AoDev Just use Provider/inject from `mobx-react` if you are not comfortable with Context. More docs will be coming, but it will take time (weeks, month, ...)

**Comment by FredyC** [comment]
@AoDev I just published migration guide, after all, feedback appreciated.

https://mobx-react.js.org/recipes-migration

**Comment by AoDev** [comment]
@FredyC Hi, thanks for your work. At first glance, I'd say the guide should be clearer about `from "what thing" to "what other thing" we are migrating`. There might be other migrations guides in the future. It isn't clear if the actual goal is to move out of classes or embrace the React hooks, or use the oficial context API, or is this a guide about from mobx-react to mobx-react-lite? Sometimes it feels like "the means and the end are inverted".
