### ISSUE TITLE
observer is double-edged sword

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#161]
Recently I kinda grew fond of using `observer`, because ... just reasons. However, the built-in `React.memo` caught me off guard. 

We have an app localized with LinguiJS. There is a Provider sitting on top and when the language is switched, it re-renders the whole app with a different translation. The `React.memo` stops the update because props haven't changed (only value in context).

The story is pretty much the same to `react-router` and others using the same technique. We cannot really expect that every lib would be written with MobX (wouldn't that be great?).

While the `observer` works in most cases, it can cause harm as well. How should we recommend what to choose if there are such strange gotchas in each of those patterns? 😕

**Comment by urugator** [comment]
LinguiJS uses legacy context.

https://reactjs.org/docs/legacy-context.html#updating-context
> The problem is, if a context value provided by component changes, descendants that use that value won’t update if an intermediate parent returns false from shouldComponentUpdate. This is totally out of control of the components using context, so there’s basically no way to reliably update the context.

However there seems to be some `publisher` to which you can subscribe for changes?:
https://github.com/lingui/js-lingui/blob/master/packages/react/src/I18nProvider.js#L48

**Comment by FredyC** [comment]
Doh! I know there is a V3 rewrite with new Context, but it's not stable so I am sticking to V2 which indeed has the legacy context. It's ok for now, it wasn't affecting too many components so I've refactored to `useObserver` which is the easiest solution.

Not sure how the publisher works and I don't think I want to know :) It's not a public API.

Thanks for reminding me of this. I need to cover this on docs site for sure, it's a nasty gotcha.

**Comment by FredyC** [comment]
Warning added to docs: https://mobx-react.js.org/observer-hoc
