### ISSUE TITLE
Pure Javascript examples?

### ISSUE THREAD

**Issue by bluepeter** [mobxjs/mobx-react-lite#166]
For those of us who haven't gone full TypeScript, how about some JavaScript examples in the README?

**Comment by bluepeter** [comment]
And user guide, particularly, https://mobx-react.js.org

**Comment by FredyC** [comment]
@bluepeter Can you elaborate what examples, in particular, seems so hard to understand because of some extra syntax? TypeScript is 100% compatible with JavaScript, it just adds type there.

**Comment by bluepeter** [comment]
@FredyC honestly, it just adds another barrier to easy adoption for those of us who aren't expert programmers and small things like that add confusion and complexity. To the extent that all TypeScripters know Javascript, but not all Javascripters know/are familiar with TS, perhaps offering the samples in the more common language would be suitable. No big whoop if not. Just my 2 cents.

**Comment by FredyC** [comment]
There is kinda a hoping that when people see TypeScript there, they will start to like it :) I am a big TypeScript enthusiast and would love to see more people jumping on board for sure.

That site is still kinda infant technologically speaking. I suppose I would be willing to show pure JS examples there only if it's possible to automate it somehow. Doing that manually would be maintenance hell. If someone can help out with that, it would be great, but it's not major focus right now.

**Comment by bluepeter** [comment]
Got it. I'd love a really clear and comprehensive example of `inject`ing stores, because I haven't yet found one, in either JS or TS (even after going through issues and docs closely), that doesn't hand-wave a lot of stuff that I'm not familiar with. As it is, I have this ugliness in my code...

```
import { inject } from "mobx-react";                                                                                 
import { observer } from "mobx-react-lite";        

const Component = inject("commonStore")(                                                                             
  observer(({ commonStore }) => {  
  ...
  }));                   
```

**Comment by FredyC** [comment]
Have you seen the latest migration guide? https://mobx-react.js.org/recipes-migration

**Comment by bluepeter** [comment]
I did... and thanks for that. It still isn't totally clear to me. One note from that doc:

> In fact, the mobx-react@6 will include similar utility build on top of new Context to ease on transition

I've sorta been assuming that waiting for `mobx-react@6` is the "right answer?" (Still not clear on if mobx-react-lite is just a stand-in until 6 is available, or it's going to continue on (for some reason?))

**Comment by FredyC** [comment]
Doesn't https://mobx-react.js.org/libraries makes it more clear to you? Thank you for the feedback, but it needs to be slightly more constructive so I know how to improve it.

`mobx-react@6` was released just today (need to update docs regarding that) so you can pretty much keep using that as it includes `mobx-react-lite` internally.

**Comment by bluepeter** [comment]
Thanks @FredyC ... can you point me to new docs for MobX 6? I've taken a look around but can't seem to dig 'em up yet...

**Comment by FredyC** [comment]
What new docs? :) Most likely the same docs site will be used for it as well.

Note, however, that `mobx-react@6` is not really a breaking change except it depends on React 16.8+. The API is the same (and extended by mobx-react-lite).

**Comment by bluepeter** [comment]
Can I `import { observer } from "mobx-react"; ` and use `observer` in a classless functional component?

**Comment by FredyC** [comment]
Yes, of course :) That's the intention of v6 to cross the gap. In some distant future, the class support might be dropped and these two packages will effectively become the one.

**Comment by bluepeter** [comment]
Ah, okay, super.

I will close this issue as it has gotten far away from it's original purpose.

**Comment by bluepeter** [comment]
Btw, one quick additional question while I have you here @FredyC ... is there a best practice in terms of MobX stores and `useEffect` hooks? I have code like this...

```
const Component = inject(
  "siteStore",
  "getStore",
  "refreshStore"
)(
  observer(props => {
    useEffect(() => {
      props.refreshStore.setLoader(loader);
      return function cleanUp() {
        props.getStore.clearAll();
        props.siteStore.clearBoss();
      };
    }, []);
```

React complains with `React Hook useEffect has a missing dependency`... I don't want to pass in an entire store as a dependency, but I can't dereference the functions (e.g., `clearBoss`) and pass just those in as dependencies without weird side-effects of `this` in the target store.

Any best practices or approaches here?

**Comment by FredyC** [comment]
You should really read through the whole docs site, there is a dedicated recipe even for that. No link this time, show some effort ;)

**Comment by FredyC** [comment]
And btw, it's not React what complains, it's that crappy ESLint plugin, that's half baked and does false positives all the time. I've ditched it until it's more polished.

**Comment by bluepeter** [comment]
So, use `autoRun` it looks like https://mobx-react.js.org/recipes-effects

**Comment by bluepeter** [comment]
Doesn't look as though it's easily possible to get rid of eslint on create-react-app w/o ejecting :( facebook/create-react-app#2157
