### ISSUE TITLE
Importing store directly vs importing context

### ISSUE THREAD

**Issue by Gameghostify** [mobxjs/mobx-react-lite#17]
I feel like this needs a little clarification, I can't wrap my head around it to say the least.

With the old `Provider`/`inject` gone and us being able to use `useContext`, whats the difference between exporting/importing the store directly and exporting/importing the context directly?

For example:
```js
// Store.js
class ChatStore {
  messages = [];
}

export default new ChatStore();

// Component.js
import ChatStore from "Store.js";

function MyComponent(props) {
  // can directly access and use ChatStore in here
}
```

and

```js
// Store.js
class ChatStore {
  messages = [];
}

export default React.createContext(new ChatStore());

// Component.js
import ChatStoreContext from "Store.js";

function MyComponent(props) {
  const store = React.useContext(ChatStoreContext);
  // extra step needed to access store, with seemingly no benefit
}
```
(examples obviously simplified and missing code necessary to run)

The only difference between these two would be the *extra step* needed to use the store in the second example.

So, what does using React's `Context` actually do for us here?

**Comment by FredyC** [comment]
In this simplified scenario, it doesn't really matter that and you can certainly do with export. In more advanced scenarios your store might actually depend on something else, you might want to have some sort of persistence setup and in that case, it's pretty much necessary to use the Provider.

Also, the major reason why not to use global state is probably for automated testing. You would need the ability to reset it between each test to ensure isolated tests. With context in place, you can easily drop Provider in the tree and supply fresh new instance for each test.
