### ISSUE TITLE
Make clear the differences between observer HOC and useObserver

### ISSUE THREAD

**Issue by asfernandes** [mobxjs/mobx-react-lite#171]
Documentation shows usage of `observer` HOC and `useObserver` when returning JSX.

It's not clear for me the difference, if it ever exist.

**Comment by FredyC** [comment]
Have you see this page in particular? https://mobx-react.js.org/observe-how

Doesn't that tell you, that differences are pretty small and it's up to you which one you like? :)

**Comment by asfernandes** [comment]
> "In most cases, there difference doesn't matter that much, but here is an overview of the three different approaches"

It definitely don't explain if that diffetences are cosmetic or functional.

**Comment by FredyC** [comment]
Well, you can read on actual differences on separate pages for one of them. PR welcome if you have an idea on how to improve that.

**Comment by asfernandes** [comment]
Ok, now I read about the `React.memo`.
