### ISSUE TITLE
Can't get basic example to work using useLocalStore/useContext

### ISSUE THREAD

**Issue by gstipi** [mobxjs/mobx-react-lite#174]
In the example below (two counters with shared state created using `useLocalStore` and retrieved via `useContext`), the label on the buttons ` {store.count}` is never updated. Why is that the case? Any help would be very much appreciated as I really like how clean the code is, but I would obviously like it even better if it worked!

`inc()` is called and the count in the store updated, as evidenced by logging `inc` calls to the console.

CodeSandbox: https://codesandbox.io/s/nice-heyrovsky-bfh7f

Dependencies:
```
"dependencies": {
    "mobx": "5.10.1",
    "mobx-react-lite": "1.4.0",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-scripts": "3.0.1"
  },
  "devDependencies": {
    "typescript": "3.3.3"
  },
```
Typescript implementation:

```
import React, { ReactNode } from "react";
import ReactDOM from "react-dom";
import { useLocalStore, useObserver } from "mobx-react-lite";

function createStore() {
  const store = {
    count: 0,
    inc() {
      store.count += 1;
      console.log(store.count);
    }
  };
  return store;
}

type Store = ReturnType<typeof createStore>;

const StoreContext = React.createContext<Store | null>(null);

export const StoreProvider = (props: { children?: ReactNode }) => {
  const store = useLocalStore(createStore);
  return (
    <StoreContext.Provider value={store}>
      {props.children}
    </StoreContext.Provider>
  );
};

export const useStore = () => {
  const store = React.useContext(StoreContext);
  if (!store) {
    throw new Error("useStore: !store, did you forget StoreProvider?");
  }
  return store;
};

const Counter = () => {
  const store = useStore();
  return useObserver(() => (
    <div>
      <button onClick={store.inc}>Clicked {store.count} times</button>
    </div>
  ));
};

const App = () => {
  return (
    <StoreProvider>
      <Counter />
      <Counter />
    </StoreProvider>
  );
};

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by mweststrate** [comment]
The problem is the combination of observables and `this`. Your `createStore()` doesn't produce an observable, so `useLocalStore` will make it observable by itself (by making an observable copy). However, since the `inc()` method operates on `store` and not `this`, it will increment the non-observable version of the store. 

You could fix this by either doing `this.count += 1` in `inc`, or using `const store = observable({ ... })`. (I recommend the first approach).

**Comment by mweststrate** [comment]
@FredyC I think this is quite a common trap, and I think we could fix it by changing https://github.com/mobxjs/mobx-react-lite/blob/b0646c1ce1bd1215b63b3f9beb33a2b104facaad/src/useLocalStore.ts#L14 to 

```javascript
let local = initializer(source as TSource)
if (isPlainObject(local))
   extendObservable(local, local)
else local = observable(local)
```

To make the object observable in-place.

**Comment by gstipi** [comment]
@mweststrate Many thanks for your help! I guess I still need to wrap my head around the subtleties of Javascript's `this`.

Does this mean that the `createStore` function in the first code sample in https://mobx-react.js.org/recipes-context suffers from the same problem? I think this is what originally led to my mistake, as `friends` is accessed as `store.friends` there and the comment says:
```
// storing variable in closure means you can access it in methods
// otherwise you would have to use `this` which doesn't work well with TypeScript
```

**Comment by FredyC** [comment]
@gstipi Apologies, that example is wrong and I wanted to fix it but forgot about it 😓

@mweststrate Isn't it too magical? But it's worth the try for sure.

**Comment by gstipi** [comment]
@FredyC no worries, I learned something new! 🙂

**Comment by FerrielMelarpis** [comment]
> You could fix this by either doing this.count += 1 in inc, or using const store = observable({ ... }). (I recommend the first approach).


@mweststrate The first approach conflicts w/ my tslint so I always do the 2nd approach. So far I haven't seen any issue w/ it but could you elaborate on why you prefer the use of `this` instead of using the assigned variable `store`?
```
TSLint: the "this" keyword is disallowed outside of a class body(no-invalid-this)
```

**Comment by mweststrate** [comment]
Sorry, I'm not gonna argue with lint rules :) observable wrapping is what the hook normally already does, and generally I don't like to make my implementation suboptimal to make a lint rule happy.

**Comment by FredyC** [comment]
@FerrielMelarpis I am with Michel. Linter is a tool that is supposed to help you. If it limits you in some way, then it's a bad tool. You might consider leaving TSLInt anyway, [it's deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9).

**Comment by FerrielMelarpis** [comment]
@FredyC Thanks for that. I've migrated my project to eslint. 
@mweststrate 
> observable wrapping is what the hook normally already does

Oh, gotcha. Thanks for the info. I agree that the first approach is optimal as well. I guess I was just wondering if there would be some unknown behavior I don't know of when using the second approach. Nevertheless, this is not an issue for me anymore 😄
