### ISSUE TITLE
Returning undefined inside <Observer> causes error

### ISSUE THREAD

**Issue by MehdiSaffar** [mobxjs/mobx-react-lite#175]
Doing this

`
<Observer>{() => undefined}</Observer>
`

Gives `Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`
While return undefined inside a regular React component does not give such error.

Why is that?

**Comment by FredyC** [comment]
That's React behavior, undefined is not a valid value to be rendered, you have to explicitly use `null`.
