### ISSUE TITLE
Object changes does not trigger re render

### ISSUE THREAD

**Issue by Englund0110** [mobxjs/mobx-react-lite#176]
I am trying to figure out, why updated objects is not triggering a re-render. 

Lets say i have a component, and i am parsing a object as a prop into that component, from a component that is hooked up with the store. When a property in that object is updated, it will not trigger a re-render in that component it is used. 

But if i take the properties from the object, and parse that as props to my component instead, it will work as expected. 

I have made a little project to clear out what i mean: https://codesandbox.io/embed/classic-mobx-stores-with-hooks-8qo4t

Am i missing something?

**Comment by FredyC** [comment]
You are missing observer around the component.

https://mobx-react.js.org/observe-why
