### ISSUE TITLE
IPromiseBasedObservable in StrictMode failes to render

### ISSUE THREAD

**Issue by JohnNilsson** [mobxjs/mobx-react-lite#180]
Somehow an `observer` wrapped in `React.StrictMode` fails to update the DOM when reacting to an `IPromiseBasedObservable`

Repro here: https://codesandbox.io/embed/throbbing-star-fonrw

**Comment by FredyC** [comment]
We have `mobx-react-lite@next` with support for StrictMode. It's still experimental (nobody tested it AFAIK), but it seems to solve your problem. Up to you if you want to give it a spin in a real app. That version is based on the 1.4.1.

**Comment by JohnNilsson** [comment]
Indeed, changing `next`does resolve the issue

**Comment by FredyC** [comment]
Awesome, I will close this issue now and feel free to open a new one if you run into some problems.

**Comment by bobinrinder** [comment]
It literally cost me hours to figure out that StrictMode was the issue.. 🙄 
Would be really nice to support that/release v2 since CRA defaults to StrictMode setup at the moment...
Or at least have note until v2 is released? I feel like a lot of other people will stumble over this...

**Comment by FredyC** [comment]
Where would you put that note to make it visible? Like a warning to library itself? I am not sure if StrictMode can be detected.

**Comment by bobinrinder** [comment]
I think a note in the ReadMe would be fair and little effort until v2 is released. You already have some warnings like `You need React version 16.8.0 and above`.

Maybe add something like:

If your app is wrapped in **React.StrictMode** (currently default with **Create-React-App**) consider using the `next` branch to avoid issues with missing renders in connection with `yield` in `flow` functions.

Or any similar wording of your choice... 😎 
When this first failed for me I suspected errors with my adaption of the hook-based approach and I went through all the docs available but couldn't find anything wrong. It was very time consuming and frustrating to find out that a default setup piece in CRA caused this and a note about it could have saved me (and therefore likely a lot of others) quite some time.
