### ISSUE TITLE
MAX_SAFE_INTEGER overflow

### ISSUE THREAD

**Issue by keenondrums** [mobxjs/mobx-react-lite#185]
[Currently `useForceUpdate` constantly increments the integer state](https://github.com/mobxjs/mobx-react-lite/blob/master/src/utils.ts#L13). If an app lives long enough it could become greater than MAX_SAFE_INTEGER. I'm just wondering wouldn't it be better just to return a brand new object each time?

```js
export function useForceUpdate() {
    const [, setTick] = useState({})

    const update = useCallback(() => {
        setTick(() => ({}))
    }, [])

    return update
}
```

**Comment by FredyC** [comment]
@keenondrums Is it an actual problem from experience? Hard to imagine reaching out that number considering each component has its own counter. Even if the component would be updated once per 1 millisecond, it would still take roughly 9520 **years** to reach that number. Anything faster doesn't sound like a real case besides animations and there are surely better ways to animate things than with MobX.

Either way, there are surely better ways than creating objects (and bothering garbage collector with it). In fact, we could easily be switching between true/false values or 0/1. As long as the value is different from the previous ones, it's fine.

So if you feel threatened by this, feel free to submit a PR to do something like that.

**Comment by keenondrums** [comment]
@FredyC no real-world use case. I was just browsing Github to see how other people implemented forceUpdate with hooks. I was just wondering why you made this choice, that's all.
Btw, it seems current implementation returns a new integer each time, so GC still has to do the same work as for objects :)

**Comment by FredyC** [comment]
Alright, I am not an expert, but seems like cleaning out a number could be slightly cheaper. Considering that number is not held by reference, thus no reference counting, it can be cleaned up right after it has been used. I cannot really confirm that though.

Either way, to feel safe we could simply add a check for MAX_SAFE_INTEGER and flip it back to 0 if that ever happens, but I don't see how it could become a problem during our lifetime :)

**Comment by Maaartinus** [comment]
I'd bet, there's nothing to clear with integers. Optimizing them is pretty substantial fir the performance.

> Either way, to feel safe we could simply add a check for MAX_SAFE_INTEGER

Something like `((t & 0xFFFFFFFF) + 1) & 0xFFFFFFFF` would surely be faster (it's all a single asm int arithmetic instruction), but...

> but I don't see how it could become a problem during our lifetime

exactly.

**Comment by mweststrate** [comment]
Objects hits the GC indeed, and numbers don't, as those are stored by value
in the component instance, and not on the heap.

The performance impact of any solutions with numbers is irrelevant,
probably in the order of a grain of sand on top of the Mount Everest cost
of re-rendering the component in the first place.

Rather than speculating if this is an issue or not, I suggest to first fire
up the browser debugger, set that number to MAX_SAFE_INTEGER - 3, and check
what happens after a few clicks :)

**Comment by FredyC** [comment]
Well, that made me curious ... did not expect such outcome for sure :D https://codesandbox.io/s/cool-https-rs0j4

**Comment by mweststrate** [comment]
So it does freeze indeed correct? I think that would be kind of expected
here indeed. Actual overflow to -MAX_SAFE_INTEGER would be better :-P.

**Comment by mweststrate** [comment]
Maybe we should just add that check, for our own piece of mind in case
somebody leaves a stock ticker open for two years :P

**Comment by FredyC** [comment]
Well, it did not freeze, it just stopped with re-rendering :) That's why I was surprised. Wonder if CodeSandbox has some sort of guards for that, possibly the reason for such behavior.

**Comment by mweststrate** [comment]
No, that actually make sense, because at certain point incrementing above safe is pointless:

```
> Number.MAX_SAFE_INTEGER + 12 === Number.MAX_SAFE_INTEGER + 13
true
```

**Comment by FredyC** [comment]
That's some hidden gem of JS engine it seems :) Well, let's not dwell in that, don't need to know everything.

> Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2
> true
> Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 3
> false

**Comment by mweststrate** [comment]
`(current ÷ max_safe) + 1` is the shortest solution probably

**Comment by keenondrums** [comment]
It's not going to freeze entirely. It's just going to start skipping updates. First every other one, then every other 3 ones and etc. Sorry if I took too much of your time guys with this issue. Was just curious :)

**Comment by Maaartinus** [comment]
> That's some hidden gem of JS engine it seems

@FredyC No, it's the [correct](https://en.wikipedia.org/wiki/IEEE_754-1985#Rounding_floating-point_numbers) behavior of `double` as standardized since 1985.

Pretty all CPUs and pretty all languages follow. The funny thing about JS is that it has nothing but `double`; no int32 and no int64. Luckily, `double` is big enough to cause hardly any problems.
