### ISSUE TITLE
custom forceUpdate on observer options

### ISSUE THREAD

**Issue by doxiaodong** [mobxjs/mobx-react-lite#187]
Just like it on useObserver.

https://github.com/mobxjs/mobx-react-lite/blob/151531855fd5b3832cf2370a86999a991a964300/src/useObserver.ts#L11

**Comment by FredyC** [comment]
Why?

**Comment by doxiaodong** [comment]
I want to do something else when react re-render,  but I use observer only.

**Comment by FredyC** [comment]
Sorry, that's not enough. Freel free to make your own `observer` that will utilize the `useObserver`.

**Comment by FredyC** [comment]
Besides, you can just `React.useEffect` (without any deps) when you want to do something after each render. That option was added there as low-level api for some edge cases, it's not intended as any sort of pattern to be widely used. Closing this (and your PR) unless you come up with really good reasoning.

**Comment by doxiaodong** [comment]
1. I don't want copy the whole observer file into my repo.
2. I only want watch the re-render cause by mobx state change

**Comment by FredyC** [comment]
Then use `reaction` to do something upon observable change. Still not seeing a reason why to even use custom forceUpdate.

**Comment by doxiaodong** [comment]
It's useful to count re-render times in components test. I can't add `reaction` in my test code.

**Comment by FredyC** [comment]
Sounds like you are just fishing reasons now :) In tests, you shouldn't count only MobX related renders.

Let's leave this discussion. If you are really convinced you need it, make your own `observer`. It's not that bad copy that code and you can leave out something you don't care about (eg. forwardRef, ssr). The biggest part is HOC handling and type declaration.
