### ISSUE TITLE
How to get the store outside the function component？

### ISSUE THREAD

**Issue by Chersquwn** [mobxjs/mobx-react-lite#193]
Because the rules of React Hooks, we should not call Hooks from regular JavaScript functions.

Is there any better way to get store in regular function?

**Comment by FredyC** [comment]
Wait, what? :) https://mobx-react.js.org/recipes-context

**Comment by Englund0110** [comment]
I think its a valid question. :-)

Lets say you want to use logic between stores, and want to call StoreA from StoreB. Or want to call StoreA, from a utility class.

**Comment by FredyC** [comment]
Wait, what? (again). Let's talk in examples folks, this is too vague...

**Comment by Chersquwn** [comment]
For example：
we want to call global Dialog component in AJAX interceptor, which managed by a store.

**Comment by FredyC** [comment]
By example, I mean an actual code 😆

**Comment by Chersquwn** [comment]
I do not know how to get the store outside of component, so where my code comes from?(😝)

```ts
// createStore.ts

export function createStore() {
  return {
    show: false,
    setShow(show: boolean) {
      this.show = show
    }
  }
}

export type TStore = ReturnType<typeof createStore>
```

```ts
// store.tsx

import React from 'react'
import { createStore, TStore } from './createStore'
import { useLocalStore } from 'mobx-react-lite'

const storeContext = React.createContext<TStore | null>(null)

export const StoreProvider = ({ children }) => {
  const store = useLocalStore(createStore)
  return <storeContext.Provider value={store}>{children}</storeContext.Provider>
}

export const useStore = () => {
  const store = React.useContext(storeContext)
  if (!store) {
    // this is especially useful in TypeScript so you don't need to be checking for null all the time
    throw new Error('You have forgot to use StoreProvider, shame on you.')
  }
  return store
}
```

```ts
// App.tsx

import React, { FC } from 'react'
import Dialog from 'react'
import Routes from './routes'
import { useStore } from './store'

const App: FC<{}> = () => {
  const { store } = useStore
  return (
    <div>
        {store.show && <Dialog />}
    </div>
  )
}

export default App
```

```ts
// request.ts

import axios from 'axios'

axios.interceptors.response.use(
  async response => {
    return response.data
  },
  error => {
    if (error.response && error.response.status) {
      // here to call Dialog
      // how to get the store?
      // store.setShow(true)
    } else {
      Promise.reject(error)
    }
  }
)
```

**Comment by FredyC** [comment]
Have you actually read https://mobx-react.js.org/recipes-context?

**Comment by austincollinpena** [comment]
As someone who's programming-challenged, I'd like to help any potential googlers out there who found this like I did.

What worked for me was that I accessed one of my stores through the typical useStore() hook in a parent component, and then passed it through as an argument into my non-react function. 

So as long as your non-react function that you want to call exists inside of a React function, you should be able to pass the store through as an argument and manipulate it without any problems! Thanks so much MobX team for making this product!

**Comment by Albermonte** [comment]
I'm trying to implement some background tasks than run when the app isn't opened, the issue is the same, how can I update the state if I can't call hooks outside components? Any idea?

**Comment by FredyC** [comment]
If the issue is the same, you can apply the same solution. Otherwise, open a new issue with more details/reproduction, please.
