### ISSUE TITLE
How to create a array which is observed deeply with useLocalStore

### ISSUE THREAD

**Issue by Mu-xue** [mobxjs/mobx-react-lite#194]
I have created a store like this
```
const store = useLocalStore(() => {
  obj: []
  setObj() {
    this.obj = [{name: '1'},{name:'2'}]  // It's ok
  }
  changeOne(){
    this.obj[0].name='0' // It's not ok
  }
})
```

When I use `useObserve` hook in my component，when I call `store.changeOne()`, the store has been changed, but My component doesn't re-renders.

**Comment by FredyC** [comment]
Please provide a reproduction, eg with CodeSandbox.
