### ISSUE TITLE
Eslint warns when use autorun in useEffect

### ISSUE THREAD

**Issue by Mu-xue** [mobxjs/mobx-react-lite#197]
I saw this in the docs: [MobX with React ](https://mobx-react.js.org/recipes-effects)
> Important realization here is that you will never need to specify dependencies for useEffect because there are simply none. Or to be more precise it does depend on store variable, but that's the same case as for React.useRef which value you shouldn't specify in dependencies also.

However,  eslint react-hooks/exhaustive-deps warns when I run this code
```
useEffect(
    () =>
      autorun(() => {
        console.log(store.id)
      }),
    [], // note empty dependencies
  )
```
` Warning: React Hook useEffect has a missing dependency: 'store.id'. Either include it or remove the dependency array`

So what should I do when my side effect actually depends on observable value.

**Comment by FredyC** [comment]
Well, point is that it's not the effect itself that depends on that value. You don't want to recreate autorun when a value changes, that would beat the purpose.

So, in this case, you would have to tell eslint to ignore that. You can make yourself a custom hook so you don't have to do it all over the place.

**Comment by Mu-xue** [comment]
@FredyC 
For the reason that the store would not change, I usually write down this:
```
 useEffect(
    () => {
      setLoading(true)
      requestTeamList().then((res) => {
        store.setList(res.teams)
        setLoading(false)
      })
    },
    [store]
  )
```
Is the usage better than autorun?

**Comment by FredyC** [comment]
I don't follow. The autorun is for a specific case when you want to run code when one of the observable changes. I don't see the similarity with that code above.
