### ISSUE TITLE
yarn build fails

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx-react-lite#2]
After cloning this repo and running `yarn` when I run `yarn build` I get:

```
Alexanders-MacBook-Pro:mobx-react-lite alexandergabriel$ yarn build
yarn run v1.12.3
$ node build-rollup.js && shx cp src/index.d.ts index.d.ts && shx cp src/index.d.ts native.d.ts && shx cp src/index.d.ts custom.d.ts
{ Error: Could not resolve entry (src/index.js)
    at error (/Users/alexandergabriel/mobx-react-lite/node_modules/rollup/dist/rollup.js:3460:30)
    at /Users/alexandergabriel/mobx-react-lite/node_modules/rollup/dist/rollup.js:21475:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3) code: 'UNRESOLVED_ENTRY' }
error Command failed with exit code 255.
```

**Comment by FredyC** [comment]
Ah right, sorry about that. Since I've converted everything to TypeScript I forgot to update the build. Will into that today. Or if you have some spare time and knowledge, go ahead :)

**Comment by FredyC** [comment]
Well, I think that whole Rollup configuration needs to ditch Babel completely and just use TypeScript compiler ... https://www.npmjs.com/package/rollup-plugin-typescript2

**Comment by barbalex** [comment]
I'm sorry to say that I have so far mostly successfully circumvented having to deal with build systems by using create-react-app and gatsby. So I will not be any help with that I'm afraid.

**Comment by FredyC** [comment]
@barbalex It's fixed and published to NPM :)
