### ISSUE TITLE
preact support?

### ISSUE THREAD

**Issue by kesha-antonov** [mobxjs/mobx-react-lite#202]
Hey!

How to enable preact support?

Now it shows error ```mobx-react-lite requires React with Hooks support```

```
if (!React.useState) {
    throw new Error("mobx-react-lite requires React with Hooks support");
  }
```

**Comment by FredyC** [comment]
You cannot, you need to use `mobx-preact` AFAIK.

**Comment by kesha-antonov** [comment]
Ok, thanks

**Comment by kesha-antonov** [comment]
https://github.com/marvinhagemeister/preact-faq/blob/master/migrate-to-x.md

preact X worked

**Comment by rvion** [comment]
https://github.com/marvinhagemeister/preact-faq/blob/master/migrate-to-x.md

says:

> ### mobx-preact
> Due to our increased compatibility with the react-ecosystem this package isn't needed anymore. Use mobx-react instead.
> 
> Remove `mobx-preact`
> Install `mobx-react`

Does anyone know if `mobx-react-lite` is supported too ?

- If so, could there be some mention in this readme ? 
- if not, could this lib decide to support `preact` too now that preact X is out and getting popular ?

**Comment by FredyC** [comment]
Interesting. I don't really use Preact, so I guess it's up to you folks to test it out :) If the compatibility is really that close, it should probably work.
