### ISSUE TITLE
Sharing context between multiple stores

### ISSUE THREAD

**Issue by ar7casper** [mobxjs/mobx-react-lite#206]
I'm probably missing something silly and since I could find any ideas online, thought it might be a good opportunity to document this for the future through this issue.

So, the idea is simple, I've got several stores (User, Auth, Strings, etc).
And I would like to be able to access every store from within any store. 

For instance, in AuthStore, I'd like to update the username after I've authenticated - 
``` 
export function AuthStore () {
...
  authenticate() {
  ...
  this.rootStore.main.setUsername('Alex');
  ...
  }
}
```

Normally, it's not an issue.
But I couldn't find a way of doing so using `mobx-react-lite`.

**Comment by FredyC** [comment]
How you structure your stores is kinda out of the scope of this package. There is numerous way including powerful `mobx-state-tree`.

What you have in that sample, those are not even stores, it's just a couple of factory functions returning objects, nothing with MobX there. Using single `useLocalStore` in context is not enough as it won't convert deeply nested actions. It's not meant to be used like that.

**Comment by ar7casper** [comment]
@FredyC 
Yeah, kinda makes sense now that I took a deeper dive. 

I'm trying to avoid using `mobx-state-tree`, it's an overkill for my needs.
`useLocalStore` auto-magically makes the object mobx-y. That what confused me.

Any ideas?

**Comment by FredyC** [comment]
Sorry, no idea, I am a happy user of MST myself so I never had to think about how to interconnect stores in another way. Might feel like overkill, but makes many things easier.

The `useLocalStore` is far from magical, it's basically just `React.useState(() => mobx.observable(...))` with some additional utilities, but nothing to help you in this case.

**Comment by ar7casper** [comment]
From the docs, seems like what I'm trying to do is possible - 
`The naming useLocalStore was chosen to indicate that store is created locally in the component. However, that doesn't mean you cannot pass such store around the component tree. In fact it's totally possible to tackle global state management with useLocalStore despite the naming. You can for example setup bunch of local stores, assemble them in one root object and pass it around the app with a help of the React Context.`

**Comment by FredyC** [comment]
Yea, you got me. I wrote that 😆 I guess you can try `useLocalStore` several times for each store within that context and shove everything to a root object (which does not need to be observable).

**Comment by ar7casper** [comment]
😂 😂 😂 😂 
Let's try making it work and then throw an example in the docs?
Might be useful for future devs, what do you think?

**Comment by FredyC** [comment]
Go ahead :) Every working example is worth it for sure.

**Comment by ar7casper** [comment]
Well, I'm kinda stuck on making it work LUL :)

**Comment by FredyC** [comment]
I gave you some hints, so try that, please. I don't the solution either and since you are currently only one having the problem, it's more or less about your effort. The `mobx-react` in general is not about building and managing your state, it's about easy reactivity.

**Comment by ar7casper** [comment]
@FredyC 

That was a joke.
Eventually, what I did was to remove `mobx-react-lite` and I use React's context like so - 

```typescript
import React from 'react';
import { createStore, Stores } from './createStore';

const store = createStore() as Stores;
const storeContext = React.createContext(store);

export const StoreProvider: React.FunctionComponent<{}> = ({ children }) => {
  return <storeContext.Provider value={store}>{children}</storeContext.Provider>;
};

export const useStore = () => {
  const _store = React.useContext(storeContext);

  if (!_store) {
    throw new Error('You have forgotten to use StoreProvider, go fish');
  }
  return _store;
};
```

where `createStore` is responsible to share context between the different stores.

**Comment by FredyC** [comment]
Yes, that's one way to tackle that for sure. Thanks for sharing, I'll close.

**Comment by matigda** [comment]
@ar7casper what about passing initial data ? Have you tried implementing it in SSR environment? I've been hitting some really danger erros, like for example this one - https://github.com/zeit/next.js/issues/8588
and I don't know where exactly put them. I don't know whether it's my bug or is it NextJS bug or MobX in ssr. In general - examples provided everywhere are really not real-world like, so it is extremely difficult to get it all together.

**Comment by FredyC** [comment]
@matigda Sorry, I am going to lock it here because you are fairly off-topic. Please open a proper issue with all necessary details (some sort of reproduction).
