### ISSUE TITLE
Question about useObserver and other hooks

### ISSUE THREAD

**Issue by igorkamyshev** [mobxjs/mobx-react-lite#216]
Hello! Great lib, thanks for that.

I have one question about hook `useObserver`. Can I use other hooks inside that? I mean something like this:
```
import { useObserver } from 'mobx-react-lite';

const Component = () =>
  useObserver(() => {
    const [count, setCount] = useState(0);
   
    const increment = useCallbacl(() => setCount(c => c + 1));
   
   return (
     <>
       <p>COUNT {count}</p>
       <button onClick={increment}>INC</button>
     </>
   )
  });
```

If it valid example, please check issue in eslint plugin for react hooks. It throwa error for this case. https://github.com/facebook/react/issues/16594

**Comment by FredyC** [comment]
Responded to linked issue for visibility: https://github.com/facebook/react/issues/16594#issuecomment-526816555
