### ISSUE TITLE
[Question] a way to use store with abstracted hook as opposed to wrapping in observer?

### ISSUE THREAD

**Issue by IljaDaderko** [mobxjs/mobx-react-lite#218]
I am currently looking for ways to make my store management as low effort as possible, thus far I came up with this solution (see index.tsx and TestStore.ts files) https://codesandbox.io/s/smoosh-pond-q70ql

I'm really enjoying this, but there is one issue that constantly pops up. I sometimes forget to wrap my component in `observer` or use `useObserver` and it leads to like 10 - 15 min of head scratching figuring out why my values are not updating.

I have an idea for this solution, ideally in my `TestStore` file I would export `useTestStore` function that I could use in my main component like this

```tsx
import useTestStore from "./TestStore.ts"

const App = () => {
const {state, actions} = useTestStore();

   return (
      <input
        value={state.name}
        onChange={({ target }) => actions.setName(target.value)}
      />
   )
}
```

I'm having trouble figuring out how and if it is possible to use `observer` or `useObserver` inside `useTestStore` and return just state and actions, without any component / hoc / render function etc...

**Comment by mweststrate** [comment]
no it isn't, as the above pattern doesn't allow tracking of the usage of
state, which is the point of MobX :). However, you could maybe redesign
your API to something like (didn't think this through): return
renderWithTestStore(store => <input ...etc />)

**Comment by IljaDaderko** [comment]
Got it ok, perhaps `renderWithTestStore` would be helpful in terms of remembering to add `observable`, but I think it has potential to end up with very nested structure if several stores need to be used.

I'll stick to what I have and will try to come up with an eslint rule to help myself remember 😛
