### ISSUE TITLE
https://mobx-react.js.org is down?

### ISSUE THREAD

**Issue by amsdamsgram** [mobxjs/mobx-react-lite#219]
Hi,

Not sure if it is the right place to talk about this but I can't access to https://mobx-react.js.org.
I have a blank page. I've tried on FF, Safari and private mode.

I have multiple errors in the console:
```
Invariant Violation: "Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings
```

**Comment by FredyC** [comment]
Thanks for the heads up. Seems like Docz issue, it got recently updated automatically. Either they will fix it soon I will revert to an older version. I have no capacity to dive deeper right now.

**Comment by FredyC** [comment]
Site is up and running.

**Comment by amsdamsgram** [comment]
Thanks, that was quick!
