### ISSUE TITLE
Idea: Add useAction hook?

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#22]
Looking at the example in README, I have a feeling that this is going to be rather a repeated pattern.

```ts
    const todos = useObservable(new Map<string, boolean>())
    const addTodo = React.useCallback(() => {
        todos.set(todoRef.current.value, false)
        todoRef.current.value = ""
    }, [])
    const toggleTodo = React.useCallback((todo: string) => {
        todos.set(todo, !todos.get(todo))
    }, [])
```

So I am thinking something along the lines of another tiny wrapper around the `useCallback` with empty inputs array by default. Possibly it can use `runInAction` internally. Thoughts?

@xaviergonz @mweststrate

**Comment by xaviergonz** [comment]
```
const actions = useActions({
  addTodo() {
    ...
  },
  toggleTodo(todo: string) {
    ...
  }
})
...
actions.addTodo();
```
With each action in the object wrapped in action with the name set to the object key?

**Comment by xaviergonz** [comment]
What would be the case where a non empty array of inputs would be useful?

**Comment by xaviergonz** [comment]
Then again, this is kind of supported by observable decorators, so this could work as well?

```js
const person = useObservable({
    name: "John",
    age: 42,
    showAge: false,

    get labelText() {
        return this.showAge ? `${this.name} (age: ${this.age})` : this.name;
    },

    // action:
    setAge(age) {
        this.age = age;
    }
}, {
    setAge: action
    // the other properties will default to observables  / computed
});
```

**Comment by FredyC** [comment]
Ah, I thought it makes actions automatically from any functions in that object. In that case, there is a mistake in README as well :)

It feels somewhat nicer to have a separate hook for defining actions. This syntax is somewhat confusing if you need to list all actions in a second argument.

Also, can you actually use the Map inside the observable object? Haven't tried that before.

**Comment by xaviergonz** [comment]
Sure, you can even do this I guess

```js
class Todo {
  ...
  @action toggle() {...}
}
class TodoStore {
  todos = new Map<string, Todo>();
  @action addTodo(): Todo { ...}
}
...
const store = useObservable(new TodoStore); 
store.addTodo()
store.todos[id].toggle();
etc
```

**Comment by FredyC** [comment]
Meh. Classes 🙄 I like [MST](https://github.com/mobxjs/mobx-state-tree) more, but that's not the point. We are not talking about observable outside of the component, but inside to replace a more verbose `useReducer` (I really dislike those strings for action types). 

Also, I would avoid decorators, even though there is apparently some new proposal that's already [at stage 2](https://github.com/tc39/proposals#stage-2) I still don't like to be forced to use classes.

**Comment by xaviergonz** [comment]
if you want to go the full MST route, then besides useActions you could have a useViews :)

The problem with useViews though is that it would only work over actually observable stuff, but wouldn't work for props since it would require them to use inject the props in the inputs array (and probably you'd need to inject different inputs for each different view)

**Comment by xaviergonz** [comment]
Even if useActions is added (which I think is nice anyway), I think it would make sense to add the decorators second parameter to useObservable?

**Comment by FredyC** [comment]
> if you want to go the full MST route, then besides useActions you could have a useViews :)

No, not really. I really just want to DRY up the code from the first example without introducing extra complexity like decorators and other weird stuff. If someone wants that, they are free to use classes or MST directly, no restrains there really.

**Comment by mweststrate** [comment]
Great thinking @FredyC 

I think 

```javascript
const addTodo = useAction(() => {
        todos.set(todoRef.current.value, false)
        todoRef.current.value = ""
})
```

as abstraction over 

```javascript
const addTodo = useCallback(action(() => {
        todos.set(todoRef.current.value, false)
        todoRef.current.value = ""
}), [])
```

is the thinnest possible abstraction, and a great starting point. After that we could introduce further convenience based on patterns that emerge in the community. For example the object literal with actions is need, but I can also imagine that it becomes common practice to pull actions out of the component all together. But anyway it is easy to add later on as additional overload to `useAction`

**Comment by xaviergonz** [comment]
I just want to add that useAction maybe could have a second optional parameter for the action name

**Comment by FredyC** [comment]
@mweststrate Sounds good, thanks.

@xaviergonz If you need a named action for the purpose of debugging, you can do this if I am not mistaken?

```js
const addTodo = useAction(function addTodo() {
        todos.set(todoRef.current.value, false)
        todoRef.current.value = ""
})
```

Not very convenient, that's true. Perhaps your idea with `useActions` could be more useful for that. But in overall I would avoid setting names as strings since it cannot be minified.

**Comment by larrymyers** [comment]
@FredyC I'm actually in favor of using classes for data stores, just because it make encapsulating the logic straight forward and makes it easier to pass via a react context.

Granted I'm very used to the structure of a project where the data stores and components are wired together with a small connected components to synthesize a view model.

**Comment by mweststrate** [comment]
I think I tend to agree with the above comment, I think the cleanest pattern (but just imho / personal preferene!) to work with complex state is (yes, this is basically the view model pattern):

```javascript
class Todos {
  @observable todos = new Map()

  @action addTodo(){ /* etc */ }
}

const TodosComponent = observer(props => {
   const todos = useMemo(() => new Todos(), [])
   // rest of the rendering
})
```

I don't think `useAction(fn)` has a big benefit over `useCallback(action(fn))`, but if it simplifies typings or is needed that often, it might actually be nice as proposed above

**Comment by xaviergonz** [comment]
Only that useMemo can't be trusted to keep an object forever

> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

So something like useRef has to be used instead

**Comment by FredyC** [comment]
@mweststrate I wish there would be a better syntax for defining complex states, POJO would be the best. I would like to eradicate classes from our codebase eventually, not even mentioning decorators.

> Only that useMemo can't be trusted to keep an object forever

We could add `useStore` that would basically accept a factory function and wrap around `useRef`. It would be a documented way of defining complex states and users won't get burned by using `useMemo`.

**Comment by mweststrate** [comment]
@xaviergonz nice catch, missed that note. useRef then indeed. (we could create a util: `useConstValue(() => initializer)`)

**Comment by alsotang** [comment]
I write a lib https://www.npmjs.com/package/rhooks . It abstract some some common patterns related to React hooks.
I think useAction is a common pattern but are not related to mobx. So should we contribute together for `rhooks`?

**Comment by devuxer** [comment]
The [docs](https://github.com/mobxjs/mobx-react-lite/blob/master/README.md) say:

> Subscribe to this issue for a proper migration guide.

What I see here is *long* discussion about the future of mobx-react. As interesting as this is, where do I go to learn how to learn how to use mobx with functional (instead of class) components? What does `useObservable` do that `useState` doesn't? When/how do I use `@action` or `action` or `runInAction`? The API is laid out pretty well in the docs, but I'm a little confused which circumstances to use mobx vs. just plain react state.

**Comment by FredyC** [comment]
@alsotang I don't see a purpose for another package like there. Have a look at [The List](https://nikgraf.github.io/react-hooks/). You can find all those lifecycle hooks in there already

**Comment by devuxer** [comment]
So, if you want the component to create its own instance of a "view model", you would do this?

```js
class Todos {
  @observable todos = new Map()

  @action addTodo(){ /* etc */ }
}

const TodosComponent = observer(props => {
   const todos = useRef(new Todos())
   // rest of the rendering
})
```

With classes, I have been typically passing in the "view model" through props. Any problem with doing that with functional components, like this?

```js
class Todos {
  @observable todos = new Map()

  @action addTodo(){ /* etc */ }
}

const TodosComponent = observer({ todos } => {
   // rest of the rendering
})
```

**Comment by FredyC** [comment]
@devuxer There was a recent discussion on exactly that topic: https://github.com/mobxjs/mobx-react-lite/issues/74

**Comment by FredyC** [comment]
We can close this now in favor of `useLocalStore` introduced in 1.3.0.
