### ISSUE TITLE
Do I have to use createContext to pass stores to components?

### ISSUE THREAD

**Issue by ManuSevenval** [mobxjs/mobx-react-lite#225]
I read your fantastic documentation at about how to use global stores in components at https://mobx-react.netlify.com/recipes-context and I am wondering:

What value does useContext / createContext here?

Wouldn't it be possible to just create an 
1. observable Object and export it from the file
2. import it in the component file
3. wrap my component with `observer()`
4. just access / modify the object properties within the component?

Is there any downside / drawback to this approach? It seems the most straight forward way to work with observables in react so far to me.

I set up a codesandbox to illustrate the approach: https://codesandbox.io/s/elated-breeze-zl2ye

**Comment by mweststrate** [comment]
It is discussed in several other places, but the very short answer is; it
introduces global state unlike context. It might be fine, but it also might
really complicate tests as it requires resetting the state between tests,
and tests can start affecting each others through side effects

**Comment by FredyC** [comment]
In other words, if you don't worry about tests, feel free to have store in global variable :) Luckily, it's not that hard refactor to Context if you later decide it's necessary.
