### ISSUE TITLE
Revive `useComputed` hook again?

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#229]
_Originally posted by @lennerd in https://github.com/mobxjs/mobx-react-lite/issues/38#issuecomment-541001332_

---

Any chance we have a `useComputed` hook again? I wrote one myself also working with `useObserver` similar to the new syntax in Vue 3:

```ts
function useComputed<T>(
  func: () => T,
  deps: ReadonlyArray<any> = []
) {
  return React.useMemo<ComputedValueObject<T>>(() => {
    const computedValue = computed(func);

    return {
      get value() {
        return computedValue.get();
      }
    };
  }, deps);
}
```

```ts
const App = () => {
  const inputRef = React.useRef<HTMLInputElement>();
  const todos = useObservable<Todo[]>([]);
  const pendingTodos = useComputed(() =>
    todos.value.filter(todo => !todo.done)
  );
  const doneTodos = useComputed(() =>
    todos.value.filter(todo => todo.done)
  );
  const addTodo = useAction(() => {
    if (inputRef.current.value === '') {
      return;
    }

    todos.value.push({
      task: inputRef.current.value,
      done: false
    });

    inputRef.current.value = '';
  });
  const toggleTodo = useAction(todo => {
    todo.done = !todo.done;
  });

  const renderTodo = (todo: Todo, index: number) => {
    return (
      <li key={index} onClick={() => toggleTodo(todo)}>
        <input type="checkbox" disabled checked={todo.done} />
        {todo.task}
      </li>
    );
  };

  return useObserver(() => (
    <div>
      <h4>Pending</h4>
      <ul>{pendingTodos.value.map(renderTodo)}</ul>
      <h4>Done</h4>
      <ul>{doneTodos.value.map(renderTodo)}</ul>
      <div>
        <input ref={inputRef} />
        <button onClick={addTodo}>Add todo</button>
      </div>
    </div>
  ));
};
```

You can find a running example here: https://codesandbox.io/s/mobx-hooks-63yr6

TBH I tried around with `useLocalStore` and have the feeling its syntax is actually a lot more cumbersome and error prone than using simple `useObservable` and `useComputed` hooks. (I'm also no big fan of magically transforming object properties and getters to observable and computed properties. But thats another topic.)

At the end it might be a very subjective feeling but the multiple hooks approach feels a lot easier to read to me.

What do you think?

**Comment by FredyC** [comment]
You are right, it's subjective and my opinion is on the other side, the `useLocalStore` is way more concise and readable to me. Can you elaborate on why do you find it cumbersome? 

I believe @xaviergonz was working on some project with a more verbose project, but cannot seem to find it now, only the https://github.com/mobxjs/mobx-react-lite/issues/94#issuecomment-475773636

**Comment by xaviergonz** [comment]
That'd be https://github.com/xaviergonz/mobx-react-component
but the syntax (when using the hooks version) is fairly similar

**Comment by lennerd** [comment]
Thank you two for the great and fast feedback. I will come back to you once I collected my thoughts on this and found the right approach to compare both solutions. Plan to have something by the end of this weekend.

**Comment by lennerd** [comment]
I thought about this a lot today. I'm a programmer for many years now but never studied programming in a university or something like that. So I often face the problem not being able to explain my thoughts and worries with certain solutions of code well enough. I will do my best to be as objective as possible, but please keep that in mind when reading the rest of my comment. 😉 

---

> Sure, it might feel slightly magical, but isn't whole MobX kinda box of magic? ✨

I would like to disagree with this one. Mobx _can_ feel like a magic box for sure. But I think this really focuses around the utility function `extendObservable` which has a very similar syntax to `useLocalStore`. Providing a function with some properties and getters getting transformed into observables and computed properties indeed feels very magical.

On the other hand decorators like `@observable`, `@computed`, or `@action` help reading class properties and class getters as observable and computed properties. Same goes for using the `observable`, `computed` and `action` functions giving you–like the function name says–an observable, a computed property and an action to trigger transactions.

Hooks like `useObservable`, `useComputed` and `useAction` help to read code and underline what they will give in return: observables, computed properties and actions. Nothing more, nothing less. They might require you to write a little more code but at the end you have a clear list of variables bing one of the three things mentioned above.

> But there is fairly good distinction between each other - functions = actions, getters = computeds, properties = you know :)

I see what you mean. But still. For somebody not used to the syntax these functions, getters and properties are what they are and nothing more. The fact that mobx is transforming them to something really powerful is hidden in a hook like `useLocalStore` or function like `extendObservable`.

---

Another thing I'd like to point out making me worry about `useLocalStore` (and I think the name already points to it): I'm basically creating a store inside my component. Thinking about dividing responsibility something powerful as a store object really fells like something not belonging into a component but instead beeing a seperate class i'm using for my application. Using a class for a store also gives me the possibility to use decorators and therefore IMO improve my code to be more precise and readable.
 
---

And finally IMHO passing a whole props object as a second argument to `useLocalStore` to use it inside my store is missing the point of defining precise dependencies. I can totally see why you implemented it the way you did. But if you compare this to built in hooks like `useEffect`, `useMemo` or `useCallback`, you give people a new way to define dependencies. This might be a good thing and again I might be driven by subjective feelings. But at the same time I think its very important to use learned patterns to support the idea behind hooks and how you work with them.

I updated my example on CodeSandbox: https://codesandbox.io/s/mobx-hooks-63yr6
The example now includes examples for how to work with properties coming from outside the component.

---

Don't get me wrong. I'm really inspired by all the work and ideas you put into this library. I really can see a lot of decisions and discussions going into the current solutions. And I really hope we can find a compromise. And if not I still will be thankful for a good discussion. 😉

**Comment by lennerd** [comment]
@xaviergonz It's indeed very similar. Still, thank you for the link! I think there are again a few nice ideas when using Mobx with React hooks.

**Comment by FredyC** [comment]
> I'm basically creating a store inside my component. Thinking about dividing responsibility something powerful as a store object really fells like something not belonging into a component but instead beeing a seperate class i'm using for my application.

It's perfectly normal to have component local state, it's basically an observable alternative to `React.useState`. The `useLocalStore` wasn't really meant to set up a whole application state. You can uses classes or MST or whatever for that. It's just a tool really, you are not forced to use it.

> And finally IMHO passing a whole props object as a second argument to `useLocalStore` to use it inside

Where did you get the idea that you _have to_ pass the whole props object? You can pass any object with a stable structure. You can pick some values from props, some from context, some from react state, mix it together and allow the store to stay up to date with those values. I wouldn't be comparing it to React dependencies. It's not used to recreate/rerun something.

I don't think we will be adding `useComputed` or any other hooks in here. The `mobx-react-lite` is more like a basic building block and bloating it with more stuff doesn't feel right. Feel free to make a new library, eg `mobx-react-hooks` and we can surely keep it under the MobX flag and you can maintain it. It can be also added to official https://mobx-react.js.org docs if you like.

Personally, I don't like `pendingTodos.value` from your example. In my opinion it might be even harder to explain to a newcomer why the `value` is needed. On the contrary with `useLocalStore`, the getter makes sense to get a value and you are using value directly without any extra wrappers.

**Comment by lennerd** [comment]
> It's perfectly normal to have component local state, it's basically an observable alternative to React.useState. The useLocalStore wasn't really meant to set up a whole application state (hence "local").

I know about component local state and I use it quite a lot for components like accordions etc. The accordion is a quite good example actually. `useLocalState` can be used for a lot more (not only for local state) and thats whats worring me when introducing such a library to teams I'm working with. 

> The mobx-react-lite is more like a basic building block and bloating it with more stuff doesn't feel right.

Exactly. For me `useLocalStore` is not a simple building block. It's an all in one solution. Maybe I'm wrong but something like `useComputed` etc. feels a lot more like a really basic building block I can create something like `useLocalStore` with.

> Where did you get the idea that you have to pass the whole props object? You can pass any object with a stable structure.

I know, I know. But I think the main purpose will be people passing props to use them inside their actions and computed properties.

> I wouldn't be comparing it to React dependencies. It's not used to recreate/rerun something.

Again something I would takle differently. When passing new dependencies I would expect to get a new computed property or observable. Again similar to how `useMemo` or `useCallback` is working.

> Personally, I don't like pendingTodos.value from your example. In my opinion it might be even harder to explain to a newcomer why the value is needed. On the contrary with useLocalStore, the getter makes sense and you are using the value directly without any extra wrappers.

Also, this is something very similar to how React is doing it with `useRef` and why I was thinking about a similar solution. If you learned to use `useRef` with `current` you will also be able to use a wrapper like I'm using in my examples. Vue 3 is using the same syntax in their new setup function and I think its a really nice way for working with primitive observables (again mostly subjective I guess).

> It can be also added to official https://mobx-react.js.org docs if you like.

Thank you for the nice offer. Reading your posts I often see you working for one primary and agreed solution (and thats what I'm hoping for when using something like `mobx-react-lite`). So I think a separate repository under an my personal profile better translate this idea and intend and does not mix up recommended ways to do things with Mobx and React. But again, thanks for you offer.

At the end I'm totally okay with "agree to disagree". Close this issue (thanks for opening it in the first place) if you feel it's enough discussion for now.

**Comment by FredyC** [comment]
> `useLocalState` can be used for a lot more (not only for local state) and thats whats worring me when introducing such a library to teams I'm working with.

I don't follow. The `useState` or `useReducer` can also be used for much more, there is no difference effectively except how is state modified. If mutating properties directly bothers you, there is a strict mode so you need actions to modify anything.

> Maybe I'm wrong but something like `useComputed` etc. feels a lot more like a really basic building block I can create something like `useLocalStore` with.

Well, you can't. It's not possible to compose these hooks into a store-like object or at least I am not aware it would be. The `useLocalStore` is basic building block because it builds on top of `observable` which is basic on its own.

> I know, I know. But I think the main purpose will be people passing props to use them inside their actions and computed properties.

Again, why would you think that? That argument is not even called "props" and in all examples, we are calling it "source". It's a tiny wrapper around `useAsObservableSource`. There is literally no mention of props.

> Again something I would takle differently. When passing new dependencies I would expect to get a new computed property or observable. Again similar to how `useMemo` or `useCallback` is working.

You are mixing together two different worlds. MobX builds on top of referential integrity. If you would be throwing away computed/observable every time then ... then, you don't need to bother with MobX at all ;) We are talking about composite derivation here. You convert your props/state/context into observable and compose a derivation from it which will state up to date.

Have fun with MobX, seems like you are taking it way too seriously :)

**Comment by lennerd** [comment]
> Have fun with MobX, seems like you are taking it way too seriously :)

This sentence really confuses me. 😟I put a lot of energy in my examples and my comments hoping to have a good discussion. Hearing something like that kind of … hurts? I hope I didn't say something to offend you or your work. If yes sorry for that!

> I don't follow. The useState or useReducer can also be used for much more, there is no difference except in a way how is such as state modified. If mutating mobx properties directly bothers you, there is a strict mode so you need actions to modify anything. If you pass reducer "dispatch" in props, it's very similar except you don't need to be passing props separately.

You're right about `useReducer`. It's also the reason I never use it. Having so much logic in my components often proved to produce harder to maintain components and to be not a good practice to me.

> Well, you can't. It's not possible to compose these hooks into a store-like object or at least I am not aware it would be. The useLocalStore is basic building block because it builds on top of observable which is basic on its own.

`useLocalStore` does a little bit more than just using observables, no? Its converting its dependencies to observables and functions inside the initial state to actions. But correct me if I'm wrong.

A simple example for `useLocalState` implemented via `useObservable`: 
``` ts
function useLocalState(func, deps = []) {
  // Missing: Creating actions from functions and converting deps to observables.
  return useObservable(React.useMemo(func, deps), deps).value;
}
```

> Again, why would you think that? That argument is not even called "props" and in all examples, we are calling it "source". It's a tiny wrapper around useAsObservableSource. There is literally no mention of props.

Both the [examples and explanations](https://mobx-react.js.org/state-local#non-observable-dependencies) around it mention props. You also say that you can use dependencies coming from `useReducer` or `useState` to "mix things up". But why should I do this? `useLocalState` is powerful enough to replace `useReducer` and `useState` in most cases. Leaving props (and context) being the only dependencies really making sense to me. Again, you can use what ever you want, I know. But I don't see why I should. And than there is the learned way of using dependencies in hooks to shallow compare them in situations like `useMemo` or `useCallback` etc. Therefore first things coming into my mind are props as dependencies.

> You are mixing together two different worlds. MobX builds on top of referential integrity. If you would be throwing away computed/observable every time then ... then, you don't need to bother with MobX at all ;) We are talking about composite derivation here. You convert your props/state/context into observable and compose a derivation from it which will state up to date.

I know how Mobx is working. I did a lot of projects with it the last years enjoying a lot of it's concepts and ideas. You might have misunderstood my comment here. To be clear I don't want to throw away observables or computed properties when ever something changed inside my Mobx observables. I was talking about props or context or what ever you like coming from the outside. The way you are doing it is totally fine of course. But it requires me to have my props or what ever dependency you have converted to observables. A "hack" I feel being not necessary when defining props as dependencies like `useMemo` is doing it. Again something I learned from React I think would also make sense in our case.

For example:
```ts
const { initalCount } = props;
const count = useObservable(0);

const counter = useComputed(() => (
  count.value + initialCount;
), [initialCount]);
```

Anyway. About me taking this whole thing too serious. We both write business software with Mobx. I don't see why we cannot talk about different concepts of using it (with hooks) in a more serious way and a good discussion, right? Or did you hear me saying you taking Mobx not serious enough? 😄😉

**Comment by lennerd** [comment]
One last thing about dependencies defined as an array: I can deconstruct them like in the example above. This is totally subjective I guess, but I really like to deconstruct properties to make my code easier to grasp and read.

**Comment by mweststrate** [comment]
Please note that `useLocalStore` is really designed for complicated cases, so where you have complicated view models, which depends on observables, but also get some configuration passed down to props etc. So it is really designed to be able to handle *all* cases. 

However, in many cases you don't need it, and you can achieve tings like `useComputed` so easily with either `useMemo` or `useState` that it is barely worth extending the api for that (I myself usually use `const [counter] = useState(() => computed(expr))` etc.

We head some api's like the proposed 
```
const counter = useComputed(() => (
  count.value + initialCount;
), [initialCount]);
```
in the past IIRC, but it is kinda misleading; (just one of the problems:) if a new computed is created for new `initialCount`, it means that `counter` will trigger a downstream change even if the output didn't actually change (although that problem is probably addressable). 

So in the end, when discussing the api we opted for a minimal api that can handle basically all cases, and encourage people further to use and compose with the standard api, rather than providing a hook for every possible use cases. So for more background about the current design, which also discusses some proposals similar to yours I recommend to first study #94 (if you didn't already), so that we have the same background info when further discussing this :)

**Comment by FredyC** [comment]
> I hope I didn't say something to offend you or your work. If yes sorry for that!

Not at all. You have offered to close the issue, so I did as I thought you are done with the discussion. It was merely a lame attempt at the closing remark. Don't mind me :)

> `useLocalStore` does a little bit more than just using observables, no? Its converting its dependencies to observables and functions inside the initial state to actions. But correct me if I'm wrong.

Yes, there is a little bit of extra code, but nothing magical hidden in it. And really, let's not call it dependencies. Unless you actually use values from the source in that store, it won't have any effect. That's a whole different paradigm than React dependencies.

> Both the [examples and explanations](https://mobx-react.js.org/state-local#non-observable-dependencies) around it mention props.

Thanks, I'll fix example, although explanation does mention a "mix" of anything as I said before. It's also for performance reasons you don't want to be passing all props and convert to observables unless you really need all of them. It's generally better to be explicit there.

> A simple example for `useLocalState` implemented via `useObservable`

Friendly advice, don't ever useMemo for anything state-related - you might lose it whenever React feels like it.

> But it requires me to have my props or what ever dependency you like have converted to observables. A "hack" I feel being not necessary when defining props as dependencies like `useMemo` is doing it.

Yea sure, it's a performance hack. With "dependencies" you can be recreating stuff all the time and it will work as well, but you would be getting extra re-renders: one for dependency change, another for observable being recreated and triggering a reaction.

**Comment by lennerd** [comment]
> However, in many cases you don't need it, and you can achieve tings like useComputed so easily with either useMemo or useState that it is barely worth extending the api for that (I myself usually use const [counter] = useState(() => computed(expr)) etc.

You might be right. I'm always wondering about custom hooks. They are so easy to use that we tend to recreate them for every project. I think thats a great thing. I think. Is it?! Anyway. Good point.

> if a new computed is created for new initialCount, it means that counter will trigger a downstream change even if the output didn't actually change (although that problem is probably addressable).

Thank you for the example and inside! Didn't know about this.

> So for more background about the current design, which also discusses some proposals similar to yours I recommend to first study #94 (if you didn't already), so that we have the same background info when further discussing this :)

Yeah I saw that issue and read through a number of comments (not all to be honest). Thanks for the insights and the opinion.

> Not at all. You have offered to close the issue, so I did as I thought you are done with the discussion. It was merely a lame attempt at the closing remark. Don't mind me :)

Sounds like a misunderstanding on my side. Sorry. 😉

> Friendly advice, don't ever useMemo for anything state-related - you might lose it whenever React feels like it.

I remember reading about something like that. 🙈Thank you for the hint!

> Yea sure, it's a performance hack. With "dependencies" you can be recreating stuff all the time and it will work as well, but you would be getting extra re-renders: one for dependency change, another for observable being recreated and triggering a reaction. It's also somewhat wasteful when you can just update a derivation.

True that. Still feels strange to have props and other dependencies converted. Had this problem with the `observer` of `mobx-react`. Although to be honest it proved to be helpful to have props tracked as observables more than once.

One more thought about this: the example by @mweststrate (and there are probably a few more) are great for the documentation to show how easy you can combine both libraries. Some kind of hook recipe page maybe? This also would remove the implication (from my view on the documentation) that `useLocalState` is the preferred or recommended way when working with Mobx and React hooks. When at the same time you really can solve simple tasks with the examples like @mweststrate  posted.

Anyway. Thank you both for your opinions. I definitely better understand thoughts behind `useLocalState` and the advantages of the way of using it now. Learned quite a bit in the process. So thank you.

**Comment by mweststrate** [comment]
I think it would be indeed to mention the above example in the docs (PR
welcome!) as I noticed many tend to over complicate this.

**Comment by xaviergonz** [comment]
FYI, I just published a v2.0.0 of mobx-react-components which basically embraces separating mobs state from the component itself to avoid common pitfalls such as destructuring props and the like.
I know some people aren't fond of decorators, but in my personal opinion I like them :)

Basically by decoupling the component rendering from the "local state parts", there's no way to actually use destructured props or unobservable dependencies (such as ones coming from context or useState), so they don't even need to be documented.

```ts
import { action, computed, observable, when } from "mobx"
import { MobxLocalState, mobxObserver, useMobxLocalState } from "mobx-react-component"
import * as React from "react"
import { memo, useContext } from "react"
import { SomeContext } from "./SomeContext"

interface IMyComponentProps {
    x: number
}

// here we define the "mobx local state" of the component
// dependencies (usually just props, but might include inputs from other hooks)
// are declared here and are turned into observables accessible through either
// this.props.NAME or this.NAME

class MyComponentState extends MobxLocalState<IMyComponentProps & { z: number }>() {
    @observable y = 0

    @computed
    get sum() {
        // x comes from component props
        // y comes from local observable
        // z comes from context
        return this.x + this.y + this.z
    }

    @action
    incY = () => {
        this.y++
    }

    getEffects() {
        // effects will be started on first render and auto disposed on unmount
        // you might use getBeforeMountEffects() instead if you want to run them
        // before the component is first mounted
        return [
            when(
                () => this.sum === 10,
                () => {
                    alert("you reached ten! (hooks / useMobxLocalState)")
                }
            )
        ]
    }
}

export const MyComponent = memo(
    mobxObserver((props: IMyComponentProps) => {
        const ctx = useContext(SomeContext)

        const s = useMobxLocalState(
            MyComponentState,
            {
                ...props,
                ...ctx
            },
            // the way to turn the object above into an observable is shallow by default,
            // but you can also specify "deep" or an object to cherry pick which properties
            // need to be turned into deep observables
            "shallow"
        )

        return (
            <div>
                <div>
                    x + y + z = {s.x} + {s.y} + {s.z} = {s.sum}
                </div>
                <button onClick={s.incY}>Increment Y (state)</button>
            </div>
        )
    })
)

MyComponent.displayName = "MyComponent"

// usage
// <MyComponent x={5}/>
```

**Comment by lennerd** [comment]
I guess you prefix your HOCs and Hooks with mobx because you want to circumvent naming collisions, right? I really like the idea of using a separate local state class (I'm also a big fan of decorators)!

But: I'm not a big fan of prefixed HOCs and Hooks to be honest. Very subjective thing, but imagine lodash or others would prefix every util function they have with `_` or `lo` or `lodash`, etc. For me if I really run in naming collisions, I use the module aliases to rename imports directly. But like I said, a very subjective opinion. 😉

Anyway. Thanks for sharing!

**Comment by xaviergonz** [comment]
Well you can always re-export them with whatever name you want :)

**Comment by lennerd** [comment]
Thats another way of seeing it. 😆
