### ISSUE TITLE
Idea: Add useObserver

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#23]
```js
function MyObserverComponent(props) {
  const observe = useObserver();

  return observe(() => {
    return <div>props.observable.x</div>
  });
}
```

I think it could have several advantages:
1. you can specify the exact specific piece of code that runs inside the reaction tracking, so you can do observable mutations outside it easily without triggering unwanted renders
2. you can memo your component, forward ref it or whatever you want without observer getting in the middle

Maybe the only disadvantage though is that you actually have to write "observe" or whatever name you assigned over the render phase though

Maybe offer it as an alternative to "observer" at least for advance use cases?

observer uses something like that internally anyway

_Originally posted by @xaviergonz in https://github.com/mobxjs/mobx-react-lite/issues/7#issuecomment-439679656_

**Comment by FredyC** [comment]
I think it might be an interesting alternative to the `observer` is not polluting the tree. Question is, wouldn't that be somewhat confusing to have a 3rd option? How would user decide what to use?

**Comment by xaviergonz** [comment]
Actually maybe this would be better to avoid people from reusing the observe function more than once (which would break)

```
function MyObserverComponent(props) {
  ...
  useObserver(() => {
    return <div>props.observable.x</div>
  });
}
```

As for which one to use, guess it would deprecate `<Observe>` ?

**Comment by FredyC** [comment]
Well, that would be kinda breaking a [rule/recommendation of hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) which should be called on top of the component. Might be confusing to people given the "magic" nature of hooks.

> Don’t call Hooks inside loops, conditions, or nested functions. Instead, **always use Hooks at the top** level of your React function.

So, in the end, the `<Observer />` is still the best option as it allows you to observe only a part of the tree, not the whole component. And it doesn't this issue of multiple uses.

**Comment by xaviergonz** [comment]
well, it would be the "last" hook of the top of the component :) (therefore the return)

**Comment by FredyC** [comment]
Feel free and try to implement it. There is certainly some appeal to it that you don't need a wrapping HOC and thus no magic around ref forwarding and stuff.

**Comment by xaviergonz** [comment]
Now that I think about it this actually allows me to use useObservableProps without getting unwanted re-renders :D (since the mutation is done outside the tracked part)
