### ISSUE TITLE
Add devcheck that ensures initializer of useLocalStore stays reaction free.

### ISSUE THREAD

**Issue by omerman** [mobxjs/mobx-react-lite#233]
Hi,
First of all great library thank you for making it!

In order to elaborate regarding the topic I'll just show an example.

Here is a code that can easily be written inside a function component:

```
const myLocalStore = useLocalStore(() => ({
   supposeToBeComputedProperty: anotherStore.value,
}));
```

The code above clearly should be written like so:

```
const myLocalStore = useLocalStore(() => ({
   get supposeToBeComputedProperty() {
     return anotherStore.value;
   }
}));
```

So I was thinking that in order to prevent such mistakes, a dev check that ensures the `useLocalStore` initializer is not reactive is a neat improvement.

I drafted this:

```
...

const [initializer] = args;
useEffect(
  () => {
    const disposeReaction = reaction(
      initializer,
      () => {
        throw new Error(`
          useLocalStore:: initializer should not be reactive.
        `);
      },
    );
    return disposeReaction;
  },
  [],
);

...
```

Please let me know what you think :)
Thanks again.

**Comment by FredyC** [comment]
Well, I think that question is, why would you even do what you did? What's your thinking about this pattern?

```js
const myLocalStore = useLocalStore(() => ({
   supposeToBeComputedProperty: anotherStore.value,
}));
```

Why not use `anotherStore.value` directly? The computed makes sense when you actually want some derivation of that value.

```js
const myLocalStore = useLocalStore(() => ({
   get supposeToBeComputedProperty() {
     return anotherStore.value * 20;
   }
}));
```

Point is, that when you actually do a derivation it's very likely you will realize some function is necessary for re-evaluation to happen.

---

That said, dev checks are a mostly nice thing to have, but I think in this case it would be unnecessary slowdown to cover for the kind of rare case of a mistake.

**Comment by omerman** [comment]
I see your point.

Thank you :)
