### ISSUE TITLE
useLocalStore() does not work in strict mode of mobx, unless functions are actions

### ISSUE THREAD

**Issue by madeofsun** [mobxjs/mobx-react-lite#235]
I have noticed that if the strict mode of mobx is enabled, there is an error, unless functions that modify observable values are wrapped in action. 

Which is strange, because that is stated that useLocalStore() wrap every function in transaction, which are actions in modern mobx API.

But then I looked into code and discovered that, actually, the transaction() API is used, that is deprecated as I understood <- https://doc.ebichu.cc/mobx/refguide/transaction.html

I think, it would be convenient to wrap functions in actions instead.

_mobx 5.14.2 was used_

**Comment by FredyC** [comment]
Please use `mobx-react-lite@next` which should work better with Strict and in theory also Concurrent mode.

**Comment by madeofsun** [comment]
Reproducible with mobx-react-lite@next

CodeSandbox - https://codesandbox.io/s/mobx-react-liteissue235-iz1kt
When strict mode is enabled, you can see the error in the console.

**Comment by FredyC** [comment]
Ah, I got it confused with Strict mode of React, but you are talking about the strict mode of MobX :)

See https://github.com/mobxjs/mobx-react-lite/issues/170#issuecomment-497825320, that should help you.

**Comment by FredyC** [comment]
Yea, just verified modify it like this, it's without error.

```js
    addApple: action(function() {
      try {
        this.numberOfApples += 1;
      } catch (err) {
        console.error(err);
      }
    }),
```

It's not that pretty anymore, it's true. Also you need to make sure to use `function`, the anonymous fat arrow would not allow you to access `this`. I would almost say that `useLocalStore` is not worth in strict mode.

**Comment by madeofsun** [comment]
Thank you.
Can you, please, update the docs also (https://mobx-react.js.org/state-local), because there transaction is interpreted as action (there is a link to https://mobx.js.org/refguide/action.html). which is confusing.

**Comment by FredyC** [comment]
PR is surely welcome :)
