### ISSUE TITLE
Proper way to run @action within useEffect

### ISSUE THREAD

**Issue by kysley** [mobxjs/mobx-react-lite#236]
I've been doing some digging on the proper way to call mobx actions inside useEffect. I saw an issue that says wrapping the `useEffect` in a `reaction` or `when` can work, but am having troubles on the implementation..

async flow function (implementation works fine): 
```js
  generateWords = flow(function*(
    this: GameStore,
  ): Generator<Promise<any>, void, any> {
    if (!this.fetchingWords) {
      this.fetchingWords = true
      const {
        data: {getWordSet},
      } = yield client.mutation(GET_WORD_SET).toPromise()
      this.loadWordSet(getWordSet)
      this.fetchingWords = false
    }
  })
```

```js
const Singleplayer: FC = observer(() => {
  // useStore() taken from the docs recipes
  const {GameStore} = useStore()

  // I want generateWords() to only be called on mount.. ala componentDidMount()
  useEffect(() => {
	GameStore.generateWords()
    return () => {
      // ...
    }
  }, [])


  return (
	// ...
  )
})
``` 

From my understanding, the `observer` doesn't know that `generateWords` was called, so the UI is never updated until a force rerender. Is there a way to incorporate `reaction` or `when`, so that `generateWords()` will only be called on mount?

Any help would be superb 😅

**Comment by FredyC** [comment]
> From my understanding, the `observer` doesn't know that `generateWords` was called

The observer will re-render if some observable in GameStore changes and you render it. Eg. if you would render `fetchingWords` to show some loading indicator, it would re-render component. There is no need for reaction/when here.

**Comment by kysley** [comment]
Thanks for the reply! I _am_ actually rendering the observable, but in a child component (which is also an observer). Let me elaborate with a more succinct example: 

Even if I map out GameStore.words in the same component, nothing is visibly shown until a forced rerender.

```js
const Singleplayer: FC = observer(() => {
  // useStore() taken from the docs recipes
  const {GameStore} = useStore()

  useEffect(() => {
	GameStore.generateWords()
    return () => {
      // ...
    }
  }, [])


  return (
  	{GameStore.words.map((word: string, i: number) => (
  		<div>{word}</div>
    ))}
  )
})
```

**Comment by FredyC** [comment]
Well, if CodeSandbox works then there must be something that you are doing differently. These examples look fine to me. Please keep trying, I don't really have capacity to dive into a whole project :)

**Comment by kysley** [comment]
@FredyC Ahh! It turns out it was `React.StrictMode` causing the issue. I had my App root wrapped in it... I definitely didn't heed your advice in the Readme.

Sorry for such a silly issue! 😅 I upgraded to `mobx-react-lite@next` and we are all good now
