### ISSUE TITLE
Access store data from hook in local store getters will trigger unlimited renders.

### ISSUE THREAD

**Issue by SidKwok** [mobxjs/mobx-react-lite#237]
Here is the related code:
```typescript
import React from 'react';
import { observer, useLocalStore } from 'mobx-react-lite';

const context = React.createContext(null);

function useTest() {
  const store: any = React.useContext(context);
  return store.list.map(e => e)
}

const Test = observer(() => {
  const store: any = React.useContext(context);
  console.log('render');
  const list = useTest();
  const local = useLocalStore(source => ({
    get list() {
      return source.list
    }
  }), { list })
  return (
    <div>
      <p>
        str: {JSON.stringify(local.list)}
      </p>
      <button onClick={store.set}>click</button>
    </div>
  );
});

const App = () => {
  const store = useLocalStore(() => ({
    list: [] as any,
    set() {
      store.list = []
    }
  }));

  return (
    <context.Provider value={store as any}>
      <Test />
    </context.Provider>
  )
};

export default App;
```

It will render unlimited times every time I set the store data `list`

Mobx: 5.14.2
mobx-react-lite: 1.5.0
react: 16.11.0

**Comment by FredyC** [comment]
Why would you do that? There is no added value in it... Just use the passed store.
```js
  const local = useLocalStore(source => ({
    get list() {
      return source.list
    }
  }), { list })
```

What is `useTest` supposed to do?

And finally where are changing that list?

**Comment by SidKwok** [comment]
I simplify the case. The more complex one is that I **do common logic in `useTest` hook**，and **do the own login (it may has its own states) in localStore**
```typescript
function useTest() {
  const store: any = React.useContext(context);
  return store.list.map(e => {
    // do the common logic
    // shared between different components
    return { value: e };
  })
}

// ...
const local = useLocalStore(source => ({
  ownState: false,
  dealWithOwnState() {
    local.ownState = !local.ownState;
  },
  get list() {
    // due with store state with its own states
    return source.list.map(e => ({ self: local.ownState ? e : 'hi' }))
  }
}), { list })
```

**Comment by FredyC** [comment]
Can you please move it to CodeSandbox? I don't see any problem here with a glimpse of an eye.

**Comment by SidKwok** [comment]
@FredyC 
https://codesandbox.io/s/unruffled-cori-cf9d8

click *button-click* as see the console

**Comment by mweststrate** [comment]
I took a quick look at the sandbox, but I couldn't figure out what it is
*trying* to do. Can you take a few steps back and try to explain what you
are trying to accomplish?

**Comment by SidKwok** [comment]
@mweststrate 
1. I am trying to separate the common login from global store with hook (see `useTest`), the hook may be used by different components.
2. combine the common logic with local states (see `get list()`). The computed state is based on global store and local store. And every component may have their own way to deal with *the common logic* and their own states.

**Comment by mweststrate** [comment]
Ok, what I don't get:
1. Is all state to supposed to be shared, or does each component have it's
own? It seems at the moment you are mixing both
2. Is the common logic supposed to operate on the shared state, or on state
owned by the component
3. If state is both own and global, I think it is going to terribly
confusing. Why should components have their own login state? At least I
wouldn't try to capture those two different concepts in the same hook.

I'd expect something like this:

const loginStore = some observable
const loginContext =context providing that store as value
const useLoginStuff = function that returns api / data, but operates on the
value of the context (instead of producing new state every time it is
rendered)

**Comment by SidKwok** [comment]
1. Not all state will be shared, only context-store will be shared, and each component has its own state. 
2. The common logic(useTest) is supposed to operate on the shared state, and it may produce a new state(like computed data).
3. The hook only deal with the global state, but it may be used by different components.
```typescript
function useTest(text: string) {
  // it only *produce state* from global store
  const store: any = React.useContext(context);
  return store.list.map(e => {
    return { value: e, text };
  })
}
```

> Why should components have their own login state? 

Imagine there is a raw jsonString in the store, which is from the http server. And we use hook to parse the jsonString(`JSON.parse(jsonString)`). But every component have their own logic to deal with the parsed-jsonString. Com1 may get something from the parsed-jsonString based on Com1's own state, and Com2 may just render the parsed-jsonString.

> const useLoginStuff = function that returns api / data, but operates on the
value of the context (instead of producing new state every time it is
rendered)

You mean the hook should only return context state but not produce a new one? If the hook can only return context state, which means the hook can only return states from context-state, but can't add any logic.
```typescript
function useTest(text: string) {
  const store: any = React.useContext(context);
  // can't do anything with the state
  return store.list;
}
```

**Comment by FredyC** [comment]
@SidKwok Have you figured out some way? Do you still need help with this?
