### ISSUE TITLE
how to reference other model in useLocalStore?

### ISSUE THREAD

**Issue by hardfist** [mobxjs/mobx-react-lite#241]
It's very convenient do observable references to other observable, just like the following 
```ts
export class Todo {
    id: number
    @observable text: string
    @observable done: boolean
    @observable deleted: boolean

    constructor(text: string) {
        this.id = generateTodoId();
        this.text = text;
    }
    toggleDone() {
        this.done = !this.done
    }
    remove() {
        this.deleted = true
    }
}

export class TodoList {
    @observable list: Todo[] = []

    get validTodos() {
        return this.list.filter(todo => !todo.deleted)
    }

    createTodo = (text: string) => {
        const todo = new Todo(text);
        this.list.push(todo)
        return todo;
    }
}
```
how to implement this in useLocalStore

**Comment by FredyC** [comment]
Pretty much the same way. It might be useful you show what you have tried and did not work for you.

**Comment by hardfist** [comment]
@FredyC Thanks!
 I figure it out, There's nothing to do with useLocalStore, useState works fine for me, The reason I failed because I forget to wrap Todo Component with observer, which doesn't rerender event todo is changed . The demo is here 
https://github.com/hardfist/hooks-puzzle/blob/master/src/store/todo.store.ts

**Comment by hardfist** [comment]
I have another question, what's the difference between The following code when TodoStore is observable already  https://github.com/hardfist/hooks-puzzle/blob/master/src/components/todo-mobx-local/index.tsx
```
const store = useLocalStore(() => new TodoStore());
const [store] = useState(() => new TodoStore()); 
```

**Comment by mweststrate** [comment]
Nothing 😊 and useState will do just fine

Op za 16 nov. 2019 14:27 schreef hardfist <notifications@github.com>:
