### ISSUE TITLE
Keep generic arguments when using `observer`

### ISSUE THREAD

**Issue by Kukkimonsuta** [mobxjs/mobx-react-lite#243]
When using `observer` to wrap component that accepts generic argument the generic argument is lost effectively removing option to have observer components with generics. I've been able to hack together following workaround, but it would be great if generics weren't lost by default in `observer`. `mobx-react` works with generic component correctly.

Workaround:
```ts
function genericObserver<T extends React.FunctionComponent<P>, P extends object = T extends React.FunctionComponent<infer P> ? P : unknown>(fn: T): T {
	return observer<P>(fn) as T;
}
```

Current behavior:
![image](https://user-images.githubusercontent.com/737093/69500055-ffd3c100-0ef7-11ea-8b62-4d1f16616e75.png)

Desired behavior (similar to `mobx-react`):
![image](https://user-images.githubusercontent.com/737093/69500187-39f19280-0ef9-11ea-9a25-27840d5c6450.png)

Sample codesandbox: https://codesandbox.io/s/zen-mestorf-4hp7q

**Comment by FredyC** [comment]
I am confused, looking at your CodeSandbox, how is the outcome different? In both cases, I see that `value` is `unknown`.

```tsx
const Bar = observer(<T extends unknown>({ value }: { value: T }) => {
  return <>{JSON.stringify(value)}</>;
});

const Baz = genericObserver(<T extends unknown>({ value }: { value: T }) => {
  return <>{JSON.stringify(value)}</>;
});
```

> `mobx-react` works with generic component correctly.

That is really strange thing to say because `mobx-react@6` builds on top of this lib and [doesn't do anything special about generics](https://github.com/mobxjs/mobx-react/blob/78c6b4964c7703de7a673913d759e9a2aab669f3/src/index.d.ts#L23). On the contrary it works even worse. Try to switch for `mobx-react` in your sandbox, the `<P>` won't work anymore.

**Comment by Kukkimonsuta** [comment]
Within the component itself the typing is fine, however outside (after `observer` is applied) the generic parameter gets replaced by `unknown` and cannot be inferred.

![image](https://user-images.githubusercontent.com/737093/69500463-8c33b300-0efb-11ea-8b73-e62a898e64b1.png)

vs

![image](https://user-images.githubusercontent.com/737093/69500454-745c2f00-0efb-11ea-90b8-92f6a4d9a7ae.png)

These screenshots are taken directly from the sandbox.


I suspect `mobx-react` works because the typing for `observer` is different:

```ts
export type IReactComponent<P = any> =
    | React.StatelessComponent<P>
    | React.ComponentClass<P>
    | React.ClassicComponentClass<P>

export function observer<T extends IReactComponent>(target: T): T
````

vs

```ts
export function observer<P extends object, TRef = {}>(
    baseComponent: React.RefForwardingComponent<TRef, P>,
    options: IObserverOptions & { forwardRef: true }
): React.MemoExoticComponent<
    React.ForwardRefExoticComponent<React.PropsWithoutRef<P> & React.RefAttributes<TRef>>
>
export function observer<P extends object>(
    baseComponent: React.FunctionComponent<P>,
    options?: IObserverOptions
): React.FunctionComponent<P>
```



For `mobx-react` the `genericObserver` workaround doesn't work, but it doesn't need to as `observer` returns generic function already:

![image](https://user-images.githubusercontent.com/737093/69500514-2b58aa80-0efc-11ea-917b-1c1541efe30b.png)

**Comment by FredyC** [comment]
Sorry, still confused. Why do want to inference for props to work? What's the point? On the contrary, you should be doing `observer<{ value: number >}(({ value }) => ...` so it's properly type checked whenever you used that component on the outside.

**Comment by Kukkimonsuta** [comment]
I have chosen simple example where it doesn't really make sense, however once you bring in bit more complexity it can be very useful - if the type is inferred you can use it multiple times and type checker ensures the types are the same. This is very useful for passing data down to a component that are expected to come back in some form using a callback.

In the following sandbox there is simple select component that can accept `value`, `options` and `onChange` and get type check that all are of the same type, but not limiting consumer to using specific one.

https://codesandbox.io/s/frosty-bouman-yrge3

**Comment by FredyC** [comment]
Thank you for a better example, now it makes more sense :) Would you mind sending in PR to fix that?

**Comment by Kukkimonsuta** [comment]
Sure, I'll see what I can do :)

**Comment by FredyC** [comment]
Merged and published to v2.0.0-alpha.5

**Comment by timothyallan** [comment]
It's still not possible to use `useImperativeHandle` with this update, as even with `forwardRef:true` in observer. Parent components still report ref as being undefined. If I do something like `const ImperativeComponent= observer(forwardRef(myComponent));` and export that, it works. But I think this causes issues with memo inside of observer glancing through the code.

**Comment by jonasalexander** [comment]
Hey, I was unable to get this to work with the changes in the linked PR here and have only been able to get it to work using @Kukkimonsuta's code snippet
```
function genericObserver<
  T extends React.FunctionComponent<P>,
  P extends object = T extends React.FunctionComponent<infer P> ? P : unknown
>(fn: T): T {
  return observer<P>(fn) as T;
}
```
What is the recommended way of having generic observers given the changes @Kukkimonsuta made? Thanks!

See a simple example here: https://stackoverflow.com/questions/63725232/mobx-generic-observer-using-typescript-typing

**Comment by Kukkimonsuta** [comment]
@jonasalexander I have answered your SO question, but for completeness let me put it in here as well:

```tsx
// original
interface GenericProps<T> {
    arg: T;
}
const foo: <T>(props: GenericProps<T>) => T = (props) => props.arg;

// 1. your sample is not react component, you need to match `React.FunctionComponent` interface
const foo_1: <T>(props: GenericProps<T>) => React.ReactElement | null = (props) => <>{JSON.stringify(props.arg)}</>;

// 2. lets add observer (this should work already since TS 3.4 or 3.5)
const foo_2: <T>(props: GenericProps<T>) => React.ReactElement | null = observer((props) => <>{JSON.stringify(props.arg)}</>);

// 3. if on older TS you need to move type declaration to the function itself (note the `extends unknown` 
// which tells compiler this is generic definition and not JSX tag)
const foo_3 = observer(<T extends unknown>(props: GenericProps<T>) => <>{JSON.stringify(props.arg)}</>);
```
