### ISSUE TITLE
Possible memory leak in useObservableEffect

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#25]
Probably not, but I just noticed in test coverage that the disposer is never called.

```ts
    useEffect(
        () => () => {
            if (disposerRef.current) {
                disposerRef.current()
            }
        },
        inputs
    )
```

I tried calling `unmount`, modify the store value again and render counters were the same so, in the essence, it seems to be working. However, the coverage hasn't changed with such test so it never gets called either way it seems.

In theory, it could be caused by the [asynchronous nature of `useEffect`](https://github.com/kentcdodds/react-testing-library/issues/215), but I tried switching it to `useLayoutEffect` which should be synchronous, but nothing has changed.

I am not really sure what might be wrong here and how to test it properly.

@xaviergonz

**Comment by xaviergonz** [comment]
Just added a PR with a test for it
