### ISSUE TITLE
Consider different approach for Concurrent mode disposal

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#250]
https://github.com/facebook/react/issues/15317#issuecomment-573337558

I haven't really looked into it and to be honest, I haven't fully grasped current solution in `next` branch yet.

@RoystonS can you perhaps have a look?
cc @mweststrate

**Comment by RoystonS** [comment]
Yep, was planning to read through that stuff tomorrow.

**Comment by FredyC** [comment]
@RoystonS Did you have some time to think about this?
