### ISSUE TITLE
how can I get the hooks value by React developer Tools

### ISSUE THREAD

**Issue by surahe** [mobxjs/mobx-react-lite#251]
Environment
React: 16.9
mobx-react-lite：1.5.2
React Developer Tools：4.4.0

---------------------------------------------------------------------------------

I use  `useState` in a component but it can't get the value while I create or update the state, it can only return Observer.

How can I get the value while I use hooks and mobx-react-lite?

![image](https://user-images.githubusercontent.com/11918423/73284995-50d19f80-4230-11ea-9cc1-fa0b8dcd7a9d.png)

![image](https://user-images.githubusercontent.com/11918423/73285133-8aa2a600-4230-11ea-8318-ea15efd49505.png)

```
export const TodoAdd: React.FC = observer(() => {
  const [todoVal, setTodoVal] = useState('')
  const todoStore = useTodoStore()

  function handleEnterChange(evt: FormEvent<HTMLInputElement>) {
      setTodoVal(evt.currentTarget.value)
  }
  function handleEnterInput(evt: KeyboardEvent<HTMLInputElement>) {
    if (todoVal === '') {
      return
    }
    if (evt.keyCode === 13) {
      todoStore.addNewTodo(todoVal)
      setTodoVal('')
    }
  }
  return (
    <div>
      <input
        value={todoVal}
        type="text"
        className="add"
        placeholder="Enter to add new todo"
        onChange={handleEnterChange}
        onKeyUp={handleEnterInput}
      />
    </div>
  )
})
```

**Comment by FredyC** [comment]
Try to look under `.track` in there. It's not very nice, that's true, but we are not aware of a better way right now.

**Comment by surahe** [comment]
I get it, thx

![image](https://user-images.githubusercontent.com/11918423/73286405-76f83f00-4232-11ea-9cf6-1a62d2d7b008.png)

![image](https://user-images.githubusercontent.com/11918423/73286459-87a8b500-4232-11ea-9dc1-46802caa6265.png)
