### ISSUE TITLE
Possibility to subscribe for parent context-sotre changes 

### ISSUE THREAD

**Issue by IzaGz** [mobxjs/mobx-react-lite#262]
Hello, ! using mobx-react 6 (mobx-react-lite using functional components, react hooks) i am using context already, and i have parent- context, it may have inside child contexts and child contexts may have other childrens with theirs contexts( each context - i mean context-store) . How is it possible inside nested children OBSERVE for changes in parent contexts-stores? It happened , that i have one common component that is used for wrapping every context needy components .
_

**Comment by FredyC** [comment]
@IzaGz Would mind creating some minimal reproduction of your situation? I am kinda lost in your description.
