### ISSUE TITLE
How do I use mobx-state-lite in my class components?

### ISSUE THREAD

**Issue by tunm1228** [mobxjs/mobx-react-lite#265]
Basic API documentation lives in the `README.md` file. Please, send in PR directly with a change instead of describing what you want to change.

More up to date information can be found at https://mobx-react.js.org/ site so feel free to contribute there.

Ask here only if your change is bigger and there is a chance for rejecting it.

**Comment by FredyC** [comment]
Please use `mobx-react` instead and READ DOCS.
