### ISSUE TITLE
Mutation from async method is not observed in <React.StrictMode>

### ISSUE THREAD

**Issue by g6123** [mobxjs/mobx-react-lite#268]
## Intended outcome

Observer component should get updated when an observable value is changed.

## Actual outcome

The component is not updated.

## How to reproduce the issue

1. Use `<React.StrictMode>`.
2. Implement any store class with an async method that eventually updates state.
3. Call the async method outside React component *or* in `useEffect()` hook.
4. Any mutation made from the async method will be ignored from React observer component.

I have created a minimal example in CodeSandbox:
https://codesandbox.io/s/mobx-react-lite-async-update-not-observed-ipq1q.

## Versions

<img width="273" alt="image" src="https://user-images.githubusercontent.com/3105607/78539925-4e8e5180-782e-11ea-9599-52c8ccf398ed.png">

**Comment by g6123** [comment]
FYI: I've checked that this issue occurs only in <code>mobx-react<b>-lite</b></code>.

**Comment by FredyC** [comment]
Please use `next` for `mobx-react-lite`

**Comment by g6123** [comment]
Thank you for the fast reply @FredyC !
Can I find any related changelog or issue/PRs?

**Comment by FredyC** [comment]
Don't worry about it. I've decided to publish 2.0 today as StrictMode will be more used now due to default inclusion in CRA.

**Comment by g6123** [comment]
That's great. Thx!
