### ISSUE TITLE
Idea: useObservableRef

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-react-lite#27]
Basically the same thing mobx-react does right now with props to make them "observable". It just keeps track of the reference of the object, since anytime the props change then its ref changes, but in a more generic way. Basically the poor mans version of useObservableProps :)

```js
const obsProps = useObservableRef(props);

// since any time the props change the reference changes this is ok
useComputed(() => `${obsProps.firstName} ${obsProps.lastName}`);

function useObservableRef(data: any) {
  const ref = useRef(observable.box(data));
  const update = useCallback(runInAction(() => {
    ref.current.set(data);
  }));

  update();
  return ref.current.get();
}
```

Good things:
- Makes using computed over props easier (no need to inject deps)
- Makes porting current mobx-react codebases easier

Possible issues:

It is compatible with useObserver/Observer, but when using observer it might have double rendering issues since the ref observable would change inside the reaction tracking part.
Possible solutions:
- one reaction per render solves it, but performance might be hurt.
- drop observer?
- warn in the docs strongly about this?
- add an option in observer that does this for you outside the useObserver (at least for props) and send those observable ref props as props object to the base component? (this is actually what mobx-react mostly does actually)

**Comment by FredyC** [comment]
Interesting idea for sure :) Have you actually verified that `props` object reference stays the same even if rerender is caused by eg. `useState`? It seems logical, but better to verify that imo :)

Another good thing is it would work with selectors as well so you can extract deep properties and turn them into observables.

However, the difference with `useObservable` is suddenly very small. It would be basically about the ability to update the underlying value but mostly looking the same. Not sure how to explain such a difference in docs to be understandable enough.

From the docs of [`observable.box`](https://mobx.js.org/refguide/boxed.html) I can see there is also some `{ deep: boolean }` option, but it's unclear if that's a default behavior. If it is then you have your `useObservableProps` I believe :)

The double rerender is bad for sure. Dropping `observer` sounds mostly good, but it would make current code bases much harder to migrate. So more likely it would need to be deprecated and show a one-time warning.

Would be great if we could provide some kind of check that `observer` has been used together with `useObservableRef`, but that mostly what the #7 is about. That's something I would consider semi-bad about hooks in general. They are so encapsulated that they cannot even share some state.

**Comment by xaviergonz** [comment]
> Interesting idea for sure :) Have you actually verified that props object reference stays the same even if rerender is caused by eg. useState? It seems logical, but better to verify that imo :)

It is guaranteed that anytime the props change the props object will be a new one (basically react makes a clone of the props object any time any prop change)
Now if the props object changes when only the state changes, then I'm not sure.

> From the docs of observable.box I can see there is also some { deep: boolean } option, but it's unclear if that's a default behavior. If it is then you have your useObservableProps I believe :)

`observable.box(value, { deep: false })`
I guess using deep true would indeed end up in the useObservableProps behaviour, but with some caveats:
- might be slow turning all the props into observables after any property changes
- reactions related to all properties are triggered whenever any property changes (which is the same that would happen with this, but that's what's happening currently in mobx-react as well)

But either way this is more about users being able to move their mobx-react based components more easily to this one.

> The double rerender is bad for sure. Dropping observer sounds mostly good, but it would make current code bases much harder to migrate. So more likely it would need to be deprecated and show a one-time warning.

Maybe observer could be renamed to "legacyObserver" and mimic as much as possible the current mobx-react way (props are made an observable ref by default, etc) but warn about its caveats?

> Would be great if we could provide some kind of check that observer has been used together with useObservableRef, but that mostly what the #7 is about. That's something I would consider semi-bad about hooks in general. They are so encapsulated that they cannot even share some state.

Yeah, I thought about the same, but I'm not even sure how to pull that off. Maybe this is something that could (maybe is already) be mentioned in the react hooks RFC?

**Comment by FredyC** [comment]
Funny, I just posted a comment in hooks rfc, but your issue is certainly more detailed, thanks :)

**Comment by xaviergonz** [comment]
Ah, feel free to reference it there :)

**Comment by mweststrate** [comment]
Just for inspiration (I'm not entirely convinced we need this, and probably instead should teach users to use the second array argument of `useComputed` property, as that lesson applies neatly to all hooks), 

but having a box in modifier struct mode would probably fix double renders, as it neatly "merges" and doesn't trigger observable changes if there is no structural difference. So it could become like:

```
const observableProps = useObservableProps(props)
```

```javascript
function useObservableProps(props) {
   const baseProps = useMemo(() => observable.box(props, { 
      comparer: comparer.structural // not entirely sure if this is possible in the current mobx api, but it should be :)
   }) , []) // `baseProps will always be the same object`
   baseProps.set(props) // merge new props in the base
   return baseProps.get()
}
```

**Comment by FredyC** [comment]
> Just for inspiration (I'm not entirely convinced we need this, and probably instead should teach users to use the second array argument of `useComputed` property, as that lesson applies neatly to all hooks),

To be honest, it gets rather tedious to specify those dependencies there and also it's rather error-prone and a hard to discover bug imo. You have to constantly think about what's observable and what's not.

Structural comparer sounds like a great feature. I would just avoid naming a whole thing `ObservableProps` as it can be essentially used with any immutable structure if I am not mistaken. Not sure about better name thought to express the idea ... useSyncedObservable? :D

**Comment by xaviergonz** [comment]
If that's possible that's neat! I didn't know a boxed set to structural would do that. That would fix reactions/computeds triggering to properties that didn't really change 

Anyway the double rendering comes from using computed inside a tracked section where the observables those computed observe are changed inside the tracked function. This only happens in observer since the action to change the observables occurs inside the reaction track, where in the other cases it happens outside

Basically what happens in observer is 
```
// memorized part 
const obs = observable.box(props) 
const fullName = computed(() => `${obs.first} ${obs.last} `) 

// render
track() => {
  obs.set(props) // triggers force update because the computed changed (although it is already up to date by the time it is actually used) 
  return fullName.get()
}) 
```
vs useObserver
```
// memorized part 
const obs = observable.box(props)
 const fullName = computed(() => `${obs.first} ${obs.last} `) 

// render
obs.set(props) // doesn't trigger force update (I think) 
track() => {
  return fullName.get()
}) 
```

**Comment by xaviergonz** [comment]
I found a workaround for this which was using a new reaction on each render so it will only care about changes done outside the track function, but I'm not sure how expensive it is to dispose and create a new reaction each time

**Comment by FredyC** [comment]
@xaviergonz So I came to the conclusion that dropping `observer` is not such good idea. For simple UI components, it just feels much tidier to just wrap it into HOC and done. Other two variants make that code slightly less readable and focused on that pure UI.

I would freeze this whole issue for now to avoid unnecessary complexity which nobody is asking for. At this point, I think I agree with Michel.

> Just for inspiration (I'm not entirely convinced we need this, and probably instead should teach users to use the second array argument of `useComputed` property, as that lesson applies neatly to all hooks),

**Comment by xaviergonz** [comment]
Sure, no problem. Still curious about the reaction part though

**Comment by mweststrate** [comment]
@xaviergonz nope, but then again, if a reaction is not tracking anyway, there is no real costs involved anymore in disposing / recreation?

Anyway, I think this one can be closed for onw
