### ISSUE TITLE
New version (2.x) do not work in React Native with hermes js engine

### ISSUE THREAD

**Issue by farwayer** [mobxjs/mobx-react-lite#270]
```js
 ReferenceError: Property 'Reflect' doesn't exist
```

Next hermes version [will support proxies and reflection](https://github.com/facebook/hermes/issues/33#issuecomment-576388658). But current is not. `Reflect` used only once in code: https://github.com/mobxjs/mobx-react-lite/blob/45a58c42bdc4a511d55a512474fd34c4ca3afbcf/src/observer.ts#L91
Can we avoid using it at least until next hermes version will be shipped with React Native?

**Comment by FredyC** [comment]
Given that `Reflect` can be polyfilled I don't think we are going to roll back this change, sorry. The same problem is with IE11 which needs polyfill almost for everything anyway.

**Comment by mweststrate** [comment]
In this very specific case (
https://github.com/mobxjs/mobx-react-lite/blob/ef91cca9d5fbb09ceaca286d2e21e9549cd19801/src/observer.ts#L91)
it seems that condition is not needed anyway, since we are already looping
the `own` properties, so `has` must always return true here?

**Comment by FredyC** [comment]
@mweststrate Hm, `Object.keys` returns own properties only? That's a new thing for me. I suppose it would make sense then given it's the only occurrence.

**Comment by farwayer** [comment]
Yep, `Object.keys` returns keys for object own props only. And in any way you can't check own property with `Reflect.has` because it uses whole prototype chain.

**Comment by FredyC** [comment]
Alright, published 2.0.3 without `Reflect`.
