### ISSUE TITLE
Get warning about batching not configured when it is actually configured

### ISSUE THREAD

**Issue by blacksteed232** [mobxjs/mobx-react-lite#271]
## Intended outcome

I just upgraded to `v2.0.1` and when I tried to follow the guide to import `observer-batching`:
```javascript
import 'mobx-react-lite/batchingForReactDom'
```

## Actual outcome

Get a warning about having not configured Mobx's observer batching

## Research

I did dig in a bit and found out that my app call `observerBatching` in the CJS file but then as it runs, it is calling the `useObserver` method from the ESM file, so the flag that indicates batching has been configured is not set. Please note that I'm running in `development` environment now

## How to reproduce the issue

I'm working on a company project so could not really share code, I would try to find the time to create a sandbox/repo as an example

## Versions

`react@16.13.1`
`react-dom@16.13.1`
`babel@7.9.0`
`typescript@3.8.3`

**Comment by blacksteed232** [comment]
@FredyC I'm not too knowledgeable about module resolution in Typescript, but perhaps, it might be the case that when we do a file import like `import '<some file>'` it tries to use the CJS module? If this is the case, is it better if we export a function from that and then the consumer can call that function to configure batching?

**Comment by FredyC** [comment]
Thank you for this investigation, you are absolutely right. It has nothing to do with TypeScript per-se. These `batching*` files refer to `/dist/index.js` which uses CJS bundles only. In the case of ESM-aware bundler, this is a problem as it will refer to a different variable.

This is tricky, we cannot make a decision in those `batching*` files about the type of bundle used. That leaves us storing the value onto a `global` object (ie `window`). It would be ideal to use `Symbol` to hide it from prying eyes, but that's not supported everywhere.

I will try to come up with some viable approach.

**Comment by FredyC** [comment]
Ok, I think I got it. Please try published 2.0.2 version.

**Comment by blacksteed232** [comment]
@FredyC thank you, I am still waiting for it to show up in our company's NPM space, will let you know asap.
