### ISSUE TITLE
forwardRef reports ref as undefined in TS

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#277]
It's still not possible to use `useImperativeHandle` with this update, as even with `forwardRef:true` in observer. Parent components still report ref as being undefined. If I do something like `const ImperativeComponent= observer(forwardRef(myComponent));` and export that, it works. But I think this causes issues with memo inside of observer glancing through the code.

_Originally posted by @timothyallan in https://github.com/mobxjs/mobx-react-lite/issues/243#issuecomment-615027563_

**Comment by FredyC** [comment]
@timothyallan Can you please set up a reproduction eg. with CodeSandbox?

**Comment by FredyC** [comment]
Could this be fixed be #279?

**Comment by yuwanlin** [comment]
@FredyC 
I also appear this problem with function component.

### part1
for example: 
```
function InfluenceCircle(_props: any, ref: React.RefObject<HTMLDivElement>) {
  return (
    <div ref={ref}></div>
  )
}

export default observer(forwardRef(InfluenceCircle));
```
It  failed. error message like:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

### part2
Also, if I use:
```
export default forwardRef(observer(InfluenceCircle));
```
It also failed. error message like
```
forwardRef requires a render function but received a `memo` component. Instead of forwardRef(memo(...)), use memo(forwardRef(...))
```

**Comment by FredyC** [comment]
@yuwanlin Please read the docs, there is `forwardRef` option you need to use with `observer`.

**Comment by yuwanlin** [comment]
@FredyC 
OK, I am updating when you replied. 
hh, you have a very fast response.

**Comment by yuwanlin** [comment]
@FredyC 
It worked. thank you !
 ```
export default observer(InfluenceCircle, { forwardRef: true });
```
