### ISSUE TITLE
Add decorators and options to useLocalStore and useAsObservableSource to make it frinendly to Devtools

### ISSUE THREAD

**Issue by rainmanhhh** [mobxjs/mobx-react-lite#283]
currently all local observables(wrapped by useAsObservableSource or created by useLocalStore) are anonymous
please add decorators and options to the function args(just like origin mobx observable) so users can set store name(for debug in Devtools)

**Comment by FredyC** [comment]
@rainmanhhh I don't think we are gonna do that, it would only complicate API for a few edge cases. Nobody has asked for it so far. You can easily make your own version of those hooks since they are pretty simple.

I will keep this open for a bit in case more people come up with the same request.

**Comment by FredyC** [comment]
Time to close this, apparently nobody else is intrigued by your idea :)
