### ISSUE TITLE
react-hot-loader with useLocalStore is no work

### ISSUE THREAD

**Issue by ckken** [mobxjs/mobx-react-lite#284]
```javascript
//===> langStore.js
export const langStore = () => {
  return {
    $l: {},
    country: '',//change country is not sync to stores
    async getLang(lang: string) {
      console.log('store:123', lang)//change console is no work in hot loader
      const localeRes = await import(`./lang_assets/${this.lang}.json`)
      this.$l = {localeRes}
    },
  }
}
//===> StoreProvider.js

export const StoreProvider = ({children}) => {
  const Stores = useLocalStore(langStore) //<== can not replace values
 // langStore() values not eq Stores
  return <storeContext.Provider value={Stores}>{children}</storeContext.Provider>
}
```

**Comment by mweststrate** [comment]
We dont support react hot loader. Please use react fast refresh instead.

**Comment by ckken** [comment]
same issue 
```javascript
const {addReactRefresh} = require('customize-cra-react-refresh')
module.exports = {
  webpack: override(
addReactRefresh({disableRefreshCheck: true}),
  )
}
```
no work!

**Comment by FredyC** [comment]
We will need more than your snippets and telling us it doesn't work. Please create minimal reproduction.

**Comment by ckken** [comment]
https://codesandbox.io/live/9rAG3 
here is the code but sanbox not support hot reload?

**Comment by ckken** [comment]
change src/stores.js 
```javascript
    async getLang() {
      console.log("change val here!"); //change here is no work
    }
```

**Comment by FredyC** [comment]
CodeSandbox runs code in production mode. Please make the repo and describe reproduction steps and what you expect to happen exactly.

**Comment by ckken** [comment]
fix it 
if use `customize-cra-react-refresh`  `mobx-react-lite` & router 
index.tsx must in clude 
```javascript
ReactDOM.render(
  <StoreProvider>
    <RouterComp />
  </StoreProvider>,
  document.getElementById('root'),
)
```
otherwise code in hot loader ,but store can not be reload

**Comment by ckken** [comment]
code :https://github.com/ckken/mobx-react-refresh-demo 
StoreProvider in src/index.tsx if store change,page is refresh, 
but it can not hot reload because the store code is not change when hot load
