### ISSUE TITLE
Shouldn't it be useObservable<T>(init: () => T)): T ?

### ISSUE THREAD

**Issue by mcjazzyfunky** [mobxjs/mobx-react-lite#29]
Maybe that sounds a bit like a `useState(initialValue)` vs. `useState(() => initialValue)` discussion, but shouldn't it be `useObservable<T>(init: () => T): T` instead of `useObservable<T>(initialValue: T): T`?
That would also help to handle unobserved data without `useRef`s, wouldn't it?

**Comment by FredyC** [comment]
Not sure. I don't consider a need for lazy initialization in this. In most cases, you would just pass some object there. Do you have some concrete use case where doing it lazily is a must or is it just theoretical hunt for a performance? :)

Either way, considering that it's just a oneliner, it's super easy for anyone to just do the following if such need arises. I don't like increasing complexity for such simple stuff.

```js
const data = useRef(observable(initialValue())).current
```
