### ISSUE TITLE
useObservable hook should have a delay option

### ISSUE THREAD

**Issue by rgranger** [mobxjs/mobx-react-lite#297]
### Summary

The useObservable hook should allow to throttle an update.

The `reaction` from mobx already allows this : https://mobx.js.org/refguide/reaction.html#options

Use case :

I have a currentTime observable value that is updated every second.

I want to show the current time, but only every 5 secondes.

```js
function MyComponent (props) {
  const currentTime = useObservable(() => myStore.currentTime, null, { delay: 5000 })
  const currentDate = useMemo(() => convertTimestampToDate(currentTime), [currentTime])

  return <div>{currentDate}</div>
}
```

### Current behavior

The component renders every second

### Expected behavior

The component should render every 5 seconds

**Comment by rgranger** [comment]
I was able to achieve what i described by doing this :

```js
const [currentTime, setCurrentTime] = useState(myStore.currentTime)
  useEffect(() => {
    const dispose = reaction(
      () => myStore.currentTime,
      (newCurrentTime) => setCurrentTime(newCurrentTime),
      {
        delay: 3000,
      }
    )
    return dispose
  }, [])
```

But i expected this behavior to work directly with the `useObservable` hook.

**Comment by FredyC** [comment]
`useObservable` was deprecated in 1.x and it's gone in 2.x. Make sure to update.

The _successor_ is `useLocalStore` and it doesn't support delay because setting up observables is unrelated to reactions. If you need to delay your reaction, you do that with `useEffect` as you have outlined.

**Comment by rgranger** [comment]
> useObservable was deprecated in 1.x and it's gone in 2.x. Make sure to update.

Ok, my bad then.

I expected a hook that would do like `useSelector` in a redux store : extract data from the store and automatically render the react component on changes.

I don't think there is an equivalent in mobx yet ?

Maybe there could be a generic `useReaction` hook or something alike, that does the useState() and useEffect() internally ?

Or maybe my use case is too marginal to make something generic.

**Comment by mweststrate** [comment]
That is what `observer` already does, only rerender when something that is
used in state changed, so the entire concept of selectors isn't needed in
mobx. See
https://mobx.js.org/refguide/observer-component.html#observer-automatically-tracks-observables-used-during-render
.

A delay option won't be supported because it is a symptom of another
problem; your components are too slow, or your updates to the state
themselves should be batched, rather than creating a situation where the UI
is getting out of sync with the state. Beyond that, throttling render
(which imho is generally a bad idea) can be achieved with utilities like
react-debounce-render and there is no need to solve that in MobX.

**Comment by rgranger** [comment]
Yeah, that's probably true. But there is one major drawback of using the `observer()` HoC : you can easily forget to use it.

Indeed, you can have a hook that uses MobX data, as well as other stuff. That hook is in a separate file for reusability.

```js
function useSomeData () {
    const users = userStore.users
    const protectedData = protectedStore.data
    const someOtherData = useSelector(getDataFromReduxStore) // some other data that comes from somewhere else

    return useMemo(() => users
        .filter((user) => user.isAdmin)
        .map((user) => user.someData + protectedData + someOtherData),
        [users, protectedData, someOtherData]
    )
}

function MyComponent () {
    const data = useSomeData()

    return <div>{data}</div>
}
```

How is the developer supposed to know that MyComponent needs to be wrapped by `observer()` ?

We could use a naming convention for hooks  that uses observable data so that the component that uses a hook named `useSomeDataMobx` (for example) knows it has to be wrapped in `observer`.

But is it really the component responsibility ? Shouldn't it be the hook responsibility instead ?

```js
function useReaction (mobxData) {
  // does the useEffect and useState stuff with `reaction()`
}

function useSomeData () {
    const users = useReaction(userStore.users)
    const protectedData = useReaction(protectedStore.data)
    const someOtherData = useSelector(getDataFromReduxStore) // some other data that comes from somewhere else

    return useMemo(() => users
        .filter((user) => user.isAdmin)
        .map((user) => user.someData + protectedData + someOtherData),
        [users, protectedData, someOtherData]
    )
}
```

I don't know if that's a good idea though. What is your opinion about this ?

**Comment by FredyC** [comment]
If you are accessing observable data in the hook, you can use `useObserver`. It is considered low-level API, but for cases like, it's perfectly fine. Just replace it with your `useMemo`

**Comment by rgranger** [comment]
Ok thanks ! But I though `useObserver` was deprecated ?

**Comment by FredyC** [comment]
useObserv**able** is deprecated :) I know, bit confusing similar names, but it's hard to come up with better ones.

**Comment by rgranger** [comment]
Ah yes ! Actually i was using `useObserver` the whole time. Dunno why i mixed up the names.

So, don't you think `userObserver` could support the same `delay` option as `reaction()` ?

**Comment by FredyC** [comment]
No. As Michel explained above it's a generally bad idea to delay rendering. You can solve it in userland if you desperately need that for whatever reasons (eg. react-debounce-render).
