### ISSUE TITLE
After upgrading to 0.3.3, Module not found: Can't resolve 'mobx-react-lite' in '/components/DropDown'

### ISSUE THREAD

**Issue by Albert-Gao** [mobxjs/mobx-react-lite#30]
After upgdating to `^0.3.3`, the module folder doesn't contain any code, downgrade doesn't help either... :(

![image](https://user-images.githubusercontent.com/18282328/49009517-a4cc9880-f1d5-11e8-9d91-05a891ebc74f.png)

**Comment by FredyC** [comment]
Sorry, my bad, fixed in 0.3.4. Not sure why 0.3.2 would not be working for you, I've been using that version for a couple of days now.

**Comment by Albert-Gao** [comment]
Thanks. :)
