### ISSUE TITLE
useLayoutEffect Warning form mobx-react-lite

### ISSUE THREAD

**Issue by Him-2C** [mobxjs/mobx-react-lite#304]
![image](https://user-images.githubusercontent.com/30730045/91273231-2c7a7900-e7a7-11ea-8b30-afe82de1097f.png)

## Intended outcome

useLayoutEffect warning form mobx-react-lite, please check.
Becuz my project don't use it, it's come when I update package to 2.1.0

## Versions

![image](https://user-images.githubusercontent.com/30730045/91273545-9e52c280-e7a7-11ea-86ed-3ec45f5f9de9.png)

**Comment by FredyC** [comment]
You have to enable SSR mode ... https://mobx-react.js.org/recipes-ssr

**Comment by Him-2C** [comment]
work! thx!
