### ISSUE TITLE
Enzyme expect failure with observer

### ISSUE THREAD

**Issue by adamrobertedwards** [mobxjs/mobx-react-lite#308]
Having a strange issue with Enzyme after migrating `observer` from `mobx-react 5.4.3` to `mobx-react-lite 2.1.0`. I am asserting the length of two separate components (`observer(Component A)` and `observer(Component B)`),  in a test of a parent component, which renders both. The assertion runs and passes as expected with `observer` from `mobx-react`, however is not reporting the correct length after switching to use `observer` from `mobx-react-lite`.

## Intended outcome
The `Received length` for _Component A_ to be `1` and Received length of _Component B_ to be `1`, as both are rendered in the parent.

## Actual outcome

The `Received length` of _Component A_ and _Component B_ are both `2`. Removing either from the parent component's render, results in the `Received length` of both being `1`. 

![image](https://user-images.githubusercontent.com/12909637/91467701-d54cd500-e888-11ea-838e-b7d9431f60f7.png)

## How to reproduce the issue

`import { inject, observer } from 'mobx-react';`
to
```
import { inject } from 'mobx-react';
import { observer } from 'mobx-react-lite';
```

Note: We are in the process of moving to use context instead of `inject` for our stores, but for now have both dependencies.

## Versions
`mobx-react 5.4.3`
`mobx-react-lite 2.1.0`

**Comment by FredyC** [comment]
Please show more code or ideally reproduce the issue with CodeSandbox. I have no idea what is `Received length`.

**Comment by adamrobertedwards** [comment]
> Please show more code or ideally reproduce the issue with CodeSandbox. I have no idea what is `Received length`.

Just heading out, but I'll follow up with some more code later.

**Comment by mweststrate** [comment]
> Just heading out, but I'll follow up with some code later.

Please don't that. It is not that we are bored and crave for vague issue reports ;-). 

Anyway, closing until more info is available (and imho honesty, getting rid of Enzyme saved me so much trouble, whatever the problem, pretty sure that might be a solution)
