### ISSUE TITLE
Attempted import error: 'isObserverBatched' is not exported from 'mobx-react-lite'.

### ISSUE THREAD

**Issue by amariyap** [mobxjs/mobx-react-lite#309]
## Intended outcome

trying to import 2.1.0 and 2.2.0 raising the error ./node_modules/mobx-react/dist/mobxreact.esm.js
Attempted import error: 'isObserverBatched' is not exported from 'mobx-react-lite'.

## Actual outcome

Upgrade from 2.0.7 to 2.1.0 without any breaking change.

## How to reproduce the issue

trying using observable from latest package.

## Versions

2.2.0

**Comment by mweststrate** [comment]
please upgrade mobx-react as well.

**Comment by FredyC** [comment]
This is going to be painful for more people probably if they need both `mobx-react` and `mobx-react-lite`. We should probably keep `isObserverBatched` for a while with deprecation.

**Comment by mweststrate** [comment]
Didn't realise it was an external api. Thought it was only exposed for testing😅

**Comment by michaelaflores** [comment]
FYI this also causes problems if you're not using mobx-react-lite directly and are just consuming mobx-react -- your install may resolve to mobx-react-lite @ 2.1 while you're on mobx-react @ 6.2.2, and receive this error.
