### ISSUE TITLE
NamedExoticComponent cannot be used for observer

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#31]
https://github.com/mobxjs/mobx-react-lite/blob/2f6dca1744cc35fa1d52e37d8d26ad6fdd3c9511/src/observer.ts#L18

Just encountered this. Apparently `ExoticComponent` cannot be used to represent an [actual callable component](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L285). It's useful for `memo`, `lazy` and similar. 

```tsx
export const ContrivedComponent = observer(({ children }) => {
  return React.Children.only(children)
})
```

Since the `ExoticComponent` is lacking `children` attribute, such component cannot be used anywhere where `children` are needed. It's possible to do `observer(({ children }: { children: ReactNode })` but that doesn't feel good at all.

Ideas @xaviergonz?

**Comment by xaviergonz** [comment]
Well that's the actual type returned by the official react memo when used over a callable component (which is what observer uses internally). Anyway I'll take a look just to make sure

**Comment by xaviergonz** [comment]
Hmm, I just tried this against the React 16.8 wip and it compiled ok

```ts
export const ContrivedComponent = observer(({ children }) => {
    React.Children.only(children)
    return null
})
```
however ```return React.Children.only(children)``` won't work, but that's unrelated, it is more about the typing of React.Children.only itself. As a matter of fact this also doesn't work:

```ts
const ContrivedComponent2: React.FunctionComponent<{}> = ({ children }) => {
    return React.Children.only(children)
}
```

but this does
```ts
const ContrivedComponent2: React.FunctionComponent<{}> = ({ children }) => {
    React.Children.only(children)
    return null
}
```

**Comment by xaviergonz** [comment]
Also this works:
```ts
    return <>{children}</>
```
but this doesn't
```ts
  return children;
```
I think it has to do with the fact that ReactNode can be lots of stuff, including strings and the like, but functional components are supposed to return either an element or null

**Comment by xaviergonz** [comment]
Heh, this works even
```ts
export const ContrivedComponent = observer(({ children }) => {
    return <>{React.Children.only(children)}</>
})
```

**Comment by samdenty** [comment]
This isn't working with the latest version of @types/react (16.8.3)

```typescript
const Test = observer(() => <div>test</div>)

const t = () => <Test>test</Test>
//               ^^^^
//               Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes'.ts(2559)
```

**Comment by samdenty** [comment]
Opened a pr here https://github.com/mobxjs/mobx-react-lite/pull/68

**Comment by lukescott** [comment]
I'm having an issue with `React.memo` where I try to include children. Wrapping in `<></>` doesn't work. I get the following error:

`Property 'children' does not exist on type 'IntrinsicAttributes & ...`

I'm assuming this is related?

I was able to fix it by changing:

```ts
interface ExoticComponent<P = {}> {
  /**
   * **NOTE**: Exotic components are not callable.
   */
  (props: P): (ReactElement|null);
  readonly $$typeof: symbol;
}
```
to:
```ts
interface ExoticComponent<P = {}> {
  /**
   * **NOTE**: Exotic components are not callable.
   */
  (props: PropsWithChildren<P>): (ReactElement|null);
  readonly $$typeof: symbol;
}
```
(Added `PropsWithChildren`)

Any problem with that?

This is unrelated to having to change `return primative` to `return <>{primative}</>`. That has to do with https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18912. With that issue `FunctionComponent` (or SFC) requires `ReactElement<any> | null` as a return instead of `ReactNode`.

**Comment by FredyC** [comment]
@lukescott If anything, that change has to go to DefinitelyTyped, we cannot change React types here :) But yea, it seems one of those long term issues that TypeScript itself has.

**Comment by lukescott** [comment]
Whoops. Yeah, this was the first Google result for `NamedExoticComponent`. Still relevant to your issue in a way I guess? For sure needs to be fixed at DefinitelyTyped.

**Comment by maxdeviant** [comment]
It looks like #68 should fix this with the latest `@types/react`.
