### ISSUE TITLE
Batching doesn't work with webpack in production mode in 2.2.0

### ISSUE THREAD

**Issue by vkrol** [mobxjs/mobx-react-lite#312]
## Intended outcome
Working batching.

## Actual outcome
Batching doesn't work.

## How to reproduce the issue
Try to build an application via webpack in production mode.
Minimal reproducible example: https://github.com/vkrol/mobx-react-lite-2.2.0-batching-bug (I don't know how to show this behavior in CodeSandbox). I used `patch-package` to insert `console.log` statement in `observerBatching` module, so I can check that the bundle contains this module.

I think that the problem is in the wrong `sideEffects` section in `package.json` https://github.com/mobxjs/mobx-react-lite/blob/master/package.json#L12-L14. If I remove this setting, everything works fine. I think, that we need to remove this setting completely. I can create a PR if you agree with this solution.

## Versions
`mobx-react-lite@2.2.0`.

**Comment by FredyC** [comment]
Well, the change is that the actual side effect is now happening inside the `index.ts`, so the current configuration for `sideEffects` is outdated imo. Can you try if you add an exception for `index.ts` instead?

**Comment by vkrol** [comment]
The following configuration works:
```
"sideEffects": [
  "es/index.js"
],
```

**Comment by FredyC** [comment]
Ok, I think it would be best to move this side effect to a different file and let `index.ts` as "export only" source. I think it could be inside the `observerBatching.ts`.

**Comment by mweststrate** [comment]
Fixed in 2.2.2 I think. If it somehow doesn't work a more thought through PR is welcome.
