### ISSUE TITLE
Ant-Design Table not rendering when change state in mobx store

### ISSUE THREAD

**Issue by FreeClimb** [mobxjs/mobx-react-lite#315]
I support the idea of observables since the knockout and mvvm template.
Аnd now in a large project I tried to use mobx-react-lite with Ant Design widgets. 

I enter new data or change in a modal window
then after pressing the save button
data is added to the storage (as seen from the console log)
but it does not render the table
I tried changing useObservable to observable, but the problem persists. 

my examples on codesandbox:

[option using 2.2.0 version](https://codesandbox.io/s/adoring-gates-9mgpc)
[and option with 3.0.0-rc ](https://codesandbox.io/s/frosty-sid-jvg3w)

I would appreciate any help.
thank

**Comment by mweststrate** [comment]
`Table` isn't an observer based component, so you shouldn't be passing it observables directly. See https://deploy-preview-2327--mobx-docs.netlify.app/react/react-integration.html#dont-pass-observables-into-components-that-arent-observer for what you can do in those cases

**Comment by FreeClimb** [comment]
Thank you for your sooner answer,
I'm new on mobix and I don't understand that you mean 'observer based component' 
How can wrap Ant Design Table for implement observer?
Did you see my second example on codesandbox with observer?
Possibly I need to use jsx-style in Ant Design Table or <Observer> in Column's method:

[Ant design Table jsx style](https://ant.design/components/table/#components-table-demo-jsx)

**Comment by mweststrate** [comment]
No, I mean that you shouldn't be passing observables to the ant.design
Table, but plain objects instead, by using wallets.slice() or
`toJS(wallets)`, see
https://deploy-preview-2327--mobx-docs.netlify.app/refguide/observable.html#converting-observables-back-to-vanilla-javascript-collections

Please do read the documentation first if you are new to MobX, or follow
for example the egghead tutorial. There is little point in opening issues
if you didn't get deep enough into the docs to be familiar with the term
"observer based component"

**Comment by FreeClimb** [comment]
In examples from documentation, not only class TodoList, but every instance of class Todo is observable.
Maybe I should make each instance of the wallet wrap observable and then make their collection wallets (array) observable

`import { makeObservable, observable, computed, action } from "mobx";

class Wallet {
  // observables
  id;
  name;
  type;

  constructor(id, name, type) {
    makeObservable(this, {
      // observables
      id: observable,
      name: observable,
      type: observable,
      // calculated
      typeName: computed,
      // actions
      setId: action,
      setName: action,
      setType: action
    });

    this.id = id;
    this.name = name;
    this.type = type;
  }

  // calculated
  get typeName() {
    return this.type === "1" ? "Currency" : "Fuel";
  }

  // actions
  setId = (id) => (this.id = id);
  setName = (name) => (this.name = name);
  setType = (type) => (this.type = type);
}

export default Wallet;
`

**Comment by FreeClimb** [comment]
it looks like the problem is not that the state is not updated in the store. The problem is that updating the state does not send a notification to update the table component. Maybe I need to use makeObservable(this.wallets) and then in async method putWallet:
            `runInAction(() => {
                this.wallets = data;
                this.isLoading = false;
            })`

**Comment by mweststrate** [comment]
@FreeClimb your validation was failing and eating all exceptions, so the sandbox failed in a bunch of different ways. Next time please provide a _minimal_ reproduction. 

Using `<Observer>` in the row rendering in combination with `.slice()` to the datasource did indeed fix the problem ([link](https://codesandbox.io/s/little-grass-0j9k9?file=/src/WalletTable.js:1502-1505)). It still behaves weird but that is because the keys arent organized, so you will need to fix that as well. 

Fur future readers see https://mobx.js.org/react-integration.html#dont-pass-observables-into-components-that-arent-observer for more details
