### ISSUE TITLE
Attempted import error: 'observerBatchingOptOut' is not exported from 'mobx-react-lite'.

### ISSUE THREAD

**Issue by michaelaflores** [mobxjs/mobx-react-lite#316]
## Intended outcome

Upgrading from mobx-react-lite 2.0.0 to 2.2.1 does not introduce breaking changes.

## Actual outcome

Upgrading causes this build issue to appear, in my use case when using mobx-react @ 6.3.0 but I'm sure for others using mobx-react-lite directly as well.

## How to reproduce the issue

I don't have a repro on hand but this is the same issue as #309.

## Versions

2.2.1

**Comment by mweststrate** [comment]
I'll try to publish a fix next weekend. Bumping mobx-react should fix it
though

**Comment by michaelaflores** [comment]
@mweststrate we are seeing this issue with the latest mobx-react currently. It attempts to import this. Or are you just pointing out that we'll be able to fix it by bumping mobx-react after your fix?

**Comment by mweststrate** [comment]
The min dep version of mobx-react-lite in mobx-react should be high enough
(sorry, cant check atm). If it is already, it is a problem in your package
manager/ lacking lock files or you arent on latest mobx-react yet

**Comment by michaelaflores** [comment]
@mweststrate from what I'm gathering after looking into this more, it's true that #309 should no longer be seen when installing mobx-react @ 6.3 as it will pick up mobx-react-lite's recent fix, and this has indeed been the case. It's also true that mobx-react @ 6.3 [does not include a reference](https://unpkg.com/browse/mobx-react@6.3.0/dist/mobxreact.esm.js) to `observerBatchingOptOut` , suggesting a local problem then. 😄 

Separately, I think this issue might still be valid for folks that are using mobx-react-lite directly and using this export, but I admit this isn't my use case so can't speak to it.

**Comment by FredyC** [comment]
> Separately, I think this issue might still be valid for folks that are using mobx-react-lite directly and using this export, but I admit this isn't my use case so can't speak to it.

That export was never documented as a public API, it was exported for `mobx-react` use only. So if anyone used it, it was their own risk.
