### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by a14m** [mobxjs/mobx-react-lite#317]
After updating `mobx-react-lite` from `2.0.7` to any newer version, I started getting the following warning message when ever I use `next dev` command:
```
Warning: useLayoutEffect does nothing on the server,
because its effect cannot be encoded into the server renderer's output format.
This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. 
To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. 
See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

## How to reproduce the issue
I've created the minimal codesandbox to reproduce the issue (you can see the error when you refresh the browser there)
here: https://codesandbox.io/s/mobx-error-3vbr3
<img width="860" alt="image" src="https://user-images.githubusercontent.com/347712/92235089-6f2d0700-eeb3-11ea-9e02-5f93c6b98b37.png">

## Versions
```
    "mobx": "^5.15.4",
    "mobx-react-lite": "^2.0.7",
    "next": "^9.5.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
```
downgrading mobx-react-lite to `2.0.7` solves the issue.

**Comment by a14m** [comment]
there is also an interesting behavior, when changing `_app.js` 
from `export default observer(MyApp);` to `export default MyApp;` the issue disappears too, but I'm not sure if it has side effects.

**Comment by mweststrate** [comment]
Please enable server side rendering support, see the readme

**Comment by a14m** [comment]
sorry I forgot to add the codesandsbox link: https://codesandbox.io/s/mobx-error-3vbr3

**Comment by stfenjobs** [comment]
me too ,  i got 

`Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.`

**Comment by stfenjobs** [comment]
i fixed it;

https://mobx-react.js.org/recipes-ssr

**Comment by a14m** [comment]
@stfenjobs where exactly did you add this to nextjs? and are you sure that it only gets called once? (as per the documentation)
> You should call it only once at the root of your server side code.

**Comment by FredyC** [comment]
It doesn't really matter how many times you call it. Ultimately, it just sets one boolean that basically blocks the observer from doing anything. Important part is to do it as soon as possible in the app before any observers used.

**Comment by stfenjobs** [comment]
@a14m 

i add to  store/index.tsx , only once

![image](https://user-images.githubusercontent.com/6580897/92366335-9724a080-f127-11ea-8e6a-d0e553650382.png)
