### ISSUE TITLE
Attempted import error: 'makeObservable' is not exported from 'mobx'.

### ISSUE THREAD

**Issue by roygold7** [mobxjs/mobx-react-lite#319]
## Intended outcome
I'm trying to import Observer and useObserver to my App.tsx in a create-react-app project like so:
`import { Observer, useObserver } from "mobx-react-lite";`

## Actual outcome
When importing Observer or useObserver from mobx-react-lite, an error is thrown because the library is trying to import makeObservable from mobx in the file assertEnvironment.ts. The problem is that it is not exported from mobx.

When adding this:
`import { Observer, useObserver } from "mobx-react-lite";`
to a file, the following error is thrown:
```
./node_modules/mobx-react-lite/es/utils/assertEnvironment.js
Attempted import error: 'makeObservable' is not exported from 'mobx'.
```

Then when I look in `./node_modules/mobx-react-lite/es/utils/assertEnvironment.js`, I see this: 
```
import { makeObservable } from "mobx";
import { useState } from "react";
if (!useState) {
    throw new Error("mobx-react-lite requires React with Hooks support");
}
if (!makeObservable) {
    throw new Error("mobx-react-lite@3 requires mobx at least version 6 to be available");
}
```

## How to reproduce the issue
Add `import { Observer, useObserver } from "mobx-react-lite";`
to the the App.tsx in a create-react-app project.

The only solution I found was to comment out parts of assertEnvironment.js:
```
// import { makeObservable } from "mobx";
import { useState } from "react";
if (!useState) {
    throw new Error("mobx-react-lite requires React with Hooks support");
}
// if (!makeObservable) {
//     throw new Error("mobx-react-lite@3 requires mobx at least version 6 to be available");
// }
```
## Versions

    "mobx": "5.15.7",
    "mobx-react": "6.3.0",
    "mobx-react-lite": "3.0.0"

**Comment by roygold7** [comment]
The only solution I found was to comment out parts of assertEnvironment.js:
```
// import { makeObservable } from "mobx";
import { useState } from "react";
if (!useState) {
    throw new Error("mobx-react-lite requires React with Hooks support");
}
// if (!makeObservable) {
//     throw new Error("mobx-react-lite@3 requires mobx at least version 6 to be available");
// }
```

**Comment by FredyC** [comment]
Please either use mobx 6.x or mobx-react-lite 2.x. Your combination is incompatible.

**Comment by roygold7** [comment]
> Please either use mobx 6.x or mobx-react-lite 2.x. Your combination is incompatible.

Okay but the error needs to be thrown then, instead of the compiler just saying that the import can't be found. The code never reaches this part:
```
if (!makeObservable) {
     throw new Error("mobx-react-lite@3 requires mobx at least version 6 to be available");
 }
```
which is what should happen.

**Comment by FredyC** [comment]
You are right it's not ideal. In theory, we could use dynamic `import()` instead. It gets transformed to `require` in CJS, so it should be safe. We are open to PR to fix that.

**Comment by mweststrate** [comment]
You get an error at build time, rather at runtime. That sounds like a
benefit to me, not a downside. Although the error itself is more vague,
googling it will now show up this issue so people should still be able to
figure it out :).

**Comment by mweststrate** [comment]
Closing for now, this is supposed to fail. So I don't think there is much point in complicating stuff by making it fail differently.

**Comment by CDoughty08** [comment]
@mweststrate Would it be reasonable to release a patched `mobx-react` i.e. 6.3.1 that does not list `"mobx-react-lite": ">=2.2.0"`. to prevent installing an incompatible version.

**Comment by mweststrate** [comment]
That has been released 2 weeks ago already
