### ISSUE TITLE
v2.x Docs Deprecation

### ISSUE THREAD

**Issue by mattboldt** [mobxjs/mobx-react-lite#324]
Hello! Looking forward to trying out Mobx6 and the latest mobx-react-lite 3. Thank you for all your hard work.

In the meantime, our projects are still using mobx-react-lite v2 and below, and the docs are no longer available as linked from the v2 readme: https://github.com/mobxjs/mobx-react-lite/tree/v2.0.5
Example: https://mobx-react.js.org/state-local

I see in the [mobx announcement](https://michel.codes/blogs/mobx6) the docs were updated and deprecated:
> we've updated all React related documentation to use function components instead of class components. And added documentation on how to use MobX with hooks, context and effects.
> [...] the separate mobx-react.js.org/ website has been deprecated. 

I understand the decision to clean up the docs and make things more accessible and consistent, but the new docs are lacking any info about v2 and before. 

## Intended outcome
Legacy docs should be available _somewhere_.

## Actual outcome
Legacy docs are gone.

**Comment by FredyC** [comment]
If you need an API, the README is still valid except for a few deprecations. And for patterns, everything valid is explained in https://mobx.js.org/react-integration.html. What specifically do you need from the old docs?

**Comment by ZavierTang** [comment]
You may be able to check it out here: https://github.com/mobxjs/mobx-react-docz/tree/renovate/docz-2.x

**Comment by FredyC** [comment]
I've revived the http://mobx-react.js.org/ for now with deprecation notice instead of a hard redirect.
