### ISSUE TITLE
Include runnable example in source code?

### ISSUE THREAD

**Issue by larrymyers** [mobxjs/mobx-react-lite#33]
I've managed to successfully migrate a mobx v5  and mobx-react project over to mobx-react-lite, and was pleasantly surprisedly how relatively easy it was.

That being said, I can see the process being daunting for people that aren't as familiar with functional composition, use of context, etc.

@FredyC is there any desire to have a runnable example project? If so, I will happily volunteer to create something that can serve as way to complement the existing documentation in the readme.

**Comment by FredyC** [comment]
@larrymyers Thanks for the offer, there is never enough examples :) I thought that those CodeSandbox ones would be enough, apparently not :)

**Comment by larrymyers** [comment]
@FredyC The code examples are really useful in the docs. I've found that having a complete application helps a lot of people by showing how the wiring all fits together.

I'm just happy this project exists, it solves my major pain point with mobx-react, which was having typesafe inject.

I'll start putting something together and submit a PR.

**Comment by FredyC** [comment]
> I'm just happy this project exists, it solves my major pain point with mobx-react, which was having typesafe inject.

Funny, this package actually does not solve that because it does not include any `inject` :D I've been using React Context with MobX since React 16.3, it wasn't really necessary to wait for anything.
