### ISSUE TITLE
HOC inject example

### ISSUE THREAD

**Issue by ross-weir** [mobxjs/mobx-react-lite#36]
Hi all.

I've been trying to find a way to create an `inject` helper function like in the README:

```
function inject(useSelector, baseComponent) {
    const store = useContext(StoreContext)
    const selected = useSelector(store)
    // optional memo essentially making a pure component
    return  baseComponent({ ...selected })
}
```

React throws a `Hooks can only be called inside the body of a function component.` error. I'm a bit of a noobie but haven't been able to find a way around this. It seems we may have to just use `useContext` and then a selector in the components themselves.

Can I please get your thoughts on this? Is my conclusion correct? Thanks :)

**Comment by FredyC** [comment]
Well, as I said, I've never tried that example, so I guess it's good thing you brought it up. How are you using such HOC? Note that it requires selector as a first argument and component in second, so it should be something like following, but mostly shooting blinds here as I am not convinced it's a good thing to do in general.

```jsx
const userSelector = createSelector(({ user }) => ({
    name: user.name,
    age: user.age
}))

function UiComponent({ name, age }) {
    return (
        <div>
            <div>Name: {name}</div>
            <div>Age: {age}</div>
        </div>
    )
}

export default inject(userSelector, UiComponent)
```

**Comment by ross-weir** [comment]
Thanks for the reply. 

Yeah that's essentially what I was trying, seems that it's a no-go. [I've read the discussion on a `useInject` hook](https://github.com/mobxjs/mobx-react-lite/issues/6), does this discussion capture your thoughts on the subject? Just using the `useContext` hook as required in components?

**Comment by FredyC** [comment]
I am not sure why it wouldn't be working. If you would prepare a reproduction repo or better a sandbox I might look at it. You can use my [template codesandbox](https://codesandbox.io/s/1921w0on7) for an easy start.

**Comment by ross-weir** [comment]
Sure thing. [Here you go](https://codesandbox.io/s/5z476y1j8k)

**Comment by FredyC** [comment]
Alright, I made it work... https://codesandbox.io/s/rlv06114op

There were a few mistakes. 
 * Do not call it `useInject` as it's not a hook (not that it would be causing any error)
 * The HOC always have to return a wrapped component, not a result of rendering
 * You need to actually render injected component, not return it

I would appreciate if you could fix the example in the README and send in the PR.

**Comment by ross-weir** [comment]
Got it. Thanks a lot for your time and the explanation.

**Comment by luisherranz** [comment]
I've created a slightly more advanced `inject` with `observer` and `ownProps`, just like the original (`mapperFunction: (stores, ownProps) => additionalProps`).


https://codesandbox.io/s/qx18xrrvmq

```js
const inject = (selector, baseComponent) =>
  React.memo(
    observer(ownProps => {
      const store = React.useContext(storeContext);
      const newProps = selector({ store, ownProps });
      return baseComponent(newProps);
    })
  );
```

**Comment by FredyC** [comment]
@luisherranz Not that I would use that personally, but you can improve it a more with `useObserver` instead. That way the observer won't be visible in debugger tree. One less nesting is always good :)

```js
const inject = (selector, baseComponent) =>
  React.memo(
    (ownProps => {
      const store = React.useContext(storeContext);
      return useObserver(() => baseComponent(selector({ store, ownProps })));
    })
  );
```

**Comment by luisherranz** [comment]
Codesandbox modified 👍 

It would be perfect if we could change the component name. Right now is memo:

![screen shot 2018-12-10 at 14 04 10](https://user-images.githubusercontent.com/3305402/49734413-7abeb000-fc84-11e8-8d20-746c7f631163.png)

**Comment by FredyC** [comment]
@luisherranz Nothing changes in that matter, you can just attach `displayName` on the component AFAIK.

**Comment by larrymyers** [comment]
Using React.memo with a component that includes the useContext hook seems really dangerous.

From: https://reactjs.org/docs/react-api.html#reactmemo

> If your function component renders the same result given the same props, you can wrap it in a call to React.memo for a performance boost in some cases by memoizing the result. This means that React will skip rendering the component, and reuse the last rendered result.

By including context inside a functional component wrapped with React.memo, you're implying that there's a very good chance that the component will **not** render the same result given the same props.

**Comment by luisherranz** [comment]
> By including context inside a functional component wrapped with React.memo, you're implying that there's a very good chance that the component will not render the same result given the same props.

What's your suggestion then?

> Nothing changes in that matter, you can just attach displayName on the component AFAIK.

How do you get the original component name?

**Comment by larrymyers** [comment]
@luisherranz This should work just fine:

```tsx
const inject = (selector, baseComponent) =>
    (ownProps) => {
        const store = React.useContext(storeContext);
        return useObserver(() => baseComponent(selector({ store, ownProps })));
    }

const MyInjectedComponent = inject(
    (store, ownProps) => {foo: store.computedFoo, ...ownProps},
    MyComponent
);
```

You certainly can include React.memo, just make sure it only wraps the baseComponent. That way the properties are already created.  You really only want to pass `f(x) = y` (i.e. pure functions) to React.memo, because if `f(x) = z` in some cases, then React.memo would still only return `y` if it was computed first for a given `x`.

**Comment by FredyC** [comment]
> How do you get the original component name?

Um, `baseComponent.displayName || baseComponent.name` ? :) Basics of creating HOC haven't changed with hooks or mobx in a bit :)

**Comment by luisherranz** [comment]
Ok, this seems to work fine:

```js
const inject = (selector, baseComponent) => {
  const component = ownProps => {
    const store = useContext(storeContext);
    return useObserver(() => baseComponent(selector({ store, ownProps })));
  };
  component.displayName = baseComponent.name;
  return component;
};
```

https://codesandbox.io/s/qx18xrrvmq

![screen shot 2018-12-11 at 08 08 43](https://user-images.githubusercontent.com/3305402/49783965-ffa8d880-fd1b-11e8-9f37-bd376e22fa5c.png)

----

Any idea how to add React.memo to the `baseComponent`? Is it really needed or is it better to avoid it?

I thought the original `inject` implementation worked like that but I don't see it anymore. Maybe I was wrong.

**Comment by FredyC** [comment]
@luisherranz Memo is just an optimization so unless you feel like it's slowing down your app, I wouldn't be using it. As @larrymyers noted, you can end up with unexpected result of something not rerendering when you expect it.

**Comment by luisherranz** [comment]
Ok, then it seems great as it is. Even better than the original `inject` as it doesn't create a new component in your tree :)

**Comment by luisherranz** [comment]
I have improved the sandbox: 

https://codesandbox.io/s/qx18xrrvmq

Now `inject` has a `setStore` function, doesn't need a React context and works like a HOC, but doesn't add the extra component.

### This is the code:

```js
let store = null;

export const setStore = newStore => {
  store = newStore;
};

const inject = selector => baseComponent => {
  const component = ownProps => {
    if (store === null)
      throw new Error('Please, use setStore before your ReactDOM.render call');
    return useObserver(() =>
      baseComponent({ ...ownProps, ...selector(store, ownProps) })
    );
  };
  component.displayName = baseComponent.name;
  return component;
};

export default inject;
```

### These are the instructions:

Before your `ReactDOM.render` you need to set your store using `setStore`:

```js
import store from './store';
import { setStore } from './mobx-react-inject';

setStore(store);

ReactDOM.render(<App />, document.getElementById('root'));
```

Then, just use `inject` in any component:

```js
import inject from '../mobx-react-inject';

const NameDisplayer = ({ name }) => <h1>{name}</h1>

const InjectedNameDisplayer = inject(store => ({
    name: store.user.name
}))(NameDisplayer)
```

`inject` works like the old mobx-react inject (https://github.com/mobxjs/mobx-react#customizing-inject) with the custom mapper:

```js
mapperFunction: (store, ownProps) => additionalProps
```

with the only difference that it doesn't add an extra component to your React tree.

----

I think it's pretty neat. It allows you to:
- Keep your components absolutely dumb. They only receive final props and just have to render.
- Avoid the use of `observer(MyComponent)` everywhere. 
- Use named exports to unit test your dumb components, like this:
```js
 // Named export for unit testing
export const NameDisplayer = ({ name }) => <h1>{name}</h1>

 // Default export to use in the app
export default inject(store => ({
    name: store.user.name
}))(NameDisplayer)
```
- You can also use `setStore` to test your not-so-dumb injected components with a mocked store.
- Keep your React tree clean. No more `injected-MyComponent`. The above example would look like this even though `NameDisplayer` is receiving `name` from `store.user.name`:
```html
<App>
  <NameDisplayer />
</App>
```
- If this ends up in a npm package, you avoid the need to import your store locally, which sometimes is a mess when you are in a deep nested folder and makes moving files around painful.
```js
import inject from 'mobx-react-inject'
// vs
import store from '../../../../store'
```
---- 

I'm reopening the issue to discuss precisely that:
- Do you think this is worth its own npm package? And if so:
  - Does it make sense to include it in this package?
  - Or it's best to create a new package, like for example `mobx-react-inject`?

cc: @mweststrate

**Comment by FredyC** [comment]
Well, I am not a big fan of scoped variables that are essentially global. React context gives a great benefit that any part of the tree can override any parent level context value, but I guess it's not that essential in this case. Although, it should definitely warn if you try to call `setStore` multiple times.

Another big reason why I would not use this is TypeScript. It was a huge pain to get a [correct typing with original inject](https://github.com/mobxjs/mobx-react/issues/256) and it's going to be mildly annoying with this as well because a scoped variable is untyped and for every use of `inject` you have to provide the type all over again.

For this reason, mainly, I don't think it fits into this package as it's a full TypeScript and needs to have good type safety. Feel free to make your own package.

**Comment by luisherranz** [comment]
> I guess it's not that essential in this case

Yes, React context doesn't make much sense here. It could be used though.

> Another big reason why I would not use this is TypeScript. 

We do not use TypeScript so I can't provide a typesafe implementation. I guess we'll have to use our own package then.

**Comment by geakstr** [comment]
Maybe someone come in handy this typescript version of the HOC.

Utility function:
```typescript
import { useObserver } from "mobx-react-lite";
import * as React from "react";

export function createPlug<T>(context: React.Context<T>) {
  return <OwnProps, SelectorOutput>(
    selector: (store: T, ownProps: OwnProps) => SelectorOutput
  ) => {
    return (
      BaseComponent: React.SFC<OwnProps & SelectorOutput>
    ): React.SFC<OwnProps> => {
      const Component: React.SFC<OwnProps> = ownProps => {
        return useObserver(() => {
          return BaseComponent({
            ...ownProps,
            ...selector(React.useContext(context), ownProps)
          });
        });
      };
      Component.displayName = BaseComponent.name;
      return Component;
    };
  };
}
```

Create `plug` function instance:
```typescript
export const plug = createPlug(React.createContext(store));
```

Usage example:
```typescript
const ListItem = plug((store, ownProps: { id: string }) => ({
  openDoc: store.view.openDoc,
  isActive: store.view.docId === ownProps.id
}))(props => (
  <li>
    <button disabled={props.isActive} onClick={() => props.openDoc(props.id)}>
      {props.id}
    </button>
  </li>
));
```

**Comment by geakstr** [comment]
Also I've implemented typescript type to extract props type which will be injected to component. It can be useful when you want to split and use hoc and component separately. It's better to look at an example:

```typescript
const HOC = plug((store, ownProps: { foo: number }) => ({
  items: store.items
}));

type HOCProps = PluggedProps<typeof HOC>; // -> { items: some[], foo: number };

const Component: React.SFC<HOCProps> = props => {
  return items.map(item => <div key={item.id}>{item.title}</div>);
};

// ...
// At the same file where `createPlug` placed
export type PluggedProps<
  T extends ReturnType<ReturnType<typeof createPlug>>
> = ComponentProps<PropsArg<T>>;

type PropsArg<T> = T extends (arg1: infer U, ...args: any[]) => any ? U : any;
type ComponentProps<T> = T extends React.SFC<infer X> ? X : null;
```

I imagine it would be cool to have it built in to `mobx-react-lite`. @FredyC what do you think?

**Comment by FredyC** [comment]
@geakstr Well, since the package does not export any sort of `inject` (I like your plug, btw), I don't see how it would fit here. The package is not meant like "garbage heap" really 😉

**Comment by geakstr** [comment]
@FredyC I named `plug` not `inject` because it does `observer` (your `useObserver` actually) internally, so `inject` may introduce confusion with `inject` from mobx-react. I didn't get your "garbage heap" statement. `mobx-react-lite` doesn't provide any analogue of `inject` from mobx-react. Functions from `mobx-react-lite` are great, but there is no way to pick pieces of state and inject them to component, without injecting store entirely.

**Comment by FredyC** [comment]
> mobx-react-lite doesn't provide any analogue of `inject` from mobx-react

That's exactly right :) Have you read the discussion in https://github.com/mobxjs/mobx-react-lite/issues/6? Also readme has [a basic reasoning](https://github.com/mobxjs/mobx-react-lite#why-no-providerinject) about it.

**Comment by FredyC** [comment]
Besides, the work on mobx-react V6 has started and there will be Provider/inject updated to use Context API. You might as well contribute your typing there.

**Comment by erasmo-marin** [comment]
I did this on an example app and works well for me, what do you think, instead a HOC I wrote a hook.

```javascript
import { useContext } from "react";
import * as stores from "../stores";
import forEach from "lodash/forEach";

const useStores = (selector) => {
	let selected = {};
	forEach(selector, storeKey => {
		storeKey = storeKey + "Store";
		if(stores[storeKey]) {
			selected[storeKey] = useContext(stores[storeKey]);
		}
	});
	return selected;
}

export default useStores;
```

Then in your component use it like this:

```javascript
const Component = observer((props) => {

	const { dataStore } = useStores(["data"]);

	/*load data*/
	useEffect(() => {
		dataStore.loadData();
	}, []);
	return <p>{ JSON.stringify(dataStore.data) }</p>
});
```

**Comment by FredyC** [comment]
Well, you are kinda breaking the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) there by running `useContext` in the loop. In this case, it's not such a problem because it's a stateless hook (only reading something), but I would advise avoiding that just for your own sake.

Honestly, I don't follow why do you think that accessing by a string value is better (typo prone), but it's your choice.

And I would personally, do this so you don't need to specify that array for each `useStores` call.

```js
const useStores = (...selectors) => {
  ...
}
const { dataStore } = useStores("data");
```

**Comment by erasmo-marin** [comment]
@FredyC you are right, it's a source of bugs, I'm deleting my comment to prevent any one to use it. But in my case, I usually need to import more than one store in one component, so importing every store I need is  tedious. Is not that I like to use strings, but just using the inject hoc approach in mobx-react.
