### ISSUE TITLE
'lite' depends on full mobx?

### ISSUE THREAD

**Issue by babakness** [mobxjs/mobx-react-lite#40]
Hi, I might be misunderstanding the full intention here--this package has the moniker "lite" and it depends on the full mobx package. By "lite" does it mean a smaller subset adapted for React Hooks *and* at a much smaller bundle size or just the former without the (necessarily) latter?

**Comment by mweststrate** [comment]
It is a lite version of `mobx-react`, not a lite version of `mobx`

**Comment by babakness** [comment]
Got, it. Thanks.
