### ISSUE TITLE
Add example or test case for mixing with vanilla useState

### ISSUE THREAD

**Issue by yoDon** [mobxjs/mobx-react-lite#41]
It's often valuable during refactoring of code to be able to shift from one state management approach to another. It would be great to be able to have both useState and mobx in the same component to allow gradual refactoring in one direction or the other.

**Comment by FredyC** [comment]
I am not sure what you would like to see in such example. You can mix both approaches just fine, they don't collide with each other in any way.

**Comment by yoDon** [comment]
My guess was they should work together, I just figured it would be worth adding a test case just to make sure they continue to work together as the project evolves. If you think its sufficiently inherent in the implementation future that no test is needed it's certainly fine to close the issue.

**Comment by FredyC** [comment]
Feel free to submit a PR with a test case :) Thanks for your input.
