### ISSUE TITLE
"mobx-react-lite requires React 16.7 to be available" actually requires alpha.0

### ISSUE THREAD

**Issue by jtreminio** [mobxjs/mobx-react-lite#42]
Your current `peerDependencies` is tied to the alpha release of React 16.7:

https://github.com/mobxjs/mobx-react-lite/blob/master/package.json#L33

```
"peerDependencies": {
    "mobx": "^4.0.0 || ^5.0.0",
    "react": "^16.7.0-alpha.0"
  },
```

React had stable 16.7.0 release 19 days ago: https://github.com/facebook/react/releases/tag/v16.7.0

**Comment by luisherranz** [comment]
React 16.7.0 doesn't include hooks yet:
https://reactjs.org/blog/2018/12/19/react-v-16-7.html

**Comment by jtreminio** [comment]
@luisherranz Thanks!
