### ISSUE TITLE
displayName is set after observer, observer could use a proxy to fetch it

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-react-lite#44]
Since we write it as:

```ts
const Item = observer(() => <div />)
Item.displayName = 'Item'
```

It won't pick up the displayName. Perhaps observer could use a proxy to pick that up:

```ts
function observer(a) {
  return new Proxy(a, { set() { /* pick up displayName and apply it to reaction here */ } })
}
```

Not sure if Mobx accepts it "after its created" so to speak, but for now I just see a ton of `observer()` in my reaction logs which isn't very helpful.

**Comment by xaviergonz** [comment]
There's always defineProperty with a getter and setter, which is like the poor's man proxy

**Comment by xaviergonz** [comment]
Either way though, since Reaction takes a plain string any name change after the fact would require a reaction destruction and re-creation

**Comment by FredyC** [comment]
That's a really ugly escape hatch :) I would rather avoid things that cannot be compiled away from a production build. I cannot help it but using named function instead of anonymous one comes to be as the best solution really.

**Comment by FredyC** [comment]
Another approach I just spotted in some chatroom. This way the observer grabs the name correctly.

```jsx
const Item = () => <div />

export default observer(Item)
```

I've decided to reconsider this whole thing. It's not really a bug. It's coming from the way JS works. Some sufficient approaches have been described, for now, so I am closing.
