### ISSUE TITLE
Question: Why is 'react-selector-hooks' used?

### ISSUE THREAD

**Issue by carlosagsmendes** [mobxjs/mobx-react-lite#45]
Can someone explain why is `react-selector-hooks` being used on the [smart/dumb example](https://github.com/mobxjs/mobx-react-lite#what-about-smartdumb-components)? 

Thanks in advance

**Comment by FredyC** [comment]
Well, it's an example, I just thought it's a cool library :) There are plenty more approaches for sure. What is there to not understand about?

**Comment by carlosagsmendes** [comment]
Thank you @FredyC 

I wanted to understand why it is being used since from my understanding it does memoization. So my question is why do we need to memoize if we are using more and the observer component?

**Comment by FredyC** [comment]
I guess it's a valid concern. I mostly added that example there as a kind of reaction to people being concerned that React hooks are forcing you to have a state in a presentational component. Honestly, it's not related to MobX much and probably shouldn't be there at all.

In case you have an idea on how to improve that example, the PR is welcome :)

**Comment by carlosagsmendes** [comment]
Thanks again, I was just curious.
