### ISSUE TITLE
useObserver causes component to update every time it runs

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-react-lite#47]
It seems like this shouldn't trigger updates in the component. Basically anytime I use `useObserver`, anytime it runs it will update the component which means you lose some of the mobx update performance benefits.

**Comment by FredyC** [comment]
As I said in #48, some example is necessary. It's more likely that rerender happens from the outside based on props change.

**Comment by FredyC** [comment]
Closing for lack of the response.
