### ISSUE TITLE
useDisposable not running

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-react-lite#48]
I'm seeing some sort of bug on this in React 16.8.0-alpha.1, where it runs the first time and then doesn't run again on any update. Opening here until I get a chance to check into it further.

**Comment by FredyC** [comment]
@natew Some example code would be useful for sure :) Ideally CodeSandbox. The `useDisposable` (in the released version 0.3.5) doesn't really do much. Most likely your issue would be with MobX itself. Hard to tell without more info.

**Comment by FredyC** [comment]
Closing for the lack of a response.
