### ISSUE TITLE
mobx-react-lite 0.3.7 does not work with react 16.8.0

### ISSUE THREAD

**Issue by larrymyers** [mobxjs/mobx-react-lite#58]
I tested out an upgrade on react app I'm building from 16.8.0-alpha.1 to 16.8.0.   Best I can tell on some initial analysis, it looks like function components wrapped in observer() aren't rendering when observables are modified in an action.

I verified that this issue is present all the way back to 0.3.4, so it's highly likely that something in the linked changelog below has resulted in a breaking change with mobx-react-lite.

https://reactjs.org/blog/2019/02/06/react-v16.8.0.html#hooks-changelog-since-alpha-versions

I went ahead and created a branch on my mobx-react-lite fork to test the 16.8.0 upgrade, and the result is most of the tests run by jest fail as well.

I'll spend some time digging into what the breaking change is and post any updates to this issue.

**Comment by FredyC** [comment]
Please see #57 :) Once some test issues are resolved, the 1.0.0 will come out ready for this new hotness :)

**Comment by larrymyers** [comment]
@FredyC ah, nice, I hadn't see that PR in flight.

**Comment by FredyC** [comment]
For anyone coming to this issue, release 1.0.0 is what you want.
