### ISSUE TITLE
Setup renovate bot

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#59]
@mweststrate Can you install it and configure for this repo? It's just bunch of DEV dependencies here, but I want to keep them updated. 

https://renovatebot.com

I do not have enough permissions to do that. I verified that when I tried to configure the Stale bot that's already enabled for the org.

**Comment by xaviergonz** [comment]
It should be installed now

**Comment by xaviergonz** [comment]
Btw, do you need something for stale?

**Comment by FredyC** [comment]
Thanks :) Stale is not necessary for now I think, with 8 open issues it's still fairly manageable :)
