### ISSUE TITLE
Using existing observables / global state

### ISSUE THREAD

**Issue by Hizoul** [mobxjs/mobx-react-lite#60]
I was wondering how one is supposed to use existing observable objects with this library.

From what I understand the useObservable creates a new observable that is only available to the component itself.

I have tried the following code for tracking global state successfully
```typescript
import { autorun, observable } from "mobx"
import { useState, useEffect } from "react"

const useGlobalState = (getValue: () => any) => {
  const value = useState(getValue())
  useEffect(() => {
    const destructor = autorun(() => {
      value[1](getValue())
    })
    return () => {
      destructor()
    }
  }, [])
  return value[0]
}

export default useGlobalState
```

Using this hook would offer automatic subscriptions like this
```typescript
import { action, observable } from "mobx"
import * as React from "react"
import useGlobalState from "./useGlobalState"

const state = observable({
  other: "another text"
})

const ExampleComponent: React.FunctionComponent<any> = (props) => {
  const stateValue = useGlobalState(() => state.other)
  return (
    <div>
      Current value is: {stateValue} <br />
      <input value={stateValue} onChange={(event: any) => {
        action(() => {
          state.other = event.nativeEvent.target.value
        })()
       }} />
    </div>
  )
}
```

**Comment by FredyC** [comment]
I am probably missing what you are asking for :) Have you seen https://github.com/mobxjs/mobx-react-lite#why-no-providerinject?

**Comment by xaviergonz** [comment]
Or just pass the observable object as a prop

**Comment by Hizoul** [comment]
So my exact question would be: "Is there a Hook that allows me to reuse an existing observable object instance?" because from what I understand useObservable creates a new instance of an observable for the component, so you can't pass an existing one (e.g. a global observable variable as in my example the `state` variable. I've gathered from here that @FredyC  is not a big fan of those so I understand if my Idea is not appreciated https://github.com/mobxjs/mobx-react-lite/issues/36#issuecomment-450116901).
Also using the `useGlobalState`-Hook that I suggested removes the necessity of using an `observer`-Wrapper around the `React.FunctionComponent` (at least for the use case in question).

**Comment by Hizoul** [comment]
> 
> 
> I am probably missing what you are asking for :) Have you seen https://github.com/mobxjs/mobx-react-lite#why-no-providerinject?

I did see it, read it a few times, but I only just properly understood it after trying it out in code. I realize now how my suggestion is obsolete, so sorry for the waste of time!

**Comment by Hizoul** [comment]
I should also mention the origin of my initial confusion. In the example of the `observer` method the `useObserver` method is used to acquire an `observable` instance.
As a newcomer to MobX it wasn't clear to me that when using the observer you can use ANY observable variable, regardless if acquired through a hook, the injection suggested or just accessing any observable variable that is reachable in the scope (e.g. a global one as I inteded to). Access will in all cases be automatically tracked.
My suggestion to make it more clear to newcomers of MobX is to alter the example of the `observer` method to reflect this more clearly and also adjust the description from "Observables can be passed through props, accessed from context or created locally with useObservable" to something along the lines of "Any observable, regardless of origin, that is accessed within the component will automatically trigger re-renders on change of the accessed properties"

**Comment by FredyC** [comment]
@Hizoul Can you please provide the example which would make it more clear in your opinion?

**Comment by Hizoul** [comment]
Figuring out that the code below is sufficient made me realize the magic of the `observer`-Function.
```typescript
import { action, observable } from "mobx"
import { observer } from "mobx-react-lite"
import * as React from "react"

const state = observable({
  text: " my text "
})

const ExampleComponent = observer((props) => {
  return (
    <div>
      Current value is: {state.text} <br />
      <input
        value={state.text}
        onChange={(event) => {
          action(() => {
            state.text = event.nativeEvent.target.value
          })()
        }}
      />
    </div>
  )
})

export default ExampleComponent
```
I also just read this (https://github.com/mobxjs/mobx-react-lite/issues/62#issuecomment-462176324) and I really agree MobX is so much easier that coming from ReSub / Redux it is hard to grasp that all that is required is to use  the `observer` and MobX magically takes care of the rest :)

**Comment by FredyC** [comment]
Ok, I see what you mean now. I was making those examples so they cover some other hooks to see the bigger picture. We should probably make some more elaborate docs over time. However, at this point, [we are kinda deciding](https://github.com/mobxjs/mobx-react/issues/640) if the lite package should be merged with `mobx-react` so we will see after that.

**Comment by dfee** [comment]
I was actually wondering this exact same thing (also new to MobX). Thanks for the tip @Hizoul 

> "Observables can be passed through props, accessed from context or created locally with useObservable" to something along the lines of "Any observable, regardless of origin, that is accessed within the component will automatically trigger re-renders on change of the accessed properties"

**Comment by FredyC** [comment]
Yesterday I've published an article not exactly about this but could be useful for some learning process.

https://levelup.gitconnected.com/formik-with-react-hooks-and-mobx-1493b5fd607e
