### ISSUE TITLE
Replace "experimental" in GitHub repo description with e.g. "16.8+" or "modern"

### ISSUE THREAD

**Issue by paulreimer** [mobxjs/mobx-react-lite#61]
Now that Hooks are an officially released feature in 16.8 (and this repo is 1.0.0, ready for production use), the word "experimental" could be removed from the GitHub repo description text (and elsewhere it may be used). Not sure what is a better replacement term.

As well, one thing not clear in the README is whether we can still use `class`-based components elsewhere in the hierarchy, not using `mobx` but possibly their children might? Otherwise I suppose `mobx-react` is still recommended?

**Comment by FredyC** [comment]
Thanks, I have missed the repo description :) I've also updated introduction in a README with more detailed instructions. Do you have something else on the mind?

**Comment by paulreimer** [comment]
Oh I see, we can use `mobx-react` and `mobx-react-lite` both at the same time (and eventually migrate to `-lite` completely, if we want).

That's great, thank you!
