### ISSUE TITLE
Bad type, Generic requires one type argument

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-react-lite#64]
In 1.0.0:

```
node_modules/mobx-react-lite/dist/ObserverComponent.d.ts:6:75 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

6 declare function ObserverComponent({ children, render }: IObserverProps): ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) => import("react").Component<any, any, any>)> | null) | (new (props: any) => import("react").Component<any, any, any>)> | null;
```

**Comment by FredyC** [comment]
@natew What version of @types/react are you using? Looking at the master version, the [second generic argument is defined](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L86).

Note: If you are using Yarn be super careful about upgrading, it tends to duplicate different versions of that package which causes weird behavior in types.

**Comment by FredyC** [comment]
I am not entirely sure about this as it's apparently generated by TypeScript itself. We are using `ReactElement<any>` in the code and this is the output. 😮 

```ts
declare function ObserverComponent({ children, render }: IObserverProps): ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) => import("react").Component<any, any, any>)> | null) | (new (props: any) => import("react").Component<any, any, any>)> | null;
```

**Comment by FredyC** [comment]
Either way, closing this as it's a most likely problem of old types package. Feel free to reopen if you have the latest and it's still broken.

**Comment by natew** [comment]
Ah totally my bad, thanks!

>
