### ISSUE TITLE
Can't work with old webpack uglify plugin?

### ISSUE THREAD

**Issue by xwillmadeit** [mobxjs/mobx-react-lite#65]
```js
ERROR in Encountered an error while minifying js/vendor.891a096d.js:
SyntaxError: Unexpected token: keyword (const)
  27927 |
  27928 | function useObservable(initialValue) {
> 27929 |     const observableRef = Object(__WEBPACK_IMPORTED_MODULE_1_react__["useRef"])(null);
        |    ^
  27930 |     if (!observableRef.current) {
  27931 |         observableRef.current = Object(__WEBPACK_IMPORTED_MODULE_0_mobx__["observable"])(initialValue);
  27932 |     }
```

The build version of this package has es6 syntax，but i use webpack-parallel-uglify-plugin，so it breaks my app. Do I have to upgrade my uglify plugin or config my babel-loader to transpile it first?

**Comment by FredyC** [comment]
Is probably related to #63, but yea, would be better if you can update your stack to support ES6. It's kinda strange that you would go with a bleeding edge like React Hooks, but would be still requiring ES5 😕 Alternatively you can try a new and maintained [minifier Terser](https://github.com/terser-js/terser). I am not sure if it has parallel webpack plugin though.

**Comment by xwillmadeit** [comment]
> Is probably related to #63, but yea, would be better if you can update your stack to support ES6. It's kinda strange that you would go with a bleeding edge like React Hooks, but would be still requiring ES5 😕 Alternatively you can try a new and maintained [minifier Terser](https://github.com/terser-js/terser). I am not sure if it has parallel webpack plugin though.

I didn't think too much because react hook is fully backwards-compatible. I use webpack 3+ and can't use [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin)，so its kinda embarrassed... I guess it's time to upgrade webpack to 4+

**Comment by FredyC** [comment]
Yea, this package is meant for like a future proof stacks. Please do try an update and if it turns out impossible, you would need to wait (or contribute) for #63 to get fixed. I will close this now and subscribe there, please.

**Comment by alsotang** [comment]
uglify can not work with es6. It only support es5. First you should compile the module to es5, then uglify it.
