### ISSUE TITLE
How to use "observer" inside a custom hook?

### ISSUE THREAD

**Issue by vitalybe** [mobxjs/mobx-react-lite#67]
I have made a custom hook that looks something like that:

```
export function useProvider(loadingStatusStore) {
  const [providedData, setProvidedData] = useState(undefined);
  const [isLoading, setIsLoading] = useState(true);
  const [isError, setIsError] = useState(false);
  const [sources, setSources] = useState([]);

  useEffect(
    () => {
      (async () => {
        try {
            const providedData = await fetch(metadata);

            setProvidedData(providedData);
            setIsLoading(false);
        } catch (e) {
          setIsError(true);
        }
      })();
    },
    loadingStatusStore ? [loadingStatusStore.lastRefreshDate] : []
  );

  return [providedData, { sources, isLoading, isError }];
}

```

I thought to use an `observable` property from a global (single-instance) store `loadingStatusStore.lastRefreshDate`... But how do I use one inside a custom hook?

`observer` expect a component and `useObserver` complaints that it must be run inside a functional component (which is weird because this hook does run inside a functional component).

The only way I found to make it work is to make the component that uses this hook an `observer`... Which sort=of makes sense but it is a bit too magical - The user of this custom hook needs somehow to know to make the using component an `observer` without a clear indication.

What is the correct way to handle that?

If there is no other way, I'd be happy at least to check if I am running inside an `observer` component and log an error if I don't. But can I know that?

**Comment by FredyC** [comment]
Hooks are trying to be isolated, so they know absolutely nothing about a component they are running in. It's sort of related to the discussion in #7

In your specific case, you can do something like this.

```js
useDisposable(
  () => mobx.reaction(() => loadingStatusStore.lastRefreshDate,
  refreshDate => {
    // here you can rest of the `useEffect`, but you need to use that `refreshDate` here, otherwise, MobX won't even bother running it since you are not really using an observed variable.
  }
)
```

The `useDisposable` (from the package) just ensures that Reaction won't cause memory leak when component unmounts.
