### ISSUE TITLE
Q: What benefits does useObservable have over using setState/Effect directly?

### ISSUE THREAD

**Issue by bestguy** [mobxjs/mobx-react-lite#69]
I'm a big fan of Mobx, and interested in hooks, but struggling to see the benefit of mobx-react-lite.
An external MobX store with `@observable` and `@computed`s still seem very valuable, but `useObservable` and `useComputed` hooks don't seem very useful.

*useObservable:*

```javascript
function ObservePerson(props) {
    const person = useObservable({ name: "John" })
    return (
        <div>
            {person.name}
            <Observer>{() => <div>{person.name}</div>}</Observer>
            <button onClick={() => (person.name = "Mike")}>No! I am Mike</button>
        </div>
    )
}
```

*useState:*

```javascript
function Person(props) {
    const [name, setName] = useState("John");
    return (
        <div>
            <div>{name}</div>
            <button onClick={() => setName("Mike")}>No! I am Mike</button>
        </div>
    )
}
```

They just seem 'different'.  Is there a benefit I'm missing to help explain when people ask?

**Comment by FredyC** [comment]
Well, it's merely a helper function, no need to use it really. There are numerous ways to get hands-on observable variable. If you look [at the code](https://github.com/mobxjs/mobx-react-lite/blob/master/src/useObservable.ts), there is nothing spectacular about it, just abstracting away repeated stuff which you can do own your own.

Difference between `useObservable` and `useState` is mostly about that you don't have setter function, you can just mutate the state and it's done. Once you set the observable value, you can be sure that value is there. React will postpone the actual mutation for "later". MobX approaches it differently and postpones a rendering only.

Note, it's really meant for simple local states with a couple of variables. I would not advice having a big states defined within a component.

Personally, I don't use decorators and classes, they just seem overly ugly to me :) I rather pick the [MST](https://github.com/mobxjs/mobx-state-tree) for a more complex states.

**Comment by bestguy** [comment]
Thanks @FredyC for the info.  Mainly making sure I wasn't missing a performance or other benefit, this helps.
