### ISSUE TITLE
useObservable without observer?

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react-lite#7]
Considering that people can just `useState` or `useReducer` without any wrapping function, they might be rather confused when switching over to `useObservable` that they need to wrap component to the `observer` as well.

@mweststrate Do you think it's actually possible to have `useObservable` truly reactive without any crutches? I can only think of a `forceUpdate` based on `observe` invocation which is essentially what `observer` is doing, right? However, we also want to avoid double rerender if they do wrap it inside the `observer`. Feels tricky.

**Comment by Ciantic** [comment]
In past we have had to add `@observer` on even stateless components to get them update the nested property values. I've always wondered if it were possible to add that observability to *all* components automatically.

Surely if it's possible to remove observe function call, it should be possible to add it to all components automatically?

**Comment by FredyC** [comment]
Well, observability has nothing to do with a state. You can have observable values passed through props into the pure UI component and then you would attach an observer so that component would rerender on its own when one of the observable values changes.

Even if it would be somehow possible to watch over the whole tree, I don't consider it a good idea as it could have a cost in a performance. You have rarely such a _live_ tree that is changing so much.

I am certain that it's possible to make `useObservable` self-aware and forceUpdate containing component whenever a change happens. The only problem is to prevent double rerender when there is `observer` as well.

The `observer` is fairly simple if you look at the source code. There is just a reaction watching over all observable variables within a functional component. So basically to prevent double rerender it would be necessary for this reaction to simply ignore observables coming from `useObservable`.

Perhaps I am all wrong, I am definitely not a MobX expert, just a consumer :) I would rather wait for @mweststrate if he has some idea. Perhaps this whole issue is all wrong :)

**Comment by xaviergonz** [comment]
why not go the other way around? this is

```js
function MyObserverComponent(props) {
  const observe = useObserver();

  return observe(
    <div>props.observable.x</div>
  )
}
```

I think it could have several advantages:
1. you can specify the exact specific piece of code that runs inside the reaction tracking, so you can do observable mutations outside it easily without triggering unwanted renders
2. you can memo your component, forward ref it or whatever you want without observer getting in the middle

Maybe the only disadvantage though is that you actually have to write "observe" or whatever name you assigned over return paths though

Maybe offer it as an alternative to "observer" at least for advance use cases?

**Comment by FredyC** [comment]
Well, isn't the same as the `<Observer />`? Just a more functional sugar and honestly that double return feels weird :)

However, the point of this issue is to be able to have `useObservable` without worrying about the need to attach `observer`. That part is easy, but how prevent double render if used together, that's the major issue.

**Comment by FredyC** [comment]
I think we can close this as nothing revolutionary will happen around this.

**Comment by ikatun** [comment]
This package might be interesting for this topic: https://www.npmjs.com/package/use-mobx-store

It's not exactly a real hook, it's a bit hacky attempt to emulate a hook but it might be fun to try it out :)

**Comment by FredyC** [comment]
@ikatun I think it's a bad road to follow because of the upcoming Concurrent mode where multiple components will probably render at the same time. It could be rather error-prone unless I am misunderstanding something here.

**Comment by FredyC** [comment]
Also note, there [two new options in MobX](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#5140--4140) that can help discover if a component is a missing observer. It's more of the defensive approach because possible issues are caught in runtime, not sooner. It would work with the assumption there is enough coverage in tests that basically try to render each component.

**Comment by ikatun** [comment]
I agree about the concurrency issue.

Nice, didn't know about those new options.
Could use them to make internal implementation concurrency-friendly , but the hook-like interface of the library could probably stay the same.

I've lost countless hours because of forgetting to decorate component with HOC :)
