### ISSUE TITLE
Using const MyComponent = observer((props) => to create observer component makes unnamed component <Memo(wrappedComponent)>  in React DevTools

### ISSUE THREAD

**Issue by uffou** [mobxjs/mobx-react-lite#73]
I know useObserver is the preferred approach but still, sometimes observer is needed, is this a known issue are there plans to get the proper name instead of this?
![image](https://user-images.githubusercontent.com/2581788/53761810-18fe9280-3ecf-11e9-88c0-05adfbb9963f.png)
![image](https://user-images.githubusercontent.com/2581788/53761992-8dd1cc80-3ecf-11e9-8ca1-4e34273c8fa6.png)

**Comment by FredyC** [comment]
What version are you using? @mweststrate has been fiddling around this recently #70. The 1.0.1 version might be better in theory.

**Comment by MatejBransky** [comment]
I have the similar problem. I'm using `mobx-react-lite` version `1.1.0`.

React DevTools:
![image](https://user-images.githubusercontent.com/20944757/53872721-1b600a00-3fff-11e9-94bb-ee8d14030938.png)
Source code:
```jsx
import React, { useContext } from 'react';
import { observer } from 'mobx-react-lite';

import TimerContext from './TimerStore';

const TimerView = observer(() => {
  const timerStore = useContext(TimerContext);

  return (
    <button onClick={timerStore.reset}>
      Seconds passed: {timerStore.timer}
    </button>
  );
});
```

**Comment by FredyC** [comment]
Yea, the last approach is pretty much what I wanted to suggest. I don't generally like default exports though, so it's an annoying tradeoff.

I think this could be solved by writing a simple macro for `babel-plugin-macros`, but I don't have experience with AST stuff. Volunteers? :)

**Comment by uffou** [comment]
@MatejBransky @FredyC thanks, I will try with export default

**Comment by mweststrate** [comment]
These two approaches will both work to create non-default named exports:

```javascript
let MyComponent1_ = () => "hello1!"; // N.B. 'MyComponent1_' is what shows up in devtools
export const MyComponent1 = observer(MyComponent1_);

export const MyComponent2 = observer(() => "hello2!");
MyComponent2.displayName = "MyComponent2";
```

Demo: https://codesandbox.io/s/w038r5q68w

**Comment by mweststrate** [comment]
This works as well: 

```javascript
let MyComponent4 = () => "hello4!";
MyComponent4 = observer(MyComponent4);
export { MyComponent4 };
```

**Comment by FredyC** [comment]
I am wondering how our other HOCs solving this. None of the mentioned solutions are exactly sexy imo. I guess people are generally more ok with default export than it seems.

I would say that `useObserver` is ultimately the best approach. For me, it actually works as some sort of mental boundary that `useObserver` is a last hook in the component and no `return` can be before that.

```jsx
export const RandomGiphy = ({ tag }) => {
  const { data, loading } = useQuery(
    RandomGiphyQuery, {
      variables: { tag }
    }
  }
  return useObserver(() => {
    if (loading) {
      return <Spinner />
    }
    return <img src={data.giphy.random.url} />
  })
}
```

**Comment by FredyC** [comment]
Fix released in v1.1.1

**Comment by asfernandes** [comment]
What about allow something like this?

```ts
export Comp = observer(() => "test", { displayName: "Comp" });
```

**Comment by FredyC** [comment]
@asfernandes That feels way too verbose in comparison to...

```js
export const Comp = observer(function Comp() {
  return "test"
})
```

**Comment by asfernandes** [comment]
If component is generic, I currently need to do that, with is much more verbose:

```ts
export const Grid: <T extends object>(props: GridProps<T>) => React.ReactElement<GridProps<T>> =
	observer(function GridFunc<T extends object>(props: GridProps<T>)
{ ... });
```

**Comment by FredyC** [comment]
I know that pain well, but it's not like you have all components generic, is it? :) I usually opt for this approach even though I dislike default exports, it's really rare to be worried about it.

```ts
function Grid<T>(props: GridProps<T>): React.ReactElement {
  
}

export default observer(Grid)
```

**Comment by bernhardc** [comment]
Because I don't like to write the component name twice, I wrote a small Webpack loader to help with this issue. Thought I'd share it with you.
This loader uses a simple regex to convert declarations in the format

```javascript
export const MyComponent = observer(() => { /* ... */ }
```
to
```javascript
export const MyComponent = observer(function MyComponent() { /* ... */ }
```

It also works for components with props:
```javascript
export const MyComponent = observer(props => { /* ... */ }
export const MyComponent = observer((props: MyComponentProps) => { /* ... */ } // Typescript
```

To use this, create a file `mobx-component-prettifier.js` for the loader:
```javascript
module.exports = function(source) {
	return source.replace(
		/const ([^ =]*)[ ]*=[ ]*observer[ ]*\([ ]*\(?([^)=]*)\)?[ ]*=>/,
		"const $1 = observer(function $1($2)"
	);
}
```

Then add the loader to your Javascript/Typescript compilation process in your `webpack.config.js` (assuming the loader file is in the same directory as your Webpack config), for example:
```javascript
{
	test: /\.jsx?$/,
	use: [
		{ loader: "babel-loader" },
		{ loader: path.resolve("mobx-component-prettifier.js") }
	]
}
```

**Comment by FredyC** [comment]
@bernhardc I am thinking this might be better handled with `babel-plugin-macros`, it wouldn't require any sort of configuration and we could include that macro in the package.

**Comment by bernhardc** [comment]
@FredyC Yes, this would be a lot less hacky of course. I will look into it if I can free some time.

**Comment by bernhardc** [comment]
OK, I did it. It was actually fun to learn more about Babel internals. I created a PR. It still needs some work to integrate it into this package, but the macro itself works.

**Comment by MohitPrakashSharma** [comment]
**`MyComponent.jsx`**

```
import { observer } from "mobx-react-lite";

let MyComponent1_ = () => "hello1!";
export const MyComponent1 = observer(MyComponent1_);

export const MyComponent2 = observer(() => "hello2!");
MyComponent2.displayName = "MyComponent2";

export const MyComponent3 = observer(function MyComponent3() {
  return "hello3!";
});

let MyComponent4 = () => "hello4!";
MyComponent4 = observer(MyComponent4);
export { MyComponent4 };

```
`**Index.js**`


```
import "./styles.css";

function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <MyComponent1 />
      <MyComponent2 />
      <MyComponent3 />
      <MyComponent4 />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

**Comment by mweststrate** [comment]
This section probably answers your question:
https://mobx.js.org/best/pitfalls.html#the-display-name-of-react-components-is-not-set

**Comment by Obi-Dann** [comment]
Hi @mweststrate, the solution setting `displayName` is no longer working for me
```
export const MyComponent2 = observer(() => "hello2!");
MyComponent2.displayName = "MyComponent2";
```
I upgraded [your demo to the latest version of react and mobx](https://codesandbox.io/s/clever-pasteur-jlegq?file=/src/MyComponent.jsx) and `MyComponent2` does not have name in react dev tools
![image](https://user-images.githubusercontent.com/12251341/89595748-73acd280-d8a9-11ea-8a8e-f4c5c8a12b47.png)

Just wanted to emphasise that I really like the suggestion from @asfernandes
> What about allow something like this?
> 
> ```ts
> export const Comp = observer(() => "test", { displayName: "Comp" });
> ```
It might be a bit verbose, but IMHO it's the best because of how explicit it is. All other solutions (except for MyComponent2.displayName = 'MyComponent2'`) don't communicate `why` this function is written in such way and can be easily unintentionally refactored without noticing by other devs or new transpilation/minification tools.

**Comment by da1z** [comment]
So what is the recommended approach right now?

**Comment by mweststrate** [comment]
Use a named function or use React 17 and set displayName (its still broken
in 16 afaik)
