### ISSUE TITLE
Question: Should we extract `PropTypes` out of `mobx-react` ?

### ISSUE THREAD

**Issue by chux0519** [mobxjs/mobx-react-lite#76]
I'm trying to use `mobx-react-lite` instead of `mobx-react`, and everything just works well except I have to use `PropTypes` of `mobx-react`, which force me to depend on the `mobx-react` package again.

Should we extract `PropTypes` out of `mobx-react` ? Maybe a new package named `mobx-prop-types` or else.

Or should we integrate `PropTypes` in `mobx-react-lite` also?

**Comment by FredyC** [comment]
Um, what do you mean? PropTypes of what exactly? Only `Observer` components need that and it has it.

**Comment by chux0519** [comment]
for example:

```javascript
...
import { PropTypes as OPropTypes } from 'mobx-react';
function MyComponent(props) {
...
}
MyComponent.propTypes = {
  someObservableObject: OPropTypes.observableObject.isRequired
}
```

say, I have a functional component which takes observable object in its props, and I have to use `PropTypes` from `mobx-react`

**Comment by FredyC** [comment]
Sorry, I haven't used PropTypes for the past 3 years since I am using TypeScript. Have a look at roadmap for [`mobx-react` V6](https://github.com/mobxjs/mobx-react/issues/640). Separating into a package is on the checklist. If you like, you could contribute to speed things up as V6 might still take some time to finalize.

**Comment by chux0519** [comment]
> Sorry, I haven't used PropTypes for the past 3 years since I am using TypeScript. Have a look at the roadmap for [`mobx-react` V6](https://github.com/mobxjs/mobx-react/issues/640). Separating PropTypes into a package is on the checklist. If you like, you could contribute to speed things up as V6 might still take some time to finalize.

Thanks for your information, I'm willing to help this, will check this out later
